#pragma once
// AUTO-GENERATED from web/. Do NOT edit by hand - run "npm run build".

static const char PORTAL_HTML[] =
"<!doctype html>\n"
"<html lang=\"de\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,viewport-fit=cover\">\n"
"<title>EUL22 Konfiguration</title>\n"
"<style>\n"
":root {\n"
"  color-scheme: light dark;\n"
"  --bg:#fff;\n"
"  --panel:#fafafa;\n"
"  --fg:#222;\n"
"  --hint:#666;\n"
"  --muted:#f0f0f0;\n"
"  --brand:#0057b7;\n"
"  --brand-fg:#fff;\n"
"  --danger:#a20000;\n"
"  --border:#ddd;\n"
"  --accent-focus:rgba(0,87,183,0.25);\n"
"}\n"
"@media (prefers-color-scheme: dark) {\n"
"  :root {\n"
"    --bg:#1b1b1e;\n"
"    --panel:#232327;\n"
"    --fg:#e6e6e6;\n"
"    --hint:#a0a0a0;\n"
"    --muted:#2b2b2f;\n"
"    --border:#3a3a3f;\n"
"    --accent-focus:rgba(255,255,255,0.15);\n"
"  }\n"
"}\n"
"* { box-sizing:border-box; }\n"
"html,body { margin:0; padding:0; background:var(--bg); color:var(--fg); }\n"
"body {\n"
"  font-family:system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",Helvetica,Arial,sans-serif;\n"
"  font-size:15px;\n"
"  line-height:1.45;\n"
"  min-height:100vh;\n"
"  display:flex;\n"
"  flex-direction:column;\n"
"}\n"
"\n"
"/* --- Header + Tabs --------------------------------------------------- */\n"
"header {\n"
"  padding:12px 16px 8px;\n"
"  border-bottom:1px solid var(--border);\n"
"  background:var(--panel);\n"
"}\n"
"header h1 { margin:0; font-size:1.2em; }\n"
"header .status { font-size:0.85em; color:var(--hint); margin-top:4px; }\n"
"nav.tabs {\n"
"  display:flex;\n"
"  overflow-x:auto;\n"
"  border-bottom:1px solid var(--border);\n"
"  background:var(--panel);\n"
"  -webkit-overflow-scrolling:touch;\n"
"  scrollbar-width:none;\n"
"}\n"
"nav.tabs::-webkit-scrollbar { display:none; }\n"
"nav.tabs button {\n"
"  flex:1;\n"
"  min-width:80px;\n"
"  background:transparent;\n"
"  color:var(--fg);\n"
"  border:0;\n"
"  border-bottom:3px solid transparent;\n"
"  padding:12px 8px;\n"
"  font-size:14px;\n"
"  font-weight:500;\n"
"  cursor:pointer;\n"
"  transition:color 0.15s, border-color 0.15s;\n"
"  white-space:nowrap;\n"
"}\n"
"nav.tabs button:hover { background:var(--muted); }\n"
"nav.tabs button.active {\n"
"  color:var(--brand);\n"
"  border-bottom-color:var(--brand);\n"
"}\n"
"\n"
"/* --- Main content ---------------------------------------------------- */\n"
"main {\n"
"  flex:1;\n"
"  padding:12px 16px 100px;   /* bottom padding fuer sticky footer */\n"
"  width:100%;                /* volle Fensterbreite */\n"
"  margin:0 auto;\n"
"}\n"
".tab { display:none; }\n"
".tab.active { display:block; }\n"
"\n"
"fieldset {\n"
"  border:1px solid var(--border);\n"
"  border-radius:6px;\n"
"  padding:12px;\n"
"  margin:0 0 14px;\n"
"  background:var(--panel);\n"
"}\n"
"legend { padding:0 6px; font-weight:600; font-size:0.95em; }\n"
"\n"
"label {\n"
"  display:block;\n"
"  margin:8px 0 3px;\n"
"  font-size:13px;\n"
"  color:var(--hint);\n"
"}\n"
"label.inline {\n"
"  display:inline-flex;\n"
"  align-items:center;\n"
"  gap:6px;\n"
"  color:var(--fg);\n"
"  font-size:14px;\n"
"  margin:6px 0;\n"
"}\n"
"label.inline input { margin:0; }\n"
"\n"
"input[type=text], input[type=password], input[type=number], select {\n"
"  width:100%;\n"
"  padding:10px 12px;\n"
"  font-size:16px;      /* verhindert iOS-zoom */\n"
"  background:var(--bg);\n"
"  color:var(--fg);\n"
"  border:1px solid var(--border);\n"
"  border-radius:6px;\n"
"  outline:none;\n"
"}\n"
"input:focus, select:focus { border-color:var(--brand); box-shadow:0 0 0 3px var(--accent-focus); }\n"
"\n"
"button {\n"
"  padding:10px 16px;\n"
"  border:0;\n"
"  border-radius:6px;\n"
"  background:var(--brand);\n"
"  color:var(--brand-fg);\n"
"  cursor:pointer;\n"
"  font-size:14px;\n"
"  font-weight:500;\n"
"  min-height:40px;\n"
"  transition:transform 0.05s, background 0.15s;\n"
"}\n"
"button:active { transform:scale(0.97); }\n"
"button.ghost { background:var(--muted); color:var(--fg); }\n"
"button.danger { background:var(--danger); color:#fff; }\n"
"button:disabled { opacity:0.5; cursor:not-allowed; }\n"
"\n"
".row { display:flex; gap:8px; align-items:center; flex-wrap:wrap; }\n"
".row > * { min-width:0; }\n"
".row > input, .row > select { flex:1; }\n"
"\n"
".hint { font-size:0.85em; color:var(--hint); margin-top:4px; }\n"
".mono {\n"
"  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;\n"
"  background:var(--muted);\n"
"  padding:8px 10px;\n"
"  border-radius:4px;\n"
"  word-break:break-all;\n"
"  font-size:13px;\n"
"}\n"
"\n"
"/* --- Password + Secret --- */\n"
".pw-wrap { position:relative; display:block; }\n"
".pw-wrap input { padding-right:48px; }\n"
".pw-eye {\n"
"  position:absolute;\n"
"  right:4px;\n"
"  top:50%;\n"
"  transform:translateY(-50%);\n"
"  background:transparent;\n"
"  color:var(--hint);\n"
"  padding:8px;\n"
"  border:0;\n"
"  cursor:pointer;\n"
"  min-height:32px;\n"
"  min-width:36px;\n"
"  border-radius:4px;\n"
"  line-height:0;\n"
"}\n"
".pw-eye:hover { color:var(--fg); background:var(--muted); }\n"
".pw-eye svg { display:block; }\n"
"\n"
".secret {\n"
"  display:flex;\n"
"  align-items:center;\n"
"  gap:6px;\n"
"  background:var(--muted);\n"
"  padding:6px 8px;\n"
"  border-radius:6px;\n"
"  min-height:38px;\n"
"}\n"
".secret .val {\n"
"  flex:1;\n"
"  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;\n"
"  font-size:13px;\n"
"  word-break:break-all;\n"
"  user-select:all;\n"
"  -webkit-user-select:all;\n"
"}\n"
".secret .pw-eye { position:static; transform:none; }\n"
"\n"
"/* --- Table (Verbindungen) ------------------------------------------- */\n"
"table { width:100%; border-collapse:collapse; font-size:13px; }\n"
"th { text-align:left; font-weight:600; color:var(--hint); border-bottom:1px solid var(--border); padding:8px 6px; font-size:12px; text-transform:uppercase; letter-spacing:0.03em; }\n"
"td { padding:8px 6px; border-bottom:1px solid var(--muted); }\n"
"tr:last-child td { border-bottom:0; }\n"
"\n"
"@media (max-width:520px) {\n"
"  /* Table -> Card layout auf schmalen screens */\n"
"  table.responsive thead { display:none; }\n"
"  table.responsive tr {\n"
"    display:block;\n"
"    padding:8px 0;\n"
"    border-bottom:1px solid var(--border);\n"
"  }\n"
"  table.responsive tr:last-child { border-bottom:0; }\n"
"  table.responsive td {\n"
"    display:flex;\n"
"    justify-content:space-between;\n"
"    align-items:baseline;\n"
"    padding:3px 0;\n"
"    border:0;\n"
"    text-align:right !important;\n"
"  }\n"
"  table.responsive td::before {\n"
"    content:attr(data-label);\n"
"    color:var(--hint);\n"
"    font-size:0.85em;\n"
"    font-weight:500;\n"
"    margin-right:12px;\n"
"    text-transform:uppercase;\n"
"    letter-spacing:0.03em;\n"
"    text-align:left;\n"
"  }\n"
"}\n"
"\n"
"/* --- Konsole -------------------------------------------------------- */\n"
"pre.console {\n"
"  background:#0f0f10;\n"
"  color:#dcdcdc;\n"
"  padding:10px 12px;\n"
"  border-radius:6px;\n"
"  font-size:12px;\n"
"  line-height:1.4;\n"
"  height:60vh;\n"
"  min-height:280px;\n"
"  max-height:520px;\n"
"  overflow:auto;\n"
"  overflow-x:auto;\n"
"  white-space:pre-wrap;\n"
"  word-break:break-all;\n"
"  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;\n"
"  user-select:text;\n"
"  -webkit-user-select:text;\n"
"  tab-size:2;\n"
"  margin:8px 0 0;\n"
"}\n"
"pre.console:focus {\n"
"  outline:2px solid var(--brand);\n"
"  outline-offset:2px;\n"
"}\n"
"\n"
"/* --- Sticky footer -------------------------------------------------- */\n"
"footer.actions {\n"
"  position:sticky;\n"
"  bottom:0;\n"
"  left:0;\n"
"  right:0;\n"
"  padding:10px 16px calc(10px + env(safe-area-inset-bottom));\n"
"  border-top:1px solid var(--border);\n"
"  background:color-mix(in srgb, var(--panel) 92%, transparent);\n"
"  backdrop-filter:blur(8px);\n"
"  -webkit-backdrop-filter:blur(8px);\n"
"  display:flex;\n"
"  gap:8px;\n"
"  justify-content:center;\n"
"  width:100%;\n"
"  margin:0 auto;\n"
"}\n"
"footer.actions button {\n"
"  flex:1;\n"
"  min-height:44px;\n"
"}\n"
"footer.actions .save { flex:2; }\n"
"\n"
"/* Sehr schmal: Buttons untereinander */\n"
"@media (max-width:380px) {\n"
"  footer.actions { flex-direction:column; }\n"
"  footer.actions button { min-height:40px; }\n"
"}\n"
"\n"
"/* --- Sonstiges ----------------------------------------------------- */\n"
"hr { border:0; border-top:1px solid var(--border); margin:12px 0; }\n"
"code { background:var(--muted); padding:1px 4px; border-radius:3px; font-size:0.9em; }\n"
"a { color:var(--brand); }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"\n"
"<header>\n"
"  <h1>Busware EUL22</h1>\n"
"  <div class=\"status\" id=\"status\">lade...</div>\n"
"</header>\n"
"\n"
"<nav class=\"tabs\" id=\"tabs\">\n"
"  <button data-tab=\"status\" class=\"active\">Status</button>\n"
"  <button data-tab=\"allgemein\">Allgemein</button>\n"
"  <button data-tab=\"wifi\">WiFi</button>\n"
"  <button data-tab=\"usb\">USB</button>\n"
"  <button data-tab=\"enocean\">EnOcean</button>\n"
"  <button data-tab=\"api\">API</button>\n"
"  <button data-tab=\"events\">Events</button>\n"
"  <button data-tab=\"konsole\">Konsole</button>\n"
"</nav>\n"
"\n"
"<main>\n"
"\n"
"  <!-- ============================================================ Status -->\n"
"  <section class=\"tab active\" id=\"tab-status\">\n"
"    <fieldset><legend>Gateway</legend>\n"
"      <div id=\"gwstat\" class=\"mono\" style=\"white-space:pre\">lade...</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Aktive Verbindungen</legend>\n"
"      <table class=\"responsive\">\n"
"        <thead>\n"
"          <tr><th>Peer</th><th>Uptime</th><th>RX</th><th>TX</th><th>Frames</th></tr>\n"
"        </thead>\n"
"        <tbody id=\"cli_body\">\n"
"          <tr><td colspan=\"5\" class=\"hint\">keine aktiven Verbindungen</td></tr>\n"
"        </tbody>\n"
"      </table>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Telegramme</legend>\n"
"      <div style=\"max-height:42vh;overflow:auto\">\n"
"        <table class=\"responsive\">\n"
"          <thead>\n"
"            <tr><th>Zeit</th><th>Ri.</th><th>RORG</th><th>Absender</th><th>Daten</th><th>Bedeutung</th><th>dBm</th></tr>\n"
"          </thead>\n"
"          <tbody id=\"tel_body\">\n"
"            <tr><td colspan=\"7\" class=\"hint\">warte auf Telegramme...</td></tr>\n"
"          </tbody>\n"
"        </table>\n"
"      </div>\n"
"      <div class=\"hint\">Dekodierte EnOcean-Funktelegramme (live, neueste oben). <code>&#8595;</code> empfangen vom TCM515 · <code>&#8593;</code> an den TCM515 gesendet.</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>TCM515-Statistik</legend>\n"
"      <div id=\"stats\" class=\"mono\" style=\"white-space:pre\">-</div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- ========================================================= Allgemein -->\n"
"  <section class=\"tab\" id=\"tab-allgemein\">\n"
"    <fieldset><legend>Geraet</legend>\n"
"      <label>Geraetename</label>\n"
"      <input type=\"text\" id=\"dev_name\" maxlength=\"39\" autocomplete=\"off\" placeholder=\"z.B. EnOcean Gateway Flur\">\n"
"      <div class=\"hint\">Anzeigename im Portal-Titel und in Home Assistant.</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Portal-Login</legend>\n"
"      <label>Benutzer</label>\n"
"      <input type=\"text\" id=\"admin_user\" maxlength=\"23\" autocomplete=\"off\" placeholder=\"admin\">\n"
"      <label>Aktuelles Passwort <span class=\"hint\">(nur beim Erst-Setup sichtbar)</span></label>\n"
"      <div id=\"adminp\" class=\"secret\"></div>\n"
"      <label>Neues Passwort <span class=\"hint\">(leer = unveraendert, min. 8 Zeichen)</span></label>\n"
"      <input type=\"password\" id=\"admin_pass_new\" maxlength=\"63\" placeholder=\"unveraendert\" autocomplete=\"off\" data-eye>\n"
"      <div class=\"hint\">Login fuer dieses Portal im Normalbetrieb (STA-Modus).</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Zeit (NTP)</legend>\n"
"      <label>NTP-Server</label>\n"
"      <input type=\"text\" id=\"ntp_server\" maxlength=\"63\" autocomplete=\"off\" placeholder=\"pool.ntp.org\">\n"
"      <label>Zeitzone</label>\n"
"      <select id=\"tz\"></select>\n"
"      <div class=\"hint\">Sommer-/Winterzeit wird gemaess Zone automatisch umgestellt.</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Firmware</legend>\n"
"      <div id=\"fw_info\" class=\"mono\" style=\"white-space:pre\">-</div>\n"
"      <label>Update einspielen (.bin)</label>\n"
"      <div class=\"row\">\n"
"        <input type=\"file\" id=\"ota_file\" accept=\".bin\">\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-ota\">Hochladen &amp; Update</button>\n"
"      </div>\n"
"      <div id=\"ota_progress\" class=\"hint\">Datei: <code>.pio/build/busware-eul22/firmware.bin</code>. Das Geraet startet nach erfolgreichem Update automatisch neu.</div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- ============================================================== WiFi -->\n"
"  <section class=\"tab\" id=\"tab-wifi\">\n"
"    <fieldset><legend>WLAN (Heimnetz)</legend>\n"
"      <label>SSID</label>\n"
"      <div class=\"row\">\n"
"        <select id=\"ssid_sel\"><option value=\"\">-- Netzwerk waehlen --</option></select>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-scan\">Suchen</button>\n"
"      </div>\n"
"      <label>oder SSID manuell</label>\n"
"      <input type=\"text\" id=\"ssid\" maxlength=\"32\" autocomplete=\"off\">\n"
"      <label>Passwort <span class=\"hint\">(Auge-Button zum Anzeigen)</span></label>\n"
"      <input type=\"password\" id=\"pass\" maxlength=\"63\" placeholder=\"(nicht gesetzt)\" autocomplete=\"off\" data-eye>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- =============================================================== USB -->\n"
"  <section class=\"tab\" id=\"tab-usb\">\n"
"    <fieldset><legend>USB-CDC-Bridge</legend>\n"
"      <label class=\"inline\"><input type=\"checkbox\" id=\"usb_en\"> USB als transparente ESP3-Bridge aktivieren</label>\n"
"      <div class=\"hint\">Erlaubt Direkt-Zugriff auf den TCM515 ueber die USB-C-Buchse als virtuellen COM-Port. Aus Sicherheitsgruenden (CRA) standardmaessig aus.</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Hinweis</legend>\n"
"      <div class=\"hint\">\n"
"        USB-Traffic wird nicht in die Web-Konsole gespiegelt. Zur Diagnose am USB-Kanal\n"
"        lokal <code>pio device monitor</code> oder <code>screen /dev/cu.usbmodemXXXX 460800</code> verwenden.\n"
"      </div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- =========================================================== EnOcean -->\n"
"  <section class=\"tab\" id=\"tab-enocean\">\n"
"    <fieldset><legend>TCP-Bridge (Home Assistant / FHEM / ...)</legend>\n"
"      <label class=\"inline\"><input type=\"checkbox\" id=\"tcp_en\"> TCP-Server aktivieren</label>\n"
"      <label>Port</label>\n"
"      <input type=\"number\" id=\"tcp_port\" value=\"5100\" min=\"1\" max=\"65535\">\n"
"      <label class=\"inline\"><input type=\"checkbox\" id=\"tcp_auth\"> AUTH-Token verlangen <span class=\"hint\">(empfohlen)</span></label>\n"
"      <label>Aktueller Token</label>\n"
"      <div class=\"row\">\n"
"        <div id=\"token\" class=\"secret\"></div>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-regen\">Neu erzeugen</button>\n"
"      </div>\n"
"      <div class=\"hint\">Handshake: Server sendet <code>HELLO EUL22 v1 AUTH-REQUIRED</code>, Client antwortet mit <code>AUTH &lt;token&gt;</code>.</div>\n"
"      <hr>\n"
"      <button type=\"button\" class=\"ghost\" id=\"btn-preset-ha\">Preset: HA-Eltako Integration</button>\n"
"      <div class=\"hint\">Setzt Port 5100 + Auth aus (MGW-LAN-Konvention der <a href=\"https://github.com/FMDHET/home-assistant-eltako\" target=\"_blank\" rel=\"noopener\">Eltako HA-Integration</a>).</div>\n"
"      <div id=\"ha_yaml_box\" style=\"display:none;margin-top:10px\">\n"
"        <label>HA-Config (nach Speichern &amp; Neustart einsetzbar)</label>\n"
"        <pre id=\"ha_yaml\" class=\"mono\" style=\"white-space:pre;overflow:auto;font-size:12px;padding:10px\"></pre>\n"
"      </div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- =============================================================== API -->\n"
"  <section class=\"tab\" id=\"tab-api\">\n"
"    <fieldset><legend>REST-API</legend>\n"
"      <label class=\"inline\"><input type=\"checkbox\" id=\"api_en\"> REST-API aktivieren</label>\n"
"      <div class=\"hint\">HTTP-Zugriff auf empfangene Telegramme und zum Senden. Authentifizierung ueber den Geraete-Token, per Header <code>Authorization: Bearer &lt;token&gt;</code> oder Query <code>?token=&lt;token&gt;</code>.</div>\n"
"      <label>Geraete-Token</label>\n"
"      <div class=\"row\">\n"
"        <div id=\"api_token\" class=\"secret\"></div>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-regen2\">Neu erzeugen</button>\n"
"      </div>\n"
"      <div class=\"hint\">Derselbe Token wie fuer die TCP-Bridge (Reiter EnOcean).</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Endpunkte</legend>\n"
"      <pre id=\"api_doc\" class=\"mono\" style=\"white-space:pre-wrap;overflow:auto;font-size:12px;padding:10px\">API deaktiviert oder Adresse unbekannt.</pre>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- ============================================================ Events -->\n"
"  <section class=\"tab\" id=\"tab-events\">\n"
"    <fieldset><legend>Ereignisse</legend>\n"
"      <div style=\"max-height:60vh;overflow:auto\">\n"
"        <table class=\"responsive\">\n"
"          <thead>\n"
"            <tr><th>Zeit</th><th>Level</th><th>Quelle</th><th>Meldung</th></tr>\n"
"          </thead>\n"
"          <tbody id=\"evt_body\">\n"
"            <tr><td colspan=\"4\" class=\"hint\">warte auf Ereignisse...</td></tr>\n"
"          </tbody>\n"
"        </table>\n"
"      </div>\n"
"      <div class=\"hint\">Boot, WLAN (Verbindung/Trennung mit Grund), TCP-Clients, MQTT, Security, periodischer Netz-Status. Neueste oben.</div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- =========================================================== Konsole -->\n"
"  <section class=\"tab\" id=\"tab-konsole\">\n"
"    <fieldset><legend>Live-Datenverkehr</legend>\n"
"      <div class=\"row\" style=\"margin-bottom:6px\">\n"
"        <label class=\"inline\" style=\"flex:1\"><input type=\"checkbox\" id=\"autoscroll\" checked> Auto-Scroll</label>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-copy\">Kopieren</button>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-clear\">Leeren</button>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-pause\">Pause</button>\n"
"      </div>\n"
"      <pre id=\"con\" class=\"console\" tabindex=\"0\" aria-label=\"Konsole. Klicken oder fokussieren, dann Strg+A um Inhalt zu markieren.\"></pre>\n"
"      <div class=\"hint\">\n"
"        <code>&lt; TCM</code> = vom Modul empfangen, <code>&gt; ip:port</code> = von diesem Client gesendet.\n"
"        Fokus auf die Konsole (Klick) und <code>Strg+A</code> / <code>Cmd+A</code> markiert nur die Konsole.\n"
"      </div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"</main>\n"
"\n"
"<footer class=\"actions\">\n"
"  <button type=\"button\" class=\"save\" id=\"btn-save\">Speichern</button>\n"
"  <button type=\"button\" class=\"ghost\" id=\"btn-reboot\">Neustart</button>\n"
"  <button type=\"button\" class=\"danger\" id=\"btn-factory\">Werkseinstellungen</button>\n"
"</footer>\n"
"\n"
"<script>\"use strict\";(()=>{var B='<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M1 12s4-8 11-8 11 8 11 8-4 8-11 8S1 12 1 12z\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/></svg>',v='<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M17.94 17.94A10.94 10.94 0 0 1 12 20c-7 0-11-8-11-8a19.4 19.4 0 0 1 5.06-5.94\"/><path d=\"M9.9 4.24A11 11 0 0 1 12 4c7 0 11 8 11 8a19.3 19.3 0 0 1-2.16 3.19\"/><path d=\"M14.12 14.12a3 3 0 1 1-4.24-4.24\"/><line x1=\"1\" y1=\"1\" x2=\"23\" y2=\"23\"/></svg>';function r(e){let t=document.getElementById(e);if(!t)throw new Error(`#${e} not found`);return t}function i(e){r(\"status\").textContent=e}function N(){return window.location.hostname}function h(e){document.querySelectorAll(\"nav.tabs button\").forEach(t=>{t.classList.toggle(\"active\",t.dataset.tab===e)}),document.querySelectorAll(\".tab\").forEach(t=>{t.classList.toggle(\"active\",t.id===`tab-${e}`)}),location.hash!==`#${e}`&&history.replaceState(null,\"\",`#${e}`)}function g(){return document.querySelector(\"nav.tabs button.active\")?.dataset.tab??\"\"}function U(){document.querySelectorAll(\"nav.tabs button\").forEach(t=>{t.addEventListener(\"click\",()=>h(t.dataset.tab))});let e=location.hash.replace(\"#\",\"\");e&&document.getElementById(`tab-${e}`)&&h(e),window.addEventListener(\"hashchange\",()=>{let t=location.hash.replace(\"#\",\"\");t&&document.getElementById(`tab-${t}`)&&h(t)})}function W(){document.querySelectorAll(\"input[data-eye]\").forEach(e=>{let t=document.createElement(\"div\");t.className=\"pw-wrap\",e.parentNode.insertBefore(t,e),t.appendChild(e);let n=document.createElement(\"button\");n.type=\"button\",n.className=\"pw-eye\",n.setAttribute(\"aria-label\",\"Passwort anzeigen\"),n.innerHTML=v,t.appendChild(n),n.addEventListener(\"click\",()=>{let s=e.type===\"password\";e.type=s?\"text\":\"password\",n.innerHTML=s?B:v,n.setAttribute(\"aria-label\",s?\"Passwort verbergen\":\"Passwort anzeigen\")})})}var f=class{constructor(t){this.host=t;this.value=\"\";this.revealed=!1;this.host.innerHTML='<span class=\"val\"></span><button type=\"button\" class=\"pw-eye\" aria-label=\"anzeigen\"></button>',this.valueEl=this.host.querySelector(\".val\"),this.btn=this.host.querySelector(\".pw-eye\"),this.btn.addEventListener(\"click\",()=>{this.revealed=!this.revealed,this.render()}),this.render()}set(t){this.value=t,this.render()}render(){this.value?this.revealed?this.valueEl.textContent=this.value:this.valueEl.textContent=\"\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\":this.valueEl.textContent=\"\\u2014\",this.btn.innerHTML=this.revealed?B:v,this.btn.setAttribute(\"aria-label\",this.revealed?\"verbergen\":\"anzeigen\")}};async function c(e,t){let n=await fetch(e,t);if(!n.ok)throw new Error(`${n.status}: ${await n.text()}`);return await n.json()}var u={state:()=>c(\"/api/state\"),scan:()=>c(\"/api/scan\"),clients:()=>c(\"/api/clients\"),stats:()=>c(\"/api/stats\"),console:e=>c(`/api/console?since=${e}`),events:e=>c(`/api/events?since=${e}`),save:e=>c(\"/api/config\",{method:\"POST\",headers:{\"content-type\":\"application/json\"},body:JSON.stringify(e)}),regenToken:()=>c(\"/api/regen-token\",{method:\"POST\"}),factoryReset:()=>c(\"/api/factory-reset\",{method:\"POST\"}),reboot:()=>c(\"/api/reboot\",{method:\"POST\"})},G=[[\"Europe/Berlin (Amsterdam, Paris, Rom, Madrid)\",\"CET-1CEST,M3.5.0,M10.5.0/3\"],[\"Europe/London (Dublin, Lissabon)\",\"GMT0BST,M3.5.0/1,M10.5.0\"],[\"Europe/Athen (Helsinki, Bukarest)\",\"EET-2EEST,M3.5.0/3,M10.5.0/4\"],[\"Europe/Moskau\",\"MSK-3\"],[\"UTC\",\"UTC0\"],[\"America/New York\",\"EST5EDT,M3.2.0,M11.1.0\"],[\"America/Chicago\",\"CST6CDT,M3.2.0,M11.1.0\"],[\"America/Denver\",\"MST7MDT,M3.2.0,M11.1.0\"],[\"America/Los Angeles\",\"PST8PDT,M3.2.0,M11.1.0\"],[\"America/Sao Paulo\",\"<-03>3\"],[\"Asia/Dubai\",\"<+04>-4\"],[\"Asia/Kolkata (Indien)\",\"IST-5:30\"],[\"Asia/Shanghai (China)\",\"CST-8\"],[\"Asia/Tokio\",\"JST-9\"],[\"Australia/Sydney\",\"AEST-10AEDT,M10.1.0,M4.1.0/3\"]];function X(){let e=r(\"tz\");e.innerHTML=\"\";for(let[t,n]of G){let s=document.createElement(\"option\");s.value=n,s.textContent=t,e.appendChild(s)}}function Z(e){let t=r(\"tz\");if(e&&!Array.from(t.options).some(n=>n.value===e)){let n=document.createElement(\"option\");n.value=e,n.textContent=`Eigene (${e})`,t.appendChild(n)}t.value=e||\"CET-1CEST,M3.5.0,M10.5.0/3\"}function d(e){let t=[\"B\",\"KB\",\"MB\",\"GB\"],n=0;for(;e>=1024&&n<t.length-1;)e/=1024,n++;return`${e.toFixed(n?1:0)} ${t[n]}`}function R(e){let t=Math.floor(e/1e3);if(t<60)return`${t}s`;let n=Math.floor(t/60);return n<60?`${n}m${t%60}s`:`${Math.floor(n/60)}h${n%60}m`}function m(e){return e.replace(/[&<>\"']/g,t=>{switch(t){case\"&\":return\"&amp;\";case\"<\":return\"&lt;\";case\">\":return\"&gt;\";case'\"':return\"&quot;\";case\"'\":return\"&#39;\";default:return t}})}var E,D,y;async function V(){try{let e=await u.state();r(\"ssid\").value=e.wifi_ssid||\"\",r(\"pass\").value=e.wifi_pass||\"\",r(\"tcp_en\").checked=e.tcp_enabled,r(\"tcp_port\").value=String(e.tcp_port),r(\"tcp_auth\").checked=e.tcp_auth_required,r(\"usb_en\").checked=e.usb_enabled,E.set(e.tcp_token),D.set(e.admin_pass),r(\"api_en\").checked=e.api_enabled,y.set(e.tcp_token),r(\"dev_name\").value=e.device_name||\"\",r(\"admin_user\").value=e.admin_user||\"admin\",r(\"ntp_server\").value=e.ntp_server||\"pool.ntp.org\",Z(e.tz),r(\"fw_info\").textContent=`Version  : ${e.fw_version}  (Build ${e.fw_build})\n"
"Git      : ${e.fw_git}\n"
"Datum    : ${e.fw_date}\n"
"Partition: ${e.fw_part}`;let t=document.querySelector(\"header h1\");t&&e.device_name&&(t.textContent=e.device_name),F(e.tcp_token,e.api_enabled),!e.tcp_auth_required&&e.tcp_enabled&&z(),i(`Modus: ${e.mode} \\xB7 MAC-Suffix ${e.suffix}`)}catch(e){i(`Fehler: ${e instanceof Error?e.message:String(e)}`)}}async function w(){i(\"scanne WLAN...\");try{let e=await u.scan(),t=r(\"ssid_sel\");t.innerHTML='<option value=\"\">-- Netzwerk waehlen --</option>',e.forEach(n=>{let s=document.createElement(\"option\");s.value=n.ssid,s.textContent=`${n.ssid} (${n.rssi} dBm${n.auth?\", \"+n.auth:\"\"})`,t.appendChild(s)}),t.onchange=()=>{r(\"ssid\").value=t.value},i(`${e.length} Netze gefunden`)}catch(e){i(`Scan-Fehler: ${e instanceof Error?e.message:String(e)}`)}}async function x(){try{let e=await u.regenToken();E.set(e.token),y.set(e.token),F(e.token,r(\"api_en\").checked),i(\"neuer Token\")}catch(e){i(`Fehler: ${e instanceof Error?e.message:String(e)}`)}}function J(){r(\"tcp_en\").checked=!0,r(\"tcp_port\").value=\"5100\",r(\"tcp_auth\").checked=!1,z(),i(\"HA-Eltako Preset gesetzt \\xB7 nicht vergessen zu speichern\")}function z(){let e=N(),t=parseInt(r(\"tcp_port\").value,10)||5100,n=`eltako:\n"
"  gateway:\n"
"    - id: 1\n"
"      device_type: eul_lan\n"
"      serial_path: ${e}\n"
"      port: ${t}\n"
"      base_id: FF-AA-00-00     # anpassen: base_id des TCM515\n"
"`;r(\"ha_yaml\").textContent=n,r(\"ha_yaml_box\").style.display=\"block\"}function F(e,t){let n=N();r(\"api_doc\").textContent=(t?\"\":`# API ist derzeit deaktiviert\n"
"\n"
"`)+`GET  http://${n}/api/telegrams\n"
"     Header: Authorization: Bearer ${e}\n"
"     -> letzte empfangene Telegramme (JSON-Array)\n"
"\n"
"POST http://${n}/api/send\n"
"     Header: Authorization: Bearer ${e}\n"
"     Body:   {\"hex\":\"55....\"}   (kompletter ESP3-Frame)\n"
"\n"
"Beispiel:\n"
"curl -H \"Authorization: Bearer ${e}\" http://${n}/api/telegrams`}async function Y(){let e={tcp_enabled:r(\"tcp_en\").checked,tcp_port:parseInt(r(\"tcp_port\").value,10)||5100,tcp_auth_required:r(\"tcp_auth\").checked,usb_enabled:r(\"usb_en\").checked,api_enabled:r(\"api_en\").checked,device_name:r(\"dev_name\").value.trim(),admin_user:r(\"admin_user\").value.trim(),ntp_server:r(\"ntp_server\").value.trim(),tz:r(\"tz\").value},t=r(\"admin_pass_new\").value;if(t){if(t.length<8){i(\"Neues Portal-Passwort braucht min. 8 Zeichen\");return}e.admin_pass=t}let n=r(\"ssid\").value.trim(),s=r(\"pass\").value;if(n&&s)e.wifi_ssid=n,e.wifi_pass=s;else if((n||s)&&!confirm(\"WLAN-Zugang bleibt unveraendert (nur SSID oder Passwort eingetragen). Fortfahren?\"))return;try{await u.save(e),i(\"gespeichert \\u2014 Neustart noetig fuer WLAN/TCP/Name/Zeitzone\")}catch(a){i(`Fehler: ${a instanceof Error?a.message:String(a)}`)}}async function Q(){if(confirm(\"Geraet jetzt neu starten? Die Verbindung wird kurz getrennt.\"))try{await u.reboot(),i(\"Neustart ausgeloest ...\")}catch(e){i(`Fehler: ${e instanceof Error?e.message:String(e)}`)}}function ee(){let e=r(\"ota_file\"),t=e.files&&e.files[0];if(!t){i(\"Bitte zuerst eine .bin-Datei waehlen\");return}if(!confirm(`Firmware \"${t.name}\" (${d(t.size)}) einspielen? Das Geraet startet danach neu.`))return;let n=r(\"ota_progress\"),s=r(\"btn-ota\");s.disabled=!0;let a=new XMLHttpRequest;a.open(\"POST\",\"/api/ota\"),a.upload.onprogress=o=>{if(o.lengthComputable){let l=Math.round(o.loaded/o.total*100);n.textContent=`Upload ${l}%  (${d(o.loaded)} / ${d(o.total)})`}},a.onload=()=>{s.disabled=!1,a.status===200?(n.textContent=\"Update erfolgreich \\u2014 Geraet startet neu ...\",i(\"Firmware aktualisiert, Neustart\")):(n.textContent=`Fehler ${a.status}: ${a.responseText}`,i(\"OTA fehlgeschlagen\"))},a.onerror=()=>{s.disabled=!1,n.textContent=\"Upload-Fehler (Verbindung abgebrochen). Nochmal versuchen.\"},n.textContent=\"Upload startet ...\",a.send(t)}async function te(){if(confirm(\"Wirklich auf Werkseinstellungen zuruecksetzen? Alle Zugangsdaten werden neu erzeugt.\"))try{await u.factoryReset(),i(\"reset \\xB7 neustart\")}catch(e){i(`Fehler: ${e instanceof Error?e.message:String(e)}`)}}async function S(){if(g()===\"status\")try{let e=await u.clients(),t=r(\"cli_body\");if(!e.length){t.innerHTML='<tr><td colspan=\"5\" class=\"hint\">keine aktiven Verbindungen</td></tr>';return}t.innerHTML=e.map(n=>`<tr><td data-label=\"Peer\" style=\"font-family:ui-monospace,monospace\">${m(n.peer)}</td><td data-label=\"Uptime\" style=\"text-align:center\">${R(n.connected_ms)}</td><td data-label=\"RX\" style=\"text-align:right\">${d(n.rx_bytes)}</td><td data-label=\"TX\" style=\"text-align:right\">${d(n.tx_bytes)}</td><td data-label=\"Frames\" style=\"text-align:center\">${n.rx_frames}</td></tr>`).join(\"\")}catch{}}function ne(e){return e?e>=-60?\"sehr gut\":e>=-70?\"gut\":e>=-78?\"schwach\":\"kritisch\":\"n/a\"}async function $(){if(g()===\"status\")try{let e=await u.stats();e.epoch_ms>17e11&&(_=e.epoch_ms-e.uptime_ms);let t=e.epoch_ms>17e11?new Date(e.epoch_ms).toLocaleString(\"de-DE\"):\"nicht synchronisiert\";r(\"gwstat\").textContent=`Uhrzeit (NTP) : ${t}\n"
"IP-Adresse    : ${e.ip||\"\\u2014\"}\n"
"WLAN-Signal   : ${e.rssi?`${e.rssi} dBm (${ne(e.rssi)})`:\"n/a\"}\n"
"Uptime        : ${R(e.uptime_ms)}\n"
"Aktive Clients: ${e.clients}\n"
"Freier Heap   : ${d(e.heap_free)}\n"
"Groesster Block: ${d(e.heap_max)}`,r(\"stats\").textContent=`RX vom TCM515 : ${d(e.tcm_rx_bytes)} / ${e.tcm_rx_frames} Frames\n"
"TX an TCM515  : ${d(e.tcm_tx_bytes)} / ${e.tcm_tx_frames} Frames`}catch{}}var re=60,se=\"\\u2193\",ae=\"\\u2191\",_=null,ie={246:\"RPS\",213:\"1BS\",165:\"4BS\",210:\"VLD\",209:\"MSC\",166:\"ADT\",212:\"UTE\"},k=[\"Wippe A unten\",\"Wippe A oben\",\"Wippe B unten\",\"Wippe B oben\",\"Taste 5\",\"Taste 6\",\"Taste 7\",\"Taste 8\"];function oe(e,t){let n=(e&16)!==0;if(!(t&32))return n?\"Taste(n) gedr\\xFCckt\":\"losgelassen\";if(!n&&e===0)return\"losgelassen\";let s=`${k[e>>5&7]} ${n?\"gedr\\xFCckt\":\"losgelassen\"}`;return e&1&&(s+=` + ${k[e>>1&7]}`),s}function le(e){return e&1?\"Kontakt geschlossen\":\"Kontakt offen\"}function ce(e){if(e.length!==4)return\"\";let t=e[0],n=e[1],s=e[3];return s&8?t===1?s&1?\"Einschalten\":\"Ausschalten\":t===2?`Dimmen auf ${n}%${s&1?\"\":\" (aus)\"}`:\"\":\"Lerntelegramm\"}function ue(e,t,n){return e===246?oe(t[0]??0,n):e===213?le(t[0]??0):e===165?ce(t):\"\"}function de(e){if(_===null)return(e/1e3).toFixed(3);let t=new Date(_+e),n=s=>String(s).padStart(2,\"0\");return`${n(t.getHours())}:${n(t.getMinutes())}:${n(t.getSeconds())}.${String(t.getMilliseconds()).padStart(3,\"0\")}`}function C(e){return e.map(t=>t.toString(16).padStart(2,\"0\")).join(\" \")}function me(e){return e.map(t=>t.toString(16).padStart(2,\"0\").toUpperCase()).join(\"-\")}function pe(e){let t=e.indexOf(\" : \");if(t<0)return null;let n=[];for(let s of e.slice(t+3).trim().split(/\\s+/))if(/^[0-9a-fA-F]{2}$/.test(s))n.push(parseInt(s,16));else break;return n.length?n:null}function fe(e,t,n){if(n.length<7||n[0]!==85)return null;let s=n[1]<<8|n[2],a=n[3],o=n[4],l=n.slice(6,6+s),L=n.slice(6+s,6+s+a);if(l.length<s)return null;if(o!==1)return{ms:e,dir:t,rorg:`Typ 0x${o.toString(16).padStart(2,\"0\")}`,sender:\"\\u2014\",data:C(l),text:\"\",dbm:null};if(s<6)return null;let b=l[0],q=l.slice(s-5,s-1),O=l[s-1],M=l.slice(1,s-5),j=a>=6&&L.length>=6?-L[5]:null,K=ie[b]||`0x${b.toString(16).padStart(2,\"0\")}`;return{ms:e,dir:t,rorg:K,sender:me(q),data:C(M),text:ue(b,M,O),dbm:j}}function ge(e){let t=e.dbm===null?\"\":String(e.dbm);return`<tr><td data-label=\"Zeit\" style=\"font-family:ui-monospace,monospace\">${de(e.ms)}</td><td data-label=\"Ri.\" style=\"text-align:center\">${e.dir}</td><td data-label=\"RORG\">${m(e.rorg)}</td><td data-label=\"Absender\" style=\"font-family:ui-monospace,monospace\">${m(e.sender)}</td><td data-label=\"Daten\" style=\"font-family:ui-monospace,monospace\">${m(e.data)}</td><td data-label=\"Bedeutung\">${m(e.text)}</td><td data-label=\"dBm\" style=\"text-align:right\">${t}</td></tr>`}function be(e){let t=[];for(let s of e){let a=s.line.startsWith(\"<\")?se:s.line.startsWith(\">\")?ae:\"\";if(!a)continue;let o=pe(s.line);if(!o)continue;let l=fe(s.ms,a,o);l&&t.push(ge(l))}if(!t.length)return;let n=r(\"tel_body\");for(n.querySelector(\".hint\")&&(n.innerHTML=\"\"),n.insertAdjacentHTML(\"afterbegin\",t.reverse().join(\"\"));n.children.length>re;)n.removeChild(n.lastElementChild)}var H=0,p=!1;async function A(){let e=g();if(!(e!==\"status\"&&e!==\"konsole\"))try{let t=await u.console(H);if(H=t.last_seq,!t.lines.length||(be(t.lines),p))return;let n=r(\"con\"),s=t.lines.map(o=>`[${(o.ms/1e3).toFixed(3).padStart(9,\" \")}] ${o.line}`).join(`\n"
"`);n.textContent=n.textContent?n.textContent+`\n"
"`+s:s;let a=n.textContent.split(`\n"
"`);a.length>400&&(n.textContent=a.slice(-400).join(`\n"
"`)),r(\"autoscroll\").checked&&(n.scrollTop=n.scrollHeight)}catch{}}var P=0,he=200,ve=[\"INFO\",\"WARN\",\"FEHLER\"],_e=[\"var(--hint)\",\"#c47f00\",\"var(--danger)\"];function Te(e,t){if(t>0){let n=new Date(t),s=a=>String(a).padStart(2,\"0\");return`${s(n.getHours())}:${s(n.getMinutes())}:${s(n.getSeconds())}`}return`${(e/1e3).toFixed(1)}s`}function Ee(e){let t=e.lvl>=0&&e.lvl<=2?e.lvl:0;return`<tr><td data-label=\"Zeit\" style=\"font-family:ui-monospace,monospace;white-space:nowrap\">${Te(e.ms,e.ts)}</td><td data-label=\"Level\" style=\"color:${_e[t]};font-weight:600\">${ve[t]}</td><td data-label=\"Quelle\" style=\"font-family:ui-monospace,monospace\">${m(e.tag)}</td><td data-label=\"Meldung\">${m(e.msg)}</td></tr>`}async function I(){if(g()===\"events\")try{let e=await u.events(P);if(P=e.last_seq,!e.events.length)return;let t=r(\"evt_body\");for(t.querySelector(\".hint\")&&(t.innerHTML=\"\"),t.insertAdjacentHTML(\"afterbegin\",e.events.map(Ee).reverse().join(\"\"));t.children.length>he;)t.removeChild(t.lastElementChild)}catch{}}function T(){let e=r(\"con\"),t=document.createRange();t.selectNodeContents(e);let n=window.getSelection();n&&(n.removeAllRanges(),n.addRange(t))}async function ye(){let e=r(\"con\").textContent||\"\";if(!e){i(\"Konsole ist leer\");return}try{await navigator.clipboard.writeText(e),i(`${e.length} Zeichen kopiert`)}catch{T(),i(\"Bitte manuell kopieren (Strg+C / Cmd+C)\")}}function Le(){r(\"con\").textContent=\"\",i(\"Konsole geleert\")}function Me(){p=!p,r(\"btn-pause\").textContent=p?\"Weiter\":\"Pause\",i(p?\"Konsole angehalten\":\"Konsole laeuft\")}function we(){r(\"con\").addEventListener(\"keydown\",t=>{(t.ctrlKey||t.metaKey)&&t.key.toLowerCase()===\"a\"&&(t.preventDefault(),T())}),document.addEventListener(\"keydown\",t=>{if(!(t.ctrlKey||t.metaKey)||t.key.toLowerCase()!==\"a\"||!document.getElementById(\"tab-konsole\")?.classList.contains(\"active\"))return;let s=document.activeElement;s&&(s.tagName===\"INPUT\"||s.tagName===\"TEXTAREA\"||s.tagName===\"SELECT\")||(t.preventDefault(),T())})}function xe(){U(),W(),E=new f(r(\"token\")),D=new f(r(\"adminp\")),y=new f(r(\"api_token\")),r(\"btn-scan\").addEventListener(\"click\",w),r(\"btn-regen\").addEventListener(\"click\",x),r(\"btn-regen2\").addEventListener(\"click\",x),r(\"btn-save\").addEventListener(\"click\",Y),r(\"btn-reboot\").addEventListener(\"click\",Q),r(\"btn-ota\").addEventListener(\"click\",ee),r(\"btn-factory\").addEventListener(\"click\",te),r(\"btn-clear\").addEventListener(\"click\",Le),r(\"btn-pause\").addEventListener(\"click\",Me),r(\"btn-copy\").addEventListener(\"click\",ye),r(\"btn-preset-ha\").addEventListener(\"click\",J),we(),X(),V(),w(),setInterval(S,3e3),setInterval($,3e3),setInterval(A,1e3),setInterval(I,2e3),S(),$(),A(),I()}xe();})();\n"
"</script>\n"
"</body>\n"
"</html>\n"
"\n"
;
