#pragma once
// AUTO-GENERATED from web/. Do NOT edit by hand - run "npm run build".

static const char PORTAL_HTML[] =
"<!doctype html>\n"
"<html lang=\"de\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,viewport-fit=cover\">\n"
"<title>EUL22 Konfiguration</title>\n"
"<style>\n"
":root {\n"
"  color-scheme: light dark;\n"
"  --bg:#fff;\n"
"  --panel:#fafafa;\n"
"  --fg:#222;\n"
"  --hint:#666;\n"
"  --muted:#f0f0f0;\n"
"  --brand:#0057b7;\n"
"  --brand-fg:#fff;\n"
"  --danger:#a20000;\n"
"  --border:#ddd;\n"
"  --accent-focus:rgba(0,87,183,0.25);\n"
"}\n"
"@media (prefers-color-scheme: dark) {\n"
"  :root {\n"
"    --bg:#1b1b1e;\n"
"    --panel:#232327;\n"
"    --fg:#e6e6e6;\n"
"    --hint:#a0a0a0;\n"
"    --muted:#2b2b2f;\n"
"    --border:#3a3a3f;\n"
"    --accent-focus:rgba(255,255,255,0.15);\n"
"  }\n"
"}\n"
"* { box-sizing:border-box; }\n"
"html,body { margin:0; padding:0; background:var(--bg); color:var(--fg); }\n"
"body {\n"
"  font-family:system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",Helvetica,Arial,sans-serif;\n"
"  font-size:15px;\n"
"  line-height:1.45;\n"
"  min-height:100vh;\n"
"  display:flex;\n"
"  flex-direction:column;\n"
"}\n"
"\n"
"/* --- Header + Tabs --------------------------------------------------- */\n"
"header {\n"
"  padding:12px 16px 8px;\n"
"  border-bottom:1px solid var(--border);\n"
"  background:var(--panel);\n"
"}\n"
"header h1 { margin:0; font-size:1.2em; }\n"
"header .status { font-size:0.85em; color:var(--hint); margin-top:4px; }\n"
"nav.tabs {\n"
"  display:flex;\n"
"  overflow-x:auto;\n"
"  border-bottom:1px solid var(--border);\n"
"  background:var(--panel);\n"
"  -webkit-overflow-scrolling:touch;\n"
"  scrollbar-width:none;\n"
"}\n"
"nav.tabs::-webkit-scrollbar { display:none; }\n"
"nav.tabs button {\n"
"  flex:1;\n"
"  min-width:80px;\n"
"  background:transparent;\n"
"  color:var(--fg);\n"
"  border:0;\n"
"  border-bottom:3px solid transparent;\n"
"  padding:12px 8px;\n"
"  font-size:14px;\n"
"  font-weight:500;\n"
"  cursor:pointer;\n"
"  transition:color 0.15s, border-color 0.15s;\n"
"  white-space:nowrap;\n"
"}\n"
"nav.tabs button:hover { background:var(--muted); }\n"
"nav.tabs button.active {\n"
"  color:var(--brand);\n"
"  border-bottom-color:var(--brand);\n"
"}\n"
"\n"
"/* --- Main content ---------------------------------------------------- */\n"
"main {\n"
"  flex:1;\n"
"  padding:12px 16px 100px;   /* bottom padding fuer sticky footer */\n"
"  width:100%;                /* volle Fensterbreite */\n"
"  margin:0 auto;\n"
"}\n"
".tab { display:none; }\n"
".tab.active { display:block; }\n"
"\n"
"fieldset {\n"
"  border:1px solid var(--border);\n"
"  border-radius:6px;\n"
"  padding:12px;\n"
"  margin:0 0 14px;\n"
"  background:var(--panel);\n"
"}\n"
"legend { padding:0 6px; font-weight:600; font-size:0.95em; }\n"
"\n"
"label {\n"
"  display:block;\n"
"  margin:8px 0 3px;\n"
"  font-size:13px;\n"
"  color:var(--hint);\n"
"}\n"
"label.inline {\n"
"  display:inline-flex;\n"
"  align-items:center;\n"
"  gap:6px;\n"
"  color:var(--fg);\n"
"  font-size:14px;\n"
"  margin:6px 0;\n"
"}\n"
"label.inline input { margin:0; }\n"
"\n"
"input[type=text], input[type=password], input[type=number], select {\n"
"  width:100%;\n"
"  padding:10px 12px;\n"
"  font-size:16px;      /* verhindert iOS-zoom */\n"
"  background:var(--bg);\n"
"  color:var(--fg);\n"
"  border:1px solid var(--border);\n"
"  border-radius:6px;\n"
"  outline:none;\n"
"}\n"
"input:focus, select:focus { border-color:var(--brand); box-shadow:0 0 0 3px var(--accent-focus); }\n"
"\n"
"button {\n"
"  padding:10px 16px;\n"
"  border:0;\n"
"  border-radius:6px;\n"
"  background:var(--brand);\n"
"  color:var(--brand-fg);\n"
"  cursor:pointer;\n"
"  font-size:14px;\n"
"  font-weight:500;\n"
"  min-height:40px;\n"
"  transition:transform 0.05s, background 0.15s;\n"
"}\n"
"button:active { transform:scale(0.97); }\n"
"button.ghost { background:var(--muted); color:var(--fg); }\n"
"button.danger { background:var(--danger); color:#fff; }\n"
"button:disabled { opacity:0.5; cursor:not-allowed; }\n"
"\n"
".row { display:flex; gap:8px; align-items:center; flex-wrap:wrap; }\n"
".row > * { min-width:0; }\n"
".row > input, .row > select { flex:1; }\n"
"\n"
".hint { font-size:0.85em; color:var(--hint); margin-top:4px; }\n"
".mono {\n"
"  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;\n"
"  background:var(--muted);\n"
"  padding:8px 10px;\n"
"  border-radius:4px;\n"
"  word-break:break-all;\n"
"  font-size:13px;\n"
"}\n"
"\n"
"/* --- Password + Secret --- */\n"
".pw-wrap { position:relative; display:block; }\n"
".pw-wrap input { padding-right:48px; }\n"
".pw-eye {\n"
"  position:absolute;\n"
"  right:4px;\n"
"  top:50%;\n"
"  transform:translateY(-50%);\n"
"  background:transparent;\n"
"  color:var(--hint);\n"
"  padding:8px;\n"
"  border:0;\n"
"  cursor:pointer;\n"
"  min-height:32px;\n"
"  min-width:36px;\n"
"  border-radius:4px;\n"
"  line-height:0;\n"
"}\n"
".pw-eye:hover { color:var(--fg); background:var(--muted); }\n"
".pw-eye svg { display:block; }\n"
"\n"
".secret {\n"
"  display:flex;\n"
"  align-items:center;\n"
"  gap:6px;\n"
"  background:var(--muted);\n"
"  padding:6px 8px;\n"
"  border-radius:6px;\n"
"  min-height:38px;\n"
"}\n"
".secret .val {\n"
"  flex:1;\n"
"  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;\n"
"  font-size:13px;\n"
"  word-break:break-all;\n"
"  user-select:all;\n"
"  -webkit-user-select:all;\n"
"}\n"
".secret .pw-eye { position:static; transform:none; }\n"
"\n"
"/* --- Table (Verbindungen) ------------------------------------------- */\n"
"table { width:100%; border-collapse:collapse; font-size:13px; }\n"
"th { text-align:left; font-weight:600; color:var(--hint); border-bottom:1px solid var(--border); padding:8px 6px; font-size:12px; text-transform:uppercase; letter-spacing:0.03em; }\n"
"td { padding:8px 6px; border-bottom:1px solid var(--muted); }\n"
"tr:last-child td { border-bottom:0; }\n"
"\n"
"@media (max-width:520px) {\n"
"  /* Table -> Card layout auf schmalen screens */\n"
"  table.responsive thead { display:none; }\n"
"  table.responsive tr {\n"
"    display:block;\n"
"    padding:8px 0;\n"
"    border-bottom:1px solid var(--border);\n"
"  }\n"
"  table.responsive tr:last-child { border-bottom:0; }\n"
"  table.responsive td {\n"
"    display:flex;\n"
"    justify-content:space-between;\n"
"    align-items:baseline;\n"
"    padding:3px 0;\n"
"    border:0;\n"
"    text-align:right !important;\n"
"  }\n"
"  table.responsive td::before {\n"
"    content:attr(data-label);\n"
"    color:var(--hint);\n"
"    font-size:0.85em;\n"
"    font-weight:500;\n"
"    margin-right:12px;\n"
"    text-transform:uppercase;\n"
"    letter-spacing:0.03em;\n"
"    text-align:left;\n"
"  }\n"
"}\n"
"\n"
"/* --- Konsole -------------------------------------------------------- */\n"
"pre.console {\n"
"  background:#0f0f10;\n"
"  color:#dcdcdc;\n"
"  padding:10px 12px;\n"
"  border-radius:6px;\n"
"  font-size:12px;\n"
"  line-height:1.4;\n"
"  height:60vh;\n"
"  min-height:280px;\n"
"  max-height:520px;\n"
"  overflow:auto;\n"
"  overflow-x:auto;\n"
"  white-space:pre-wrap;\n"
"  word-break:break-all;\n"
"  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;\n"
"  user-select:text;\n"
"  -webkit-user-select:text;\n"
"  tab-size:2;\n"
"  margin:8px 0 0;\n"
"}\n"
"pre.console:focus {\n"
"  outline:2px solid var(--brand);\n"
"  outline-offset:2px;\n"
"}\n"
"\n"
"/* --- Sticky footer -------------------------------------------------- */\n"
"footer.actions {\n"
"  position:sticky;\n"
"  bottom:0;\n"
"  left:0;\n"
"  right:0;\n"
"  padding:10px 16px calc(10px + env(safe-area-inset-bottom));\n"
"  border-top:1px solid var(--border);\n"
"  background:color-mix(in srgb, var(--panel) 92%, transparent);\n"
"  backdrop-filter:blur(8px);\n"
"  -webkit-backdrop-filter:blur(8px);\n"
"  display:flex;\n"
"  gap:8px;\n"
"  justify-content:center;\n"
"  width:100%;\n"
"  margin:0 auto;\n"
"}\n"
"footer.actions button {\n"
"  flex:1;\n"
"  min-height:44px;\n"
"}\n"
"footer.actions .save { flex:2; }\n"
"\n"
"/* Sehr schmal: Buttons untereinander */\n"
"@media (max-width:380px) {\n"
"  footer.actions { flex-direction:column; }\n"
"  footer.actions button { min-height:40px; }\n"
"}\n"
"\n"
"/* --- Sonstiges ----------------------------------------------------- */\n"
"hr { border:0; border-top:1px solid var(--border); margin:12px 0; }\n"
"code { background:var(--muted); padding:1px 4px; border-radius:3px; font-size:0.9em; }\n"
"a { color:var(--brand); }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"\n"
"<header>\n"
"  <h1>Busware EUL22</h1>\n"
"  <div class=\"status\" id=\"status\">lade...</div>\n"
"</header>\n"
"\n"
"<nav class=\"tabs\" id=\"tabs\">\n"
"  <button data-tab=\"status\" class=\"active\">Status</button>\n"
"  <button data-tab=\"allgemein\">Allgemein</button>\n"
"  <button data-tab=\"wifi\">WiFi</button>\n"
"  <button data-tab=\"usb\">USB</button>\n"
"  <button data-tab=\"enocean\">EnOcean</button>\n"
"  <button data-tab=\"api\">API</button>\n"
"  <button data-tab=\"mqtt\">MQTT</button>\n"
"  <button data-tab=\"events\">Events</button>\n"
"  <button data-tab=\"konsole\">Konsole</button>\n"
"</nav>\n"
"\n"
"<main>\n"
"\n"
"  <!-- ============================================================ Status -->\n"
"  <section class=\"tab active\" id=\"tab-status\">\n"
"    <fieldset><legend>Gateway</legend>\n"
"      <div id=\"gwstat\" class=\"mono\" style=\"white-space:pre\">lade...</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Aktive Verbindungen</legend>\n"
"      <table class=\"responsive\">\n"
"        <thead>\n"
"          <tr><th>Peer</th><th>Uptime</th><th>RX</th><th>TX</th><th>Frames</th></tr>\n"
"        </thead>\n"
"        <tbody id=\"cli_body\">\n"
"          <tr><td colspan=\"5\" class=\"hint\">keine aktiven Verbindungen</td></tr>\n"
"        </tbody>\n"
"      </table>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Telegramme</legend>\n"
"      <div style=\"max-height:42vh;overflow:auto\">\n"
"        <table class=\"responsive\">\n"
"          <thead>\n"
"            <tr><th>Zeit</th><th>Ri.</th><th>RORG</th><th>Absender</th><th>Daten</th><th>Bedeutung</th><th>dBm</th></tr>\n"
"          </thead>\n"
"          <tbody id=\"tel_body\">\n"
"            <tr><td colspan=\"7\" class=\"hint\">warte auf Telegramme...</td></tr>\n"
"          </tbody>\n"
"        </table>\n"
"      </div>\n"
"      <div class=\"hint\">Dekodierte EnOcean-Funktelegramme (live, neueste oben). <code>&#8595;</code> empfangen vom TCM515 · <code>&#8593;</code> an den TCM515 gesendet.</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>TCM515-Statistik</legend>\n"
"      <div id=\"stats\" class=\"mono\" style=\"white-space:pre\">-</div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- ========================================================= Allgemein -->\n"
"  <section class=\"tab\" id=\"tab-allgemein\">\n"
"    <fieldset><legend>Geraet</legend>\n"
"      <label>Geraetename</label>\n"
"      <input type=\"text\" id=\"dev_name\" maxlength=\"39\" autocomplete=\"off\" placeholder=\"z.B. EnOcean Gateway Flur\">\n"
"      <div class=\"hint\">Anzeigename im Portal-Titel und in Home Assistant.</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Portal-Login</legend>\n"
"      <label>Benutzer</label>\n"
"      <input type=\"text\" id=\"admin_user\" maxlength=\"23\" autocomplete=\"off\" placeholder=\"admin\">\n"
"      <label>Aktuelles Passwort <span class=\"hint\">(nur beim Erst-Setup sichtbar)</span></label>\n"
"      <div id=\"adminp\" class=\"secret\"></div>\n"
"      <label>Neues Passwort <span class=\"hint\">(leer = unveraendert, min. 8 Zeichen)</span></label>\n"
"      <input type=\"password\" id=\"admin_pass_new\" maxlength=\"63\" placeholder=\"unveraendert\" autocomplete=\"off\" data-eye>\n"
"      <div class=\"hint\">Login fuer dieses Portal im Normalbetrieb (STA-Modus).</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Zeit (NTP)</legend>\n"
"      <label>NTP-Server</label>\n"
"      <input type=\"text\" id=\"ntp_server\" maxlength=\"63\" autocomplete=\"off\" placeholder=\"pool.ntp.org\">\n"
"      <div class=\"hint\">Zeitzone fest Europe/Berlin (inkl. Sommerzeit).</div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- ============================================================== WiFi -->\n"
"  <section class=\"tab\" id=\"tab-wifi\">\n"
"    <fieldset><legend>WLAN (Heimnetz)</legend>\n"
"      <label>SSID</label>\n"
"      <div class=\"row\">\n"
"        <select id=\"ssid_sel\"><option value=\"\">-- Netzwerk waehlen --</option></select>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-scan\">Suchen</button>\n"
"      </div>\n"
"      <label>oder SSID manuell</label>\n"
"      <input type=\"text\" id=\"ssid\" maxlength=\"32\" autocomplete=\"off\">\n"
"      <label>Passwort <span class=\"hint\">(Auge-Button zum Anzeigen)</span></label>\n"
"      <input type=\"password\" id=\"pass\" maxlength=\"63\" placeholder=\"(nicht gesetzt)\" autocomplete=\"off\" data-eye>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- =============================================================== USB -->\n"
"  <section class=\"tab\" id=\"tab-usb\">\n"
"    <fieldset><legend>USB-CDC-Bridge</legend>\n"
"      <label class=\"inline\"><input type=\"checkbox\" id=\"usb_en\"> USB als transparente ESP3-Bridge aktivieren</label>\n"
"      <div class=\"hint\">Erlaubt Direkt-Zugriff auf den TCM515 ueber die USB-C-Buchse als virtuellen COM-Port. Aus Sicherheitsgruenden (CRA) standardmaessig aus.</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Hinweis</legend>\n"
"      <div class=\"hint\">\n"
"        USB-Traffic wird nicht in die Web-Konsole gespiegelt. Zur Diagnose am USB-Kanal\n"
"        lokal <code>pio device monitor</code> oder <code>screen /dev/cu.usbmodemXXXX 460800</code> verwenden.\n"
"      </div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- =========================================================== EnOcean -->\n"
"  <section class=\"tab\" id=\"tab-enocean\">\n"
"    <fieldset><legend>TCP-Bridge (Home Assistant / FHEM / ...)</legend>\n"
"      <label class=\"inline\"><input type=\"checkbox\" id=\"tcp_en\"> TCP-Server aktivieren</label>\n"
"      <label>Port</label>\n"
"      <input type=\"number\" id=\"tcp_port\" value=\"5100\" min=\"1\" max=\"65535\">\n"
"      <label class=\"inline\"><input type=\"checkbox\" id=\"tcp_auth\"> AUTH-Token verlangen <span class=\"hint\">(empfohlen)</span></label>\n"
"      <label>Aktueller Token</label>\n"
"      <div class=\"row\">\n"
"        <div id=\"token\" class=\"secret\"></div>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-regen\">Neu erzeugen</button>\n"
"      </div>\n"
"      <div class=\"hint\">Handshake: Server sendet <code>HELLO EUL22 v1 AUTH-REQUIRED</code>, Client antwortet mit <code>AUTH &lt;token&gt;</code>.</div>\n"
"      <hr>\n"
"      <button type=\"button\" class=\"ghost\" id=\"btn-preset-ha\">Preset: HA-Eltako Integration</button>\n"
"      <div class=\"hint\">Setzt Port 5100 + Auth aus (MGW-LAN-Konvention der <a href=\"https://github.com/FMDHET/home-assistant-eltako\" target=\"_blank\" rel=\"noopener\">Eltako HA-Integration</a>).</div>\n"
"      <div id=\"ha_yaml_box\" style=\"display:none;margin-top:10px\">\n"
"        <label>HA-Config (nach Speichern &amp; Neustart einsetzbar)</label>\n"
"        <pre id=\"ha_yaml\" class=\"mono\" style=\"white-space:pre;overflow:auto;font-size:12px;padding:10px\"></pre>\n"
"      </div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- =============================================================== API -->\n"
"  <section class=\"tab\" id=\"tab-api\">\n"
"    <fieldset><legend>REST-API</legend>\n"
"      <label class=\"inline\"><input type=\"checkbox\" id=\"api_en\"> REST-API aktivieren</label>\n"
"      <div class=\"hint\">HTTP-Zugriff auf empfangene Telegramme und zum Senden. Authentifizierung ueber den Geraete-Token, per Header <code>Authorization: Bearer &lt;token&gt;</code> oder Query <code>?token=&lt;token&gt;</code>.</div>\n"
"      <label>Geraete-Token</label>\n"
"      <div class=\"row\">\n"
"        <div id=\"api_token\" class=\"secret\"></div>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-regen2\">Neu erzeugen</button>\n"
"      </div>\n"
"      <div class=\"hint\">Derselbe Token wie fuer die TCP-Bridge (Reiter EnOcean).</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Endpunkte</legend>\n"
"      <pre id=\"api_doc\" class=\"mono\" style=\"white-space:pre-wrap;overflow:auto;font-size:12px;padding:10px\">API deaktiviert oder Adresse unbekannt.</pre>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- ============================================================== MQTT -->\n"
"  <section class=\"tab\" id=\"tab-mqtt\">\n"
"    <fieldset><legend>MQTT-Broker</legend>\n"
"      <label class=\"inline\"><input type=\"checkbox\" id=\"mqtt_en\"> MQTT-Client aktivieren</label>\n"
"      <label>Broker-Host</label>\n"
"      <input type=\"text\" id=\"mqtt_host\" maxlength=\"63\" autocomplete=\"off\" placeholder=\"z.B. 192.168.177.1 oder homeassistant.local\">\n"
"      <label>Port</label>\n"
"      <input type=\"number\" id=\"mqtt_port\" value=\"1883\" min=\"1\" max=\"65535\">\n"
"      <label>Benutzer <span class=\"hint\">(optional)</span></label>\n"
"      <input type=\"text\" id=\"mqtt_user\" maxlength=\"47\" autocomplete=\"off\">\n"
"      <label>Passwort <span class=\"hint\">(Auge-Button zum Anzeigen)</span></label>\n"
"      <input type=\"password\" id=\"mqtt_pass\" maxlength=\"63\" placeholder=\"(nicht gesetzt)\" autocomplete=\"off\" data-eye>\n"
"      <label>Basis-Topic</label>\n"
"      <input type=\"text\" id=\"mqtt_topic\" maxlength=\"47\" placeholder=\"eul22/xxxxxx (leer = automatisch)\">\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Home Assistant</legend>\n"
"      <label class=\"inline\"><input type=\"checkbox\" id=\"mqtt_disc\"> HA-Autodiscovery aktivieren</label>\n"
"      <label class=\"inline\"><input type=\"checkbox\" id=\"mqtt_ret\"> State-Messages mit Retain senden</label>\n"
"      <label>Discovery-Prefix</label>\n"
"      <input type=\"text\" id=\"mqtt_prefix\" maxlength=\"31\" placeholder=\"homeassistant\">\n"
"      <div class=\"hint\">Legt in HA ein Gateway-Diagnose-Geraet (RSSI/Uptime/Clients) UND je Sender-ID automatisch ein Entity an. Verfuegbarkeit (LWT) auf <code>&lt;topic&gt;/status</code>.</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Topics</legend>\n"
"      <div id=\"mqtt_doc\" class=\"hint\" style=\"white-space:pre-wrap\"></div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- ============================================================ Events -->\n"
"  <section class=\"tab\" id=\"tab-events\">\n"
"    <fieldset><legend>Ereignisse</legend>\n"
"      <div style=\"max-height:60vh;overflow:auto\">\n"
"        <table class=\"responsive\">\n"
"          <thead>\n"
"            <tr><th>Zeit</th><th>Level</th><th>Quelle</th><th>Meldung</th></tr>\n"
"          </thead>\n"
"          <tbody id=\"evt_body\">\n"
"            <tr><td colspan=\"4\" class=\"hint\">warte auf Ereignisse...</td></tr>\n"
"          </tbody>\n"
"        </table>\n"
"      </div>\n"
"      <div class=\"hint\">Boot, WLAN (Verbindung/Trennung mit Grund), TCP-Clients, MQTT, Security, periodischer Netz-Status. Neueste oben.</div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- =========================================================== Konsole -->\n"
"  <section class=\"tab\" id=\"tab-konsole\">\n"
"    <fieldset><legend>Live-Datenverkehr</legend>\n"
"      <div class=\"row\" style=\"margin-bottom:6px\">\n"
"        <label class=\"inline\" style=\"flex:1\"><input type=\"checkbox\" id=\"autoscroll\" checked> Auto-Scroll</label>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-copy\">Kopieren</button>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-clear\">Leeren</button>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-pause\">Pause</button>\n"
"      </div>\n"
"      <pre id=\"con\" class=\"console\" tabindex=\"0\" aria-label=\"Konsole. Klicken oder fokussieren, dann Strg+A um Inhalt zu markieren.\"></pre>\n"
"      <div class=\"hint\">\n"
"        <code>&lt; TCM</code> = vom Modul empfangen, <code>&gt; ip:port</code> = von diesem Client gesendet.\n"
"        Fokus auf die Konsole (Klick) und <code>Strg+A</code> / <code>Cmd+A</code> markiert nur die Konsole.\n"
"      </div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"</main>\n"
"\n"
"<footer class=\"actions\">\n"
"  <button type=\"button\" class=\"save\" id=\"btn-save\">Speichern &amp; Neustart</button>\n"
"  <button type=\"button\" class=\"danger\" id=\"btn-factory\">Werkseinstellungen</button>\n"
"</footer>\n"
"\n"
"<script>\"use strict\";(()=>{var A='<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M1 12s4-8 11-8 11 8 11 8-4 8-11 8S1 12 1 12z\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/></svg>',h='<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M17.94 17.94A10.94 10.94 0 0 1 12 20c-7 0-11-8-11-8a19.4 19.4 0 0 1 5.06-5.94\"/><path d=\"M9.9 4.24A11 11 0 0 1 12 4c7 0 11 8 11 8a19.3 19.3 0 0 1-2.16 3.19\"/><path d=\"M14.12 14.12a3 3 0 1 1-4.24-4.24\"/><line x1=\"1\" y1=\"1\" x2=\"23\" y2=\"23\"/></svg>';function s(e){let t=document.getElementById(e);if(!t)throw new Error(`#${e} not found`);return t}function a(e){s(\"status\").textContent=e}function B(){return window.location.hostname}function b(e){document.querySelectorAll(\"nav.tabs button\").forEach(t=>{t.classList.toggle(\"active\",t.dataset.tab===e)}),document.querySelectorAll(\".tab\").forEach(t=>{t.classList.toggle(\"active\",t.id===`tab-${e}`)}),location.hash!==`#${e}`&&history.replaceState(null,\"\",`#${e}`)}function f(){return document.querySelector(\"nav.tabs button.active\")?.dataset.tab??\"\"}function W(){document.querySelectorAll(\"nav.tabs button\").forEach(t=>{t.addEventListener(\"click\",()=>b(t.dataset.tab))});let e=location.hash.replace(\"#\",\"\");e&&document.getElementById(`tab-${e}`)&&b(e),window.addEventListener(\"hashchange\",()=>{let t=location.hash.replace(\"#\",\"\");t&&document.getElementById(`tab-${t}`)&&b(t)})}function X(){document.querySelectorAll(\"input[data-eye]\").forEach(e=>{let t=document.createElement(\"div\");t.className=\"pw-wrap\",e.parentNode.insertBefore(t,e),t.appendChild(e);let n=document.createElement(\"button\");n.type=\"button\",n.className=\"pw-eye\",n.setAttribute(\"aria-label\",\"Passwort anzeigen\"),n.innerHTML=h,t.appendChild(n),n.addEventListener(\"click\",()=>{let r=e.type===\"password\";e.type=r?\"text\":\"password\",n.innerHTML=r?A:h,n.setAttribute(\"aria-label\",r?\"Passwort verbergen\":\"Passwort anzeigen\")})})}var p=class{constructor(t){this.host=t;this.value=\"\";this.revealed=!1;this.host.innerHTML='<span class=\"val\"></span><button type=\"button\" class=\"pw-eye\" aria-label=\"anzeigen\"></button>',this.valueEl=this.host.querySelector(\".val\"),this.btn=this.host.querySelector(\".pw-eye\"),this.btn.addEventListener(\"click\",()=>{this.revealed=!this.revealed,this.render()}),this.render()}set(t){this.value=t,this.render()}render(){this.value?this.revealed?this.valueEl.textContent=this.value:this.valueEl.textContent=\"\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\":this.valueEl.textContent=\"\\u2014\",this.btn.innerHTML=this.revealed?A:h,this.btn.setAttribute(\"aria-label\",this.revealed?\"verbergen\":\"anzeigen\")}};async function c(e,t){let n=await fetch(e,t);if(!n.ok)throw new Error(`${n.status}: ${await n.text()}`);return await n.json()}var u={state:()=>c(\"/api/state\"),scan:()=>c(\"/api/scan\"),clients:()=>c(\"/api/clients\"),stats:()=>c(\"/api/stats\"),console:e=>c(`/api/console?since=${e}`),events:e=>c(`/api/events?since=${e}`),save:e=>c(\"/api/config\",{method:\"POST\",headers:{\"content-type\":\"application/json\"},body:JSON.stringify(e)}),regenToken:()=>c(\"/api/regen-token\",{method:\"POST\"}),factoryReset:()=>c(\"/api/factory-reset\",{method:\"POST\"})};function g(e){let t=[\"B\",\"KB\",\"MB\",\"GB\"],n=0;for(;e>=1024&&n<t.length-1;)e/=1024,n++;return`${e.toFixed(n?1:0)} ${t[n]}`}function R(e){let t=Math.floor(e/1e3);if(t<60)return`${t}s`;let n=Math.floor(t/60);return n<60?`${n}m${t%60}s`:`${Math.floor(n/60)}h${n%60}m`}function m(e){return e.replace(/[&<>\"']/g,t=>{switch(t){case\"&\":return\"&amp;\";case\"<\":return\"&lt;\";case\">\":return\"&gt;\";case'\"':return\"&quot;\";case\"'\":return\"&#39;\";default:return t}})}var y,N,T;async function U(){try{let e=await u.state();s(\"ssid\").value=e.wifi_ssid||\"\",s(\"pass\").value=e.wifi_pass||\"\",s(\"tcp_en\").checked=e.tcp_enabled,s(\"tcp_port\").value=String(e.tcp_port),s(\"tcp_auth\").checked=e.tcp_auth_required,s(\"usb_en\").checked=e.usb_enabled,y.set(e.tcp_token),N.set(e.admin_pass),s(\"api_en\").checked=e.api_enabled,s(\"mqtt_en\").checked=e.mqtt_enabled,s(\"mqtt_host\").value=e.mqtt_host||\"\",s(\"mqtt_port\").value=String(e.mqtt_port||1883),s(\"mqtt_user\").value=e.mqtt_user||\"\",s(\"mqtt_pass\").value=e.mqtt_pass||\"\",s(\"mqtt_topic\").value=e.mqtt_topic||\"\",T.set(e.tcp_token),s(\"dev_name\").value=e.device_name||\"\",s(\"admin_user\").value=e.admin_user||\"admin\",s(\"ntp_server\").value=e.ntp_server||\"pool.ntp.org\",s(\"mqtt_disc\").checked=e.mqtt_discovery,s(\"mqtt_ret\").checked=e.mqtt_retain,s(\"mqtt_prefix\").value=e.mqtt_disc_prefix||\"homeassistant\";let t=document.querySelector(\"header h1\");t&&e.device_name&&(t.textContent=e.device_name),D(e.tcp_token,e.api_enabled),Z(e.mqtt_topic,e.suffix),!e.tcp_auth_required&&e.tcp_enabled&&F(),a(`Modus: ${e.mode} \\xB7 MAC-Suffix ${e.suffix}`)}catch(e){a(`Fehler: ${e instanceof Error?e.message:String(e)}`)}}async function M(){a(\"scanne WLAN...\");try{let e=await u.scan(),t=s(\"ssid_sel\");t.innerHTML='<option value=\"\">-- Netzwerk waehlen --</option>',e.forEach(n=>{let r=document.createElement(\"option\");r.value=n.ssid,r.textContent=`${n.ssid} (${n.rssi} dBm${n.auth?\", \"+n.auth:\"\"})`,t.appendChild(r)}),t.onchange=()=>{s(\"ssid\").value=t.value},a(`${e.length} Netze gefunden`)}catch(e){a(`Scan-Fehler: ${e instanceof Error?e.message:String(e)}`)}}async function k(){try{let e=await u.regenToken();y.set(e.token),T.set(e.token),D(e.token,s(\"api_en\").checked),a(\"neuer Token\")}catch(e){a(`Fehler: ${e instanceof Error?e.message:String(e)}`)}}function G(){s(\"tcp_en\").checked=!0,s(\"tcp_port\").value=\"5100\",s(\"tcp_auth\").checked=!1,F(),a(\"HA-Eltako Preset gesetzt \\xB7 nicht vergessen zu speichern\")}function F(){let e=B(),t=parseInt(s(\"tcp_port\").value,10)||5100,n=`eltako:\n"
"  gateway:\n"
"    - id: 1\n"
"      device_type: eul_lan\n"
"      serial_path: ${e}\n"
"      port: ${t}\n"
"      base_id: FF-AA-00-00     # anpassen: base_id des TCM515\n"
"`;s(\"ha_yaml\").textContent=n,s(\"ha_yaml_box\").style.display=\"block\"}function D(e,t){let n=B();s(\"api_doc\").textContent=(t?\"\":`# API ist derzeit deaktiviert\n"
"\n"
"`)+`GET  http://${n}/api/telegrams\n"
"     Header: Authorization: Bearer ${e}\n"
"     -> letzte empfangene Telegramme (JSON-Array)\n"
"\n"
"POST http://${n}/api/send\n"
"     Header: Authorization: Bearer ${e}\n"
"     Body:   {\"hex\":\"55....\"}   (kompletter ESP3-Frame)\n"
"\n"
"Beispiel:\n"
"curl -H \"Authorization: Bearer ${e}\" http://${n}/api/telegrams`}function Z(e,t){let n=e||`eul22/${t}`;s(\"mqtt_doc\").textContent=`Empfangene Telegramme werden publiziert auf:\n"
"  ${n}/rx\n"
"\n"
"Sende-Kommandos abonniert das Geraet auf:\n"
"  ${n}/send\n"
"  Payload = ESP3-Frame als Hex, z.B. \"55 00 07 07 01 ...\"`}async function V(){let e={tcp_enabled:s(\"tcp_en\").checked,tcp_port:parseInt(s(\"tcp_port\").value,10)||5100,tcp_auth_required:s(\"tcp_auth\").checked,usb_enabled:s(\"usb_en\").checked,api_enabled:s(\"api_en\").checked,mqtt_enabled:s(\"mqtt_en\").checked,mqtt_host:s(\"mqtt_host\").value.trim(),mqtt_port:parseInt(s(\"mqtt_port\").value,10)||1883,mqtt_user:s(\"mqtt_user\").value.trim(),mqtt_topic:s(\"mqtt_topic\").value.trim(),mqtt_discovery:s(\"mqtt_disc\").checked,mqtt_retain:s(\"mqtt_ret\").checked,mqtt_disc_prefix:s(\"mqtt_prefix\").value.trim(),device_name:s(\"dev_name\").value.trim(),admin_user:s(\"admin_user\").value.trim(),ntp_server:s(\"ntp_server\").value.trim()},t=s(\"mqtt_pass\").value;t&&(e.mqtt_pass=t);let n=s(\"admin_pass_new\").value;if(n){if(n.length<8){a(\"Neues Portal-Passwort braucht min. 8 Zeichen\");return}e.admin_pass=n}let r=s(\"ssid\").value.trim(),i=s(\"pass\").value;if(r&&i)e.wifi_ssid=r,e.wifi_pass=i;else if((r||i)&&!confirm(\"WLAN-Zugang bleibt unveraendert (nur SSID oder Passwort eingetragen). Fortfahren?\"))return;try{await u.save(e),a(\"gespeichert \\xB7 Geraet startet neu...\")}catch(o){a(`Fehler: ${o instanceof Error?o.message:String(o)}`)}}async function J(){if(confirm(\"Wirklich auf Werkseinstellungen zuruecksetzen? Alle Zugangsdaten werden neu erzeugt.\"))try{await u.factoryReset(),a(\"reset \\xB7 neustart\")}catch(e){a(`Fehler: ${e instanceof Error?e.message:String(e)}`)}}async function H(){if(f()===\"status\")try{let e=await u.clients(),t=s(\"cli_body\");if(!e.length){t.innerHTML='<tr><td colspan=\"5\" class=\"hint\">keine aktiven Verbindungen</td></tr>';return}t.innerHTML=e.map(n=>`<tr><td data-label=\"Peer\" style=\"font-family:ui-monospace,monospace\">${m(n.peer)}</td><td data-label=\"Uptime\" style=\"text-align:center\">${R(n.connected_ms)}</td><td data-label=\"RX\" style=\"text-align:right\">${g(n.rx_bytes)}</td><td data-label=\"TX\" style=\"text-align:right\">${g(n.tx_bytes)}</td><td data-label=\"Frames\" style=\"text-align:center\">${n.rx_frames}</td></tr>`).join(\"\")}catch{}}function Y(e){return e?e>=-60?\"sehr gut\":e>=-70?\"gut\":e>=-78?\"schwach\":\"kritisch\":\"n/a\"}async function $(){if(f()===\"status\")try{let e=await u.stats();e.epoch_ms>17e11&&(v=e.epoch_ms-e.uptime_ms);let t=e.epoch_ms>17e11?new Date(e.epoch_ms).toLocaleString(\"de-DE\"):\"nicht synchronisiert\";s(\"gwstat\").textContent=`Uhrzeit (NTP) : ${t}\n"
"IP-Adresse    : ${e.ip||\"\\u2014\"}\n"
"WLAN-Signal   : ${e.rssi?`${e.rssi} dBm (${Y(e.rssi)})`:\"n/a\"}\n"
"Uptime        : ${R(e.uptime_ms)}\n"
"Aktive Clients: ${e.clients}`,s(\"stats\").textContent=`RX vom TCM515 : ${g(e.tcm_rx_bytes)} / ${e.tcm_rx_frames} Frames\n"
"TX an TCM515  : ${g(e.tcm_tx_bytes)} / ${e.tcm_tx_frames} Frames`}catch{}}var Q=60,ee=\"\\u2193\",te=\"\\u2191\",v=null,ne={246:\"RPS\",213:\"1BS\",165:\"4BS\",210:\"VLD\",209:\"MSC\",166:\"ADT\",212:\"UTE\"},w=[\"Wippe A unten\",\"Wippe A oben\",\"Wippe B unten\",\"Wippe B oben\",\"Taste 5\",\"Taste 6\",\"Taste 7\",\"Taste 8\"];function se(e,t){let n=(e&16)!==0;if(!(t&32))return n?\"Taste(n) gedr\\xFCckt\":\"losgelassen\";if(!n&&e===0)return\"losgelassen\";let r=`${w[e>>5&7]} ${n?\"gedr\\xFCckt\":\"losgelassen\"}`;return e&1&&(r+=` + ${w[e>>1&7]}`),r}function re(e){return e&1?\"Kontakt geschlossen\":\"Kontakt offen\"}function ae(e){if(e.length!==4)return\"\";let t=e[0],n=e[1],r=e[3];return r&8?t===1?r&1?\"Einschalten\":\"Ausschalten\":t===2?`Dimmen auf ${n}%${r&1?\"\":\" (aus)\"}`:\"\":\"Lerntelegramm\"}function ie(e,t,n){return e===246?se(t[0]??0,n):e===213?re(t[0]??0):e===165?ae(t):\"\"}function oe(e){if(v===null)return(e/1e3).toFixed(3);let t=new Date(v+e),n=r=>String(r).padStart(2,\"0\");return`${n(t.getHours())}:${n(t.getMinutes())}:${n(t.getSeconds())}.${String(t.getMilliseconds()).padStart(3,\"0\")}`}function q(e){return e.map(t=>t.toString(16).padStart(2,\"0\")).join(\" \")}function le(e){return e.map(t=>t.toString(16).padStart(2,\"0\").toUpperCase()).join(\"-\")}function ce(e){let t=e.indexOf(\" : \");if(t<0)return null;let n=[];for(let r of e.slice(t+3).trim().split(/\\s+/))if(/^[0-9a-fA-F]{2}$/.test(r))n.push(parseInt(r,16));else break;return n.length?n:null}function ue(e,t,n){if(n.length<7||n[0]!==85)return null;let r=n[1]<<8|n[2],i=n[3],o=n[4],l=n.slice(6,6+r),L=n.slice(6+r,6+r+i);if(l.length<r)return null;if(o!==1)return{ms:e,dir:t,rorg:`Typ 0x${o.toString(16).padStart(2,\"0\")}`,sender:\"\\u2014\",data:q(l),text:\"\",dbm:null};if(r<6)return null;let _=l[0],z=l.slice(r-5,r-1),j=l[r-1],x=l.slice(1,r-5),K=i>=6&&L.length>=6?-L[5]:null,O=ne[_]||`0x${_.toString(16).padStart(2,\"0\")}`;return{ms:e,dir:t,rorg:O,sender:le(z),data:q(x),text:ie(_,x,j),dbm:K}}function me(e){let t=e.dbm===null?\"\":String(e.dbm);return`<tr><td data-label=\"Zeit\" style=\"font-family:ui-monospace,monospace\">${oe(e.ms)}</td><td data-label=\"Ri.\" style=\"text-align:center\">${e.dir}</td><td data-label=\"RORG\">${m(e.rorg)}</td><td data-label=\"Absender\" style=\"font-family:ui-monospace,monospace\">${m(e.sender)}</td><td data-label=\"Daten\" style=\"font-family:ui-monospace,monospace\">${m(e.data)}</td><td data-label=\"Bedeutung\">${m(e.text)}</td><td data-label=\"dBm\" style=\"text-align:right\">${t}</td></tr>`}function de(e){let t=[];for(let r of e){let i=r.line.startsWith(\"<\")?ee:r.line.startsWith(\">\")?te:\"\";if(!i)continue;let o=ce(r.line);if(!o)continue;let l=ue(r.ms,i,o);l&&t.push(me(l))}if(!t.length)return;let n=s(\"tel_body\");for(n.querySelector(\".hint\")&&(n.innerHTML=\"\"),n.insertAdjacentHTML(\"afterbegin\",t.reverse().join(\"\"));n.children.length>Q;)n.removeChild(n.lastElementChild)}var S=0,d=!1;async function I(){let e=f();if(!(e!==\"status\"&&e!==\"konsole\"))try{let t=await u.console(S);if(S=t.last_seq,!t.lines.length||(de(t.lines),d))return;let n=s(\"con\"),r=t.lines.map(o=>`[${(o.ms/1e3).toFixed(3).padStart(9,\" \")}] ${o.line}`).join(`\n"
"`);n.textContent=n.textContent?n.textContent+`\n"
"`+r:r;let i=n.textContent.split(`\n"
"`);i.length>400&&(n.textContent=i.slice(-400).join(`\n"
"`)),s(\"autoscroll\").checked&&(n.scrollTop=n.scrollHeight)}catch{}}var C=0,pe=200,ge=[\"INFO\",\"WARN\",\"FEHLER\"],fe=[\"var(--hint)\",\"#c47f00\",\"var(--danger)\"];function _e(e,t){if(t>0){let n=new Date(t),r=i=>String(i).padStart(2,\"0\");return`${r(n.getHours())}:${r(n.getMinutes())}:${r(n.getSeconds())}`}return`${(e/1e3).toFixed(1)}s`}function be(e){let t=e.lvl>=0&&e.lvl<=2?e.lvl:0;return`<tr><td data-label=\"Zeit\" style=\"font-family:ui-monospace,monospace;white-space:nowrap\">${_e(e.ms,e.ts)}</td><td data-label=\"Level\" style=\"color:${fe[t]};font-weight:600\">${ge[t]}</td><td data-label=\"Quelle\" style=\"font-family:ui-monospace,monospace\">${m(e.tag)}</td><td data-label=\"Meldung\">${m(e.msg)}</td></tr>`}async function P(){if(f()===\"events\")try{let e=await u.events(C);if(C=e.last_seq,!e.events.length)return;let t=s(\"evt_body\");for(t.querySelector(\".hint\")&&(t.innerHTML=\"\"),t.insertAdjacentHTML(\"afterbegin\",e.events.map(be).reverse().join(\"\"));t.children.length>pe;)t.removeChild(t.lastElementChild)}catch{}}function E(){let e=s(\"con\"),t=document.createRange();t.selectNodeContents(e);let n=window.getSelection();n&&(n.removeAllRanges(),n.addRange(t))}async function he(){let e=s(\"con\").textContent||\"\";if(!e){a(\"Konsole ist leer\");return}try{await navigator.clipboard.writeText(e),a(`${e.length} Zeichen kopiert`)}catch{E(),a(\"Bitte manuell kopieren (Strg+C / Cmd+C)\")}}function ve(){s(\"con\").textContent=\"\",a(\"Konsole geleert\")}function Ee(){d=!d,s(\"btn-pause\").textContent=d?\"Weiter\":\"Pause\",a(d?\"Konsole angehalten\":\"Konsole laeuft\")}function ye(){s(\"con\").addEventListener(\"keydown\",t=>{(t.ctrlKey||t.metaKey)&&t.key.toLowerCase()===\"a\"&&(t.preventDefault(),E())}),document.addEventListener(\"keydown\",t=>{if(!(t.ctrlKey||t.metaKey)||t.key.toLowerCase()!==\"a\"||!document.getElementById(\"tab-konsole\")?.classList.contains(\"active\"))return;let r=document.activeElement;r&&(r.tagName===\"INPUT\"||r.tagName===\"TEXTAREA\"||r.tagName===\"SELECT\")||(t.preventDefault(),E())})}function Te(){W(),X(),y=new p(s(\"token\")),N=new p(s(\"adminp\")),T=new p(s(\"api_token\")),s(\"btn-scan\").addEventListener(\"click\",M),s(\"btn-regen\").addEventListener(\"click\",k),s(\"btn-regen2\").addEventListener(\"click\",k),s(\"btn-save\").addEventListener(\"click\",V),s(\"btn-factory\").addEventListener(\"click\",J),s(\"btn-clear\").addEventListener(\"click\",ve),s(\"btn-pause\").addEventListener(\"click\",Ee),s(\"btn-copy\").addEventListener(\"click\",he),s(\"btn-preset-ha\").addEventListener(\"click\",G),ye(),U(),M(),setInterval(H,3e3),setInterval($,3e3),setInterval(I,1e3),setInterval(P,2e3),H(),$(),I(),P()}Te();})();\n"
"</script>\n"
"</body>\n"
"</html>\n"
"\n"
;
