#pragma once
// AUTO-GENERATED from web/. Do NOT edit by hand - run "npm run build".

static const char PORTAL_HTML[] =
"<!doctype html>\n"
"<html lang=\"de\">\n"
"<head>\n"
"<meta charset=\"utf-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,viewport-fit=cover\">\n"
"<title>EUL Konfiguration</title>\n"
"<style>\n"
":root {\n"
"  color-scheme: light dark;\n"
"  --bg:#fff;\n"
"  --panel:#fafafa;\n"
"  --fg:#222;\n"
"  --hint:#666;\n"
"  --muted:#f0f0f0;\n"
"  --brand:#0057b7;\n"
"  --brand-fg:#fff;\n"
"  --danger:#a20000;\n"
"  --border:#ddd;\n"
"  --accent-focus:rgba(0,87,183,0.25);\n"
"}\n"
"@media (prefers-color-scheme: dark) {\n"
"  :root {\n"
"    --bg:#1b1b1e;\n"
"    --panel:#232327;\n"
"    --fg:#e6e6e6;\n"
"    --hint:#a0a0a0;\n"
"    --muted:#2b2b2f;\n"
"    --border:#3a3a3f;\n"
"    --accent-focus:rgba(255,255,255,0.15);\n"
"  }\n"
"}\n"
"* { box-sizing:border-box; }\n"
"html,body { margin:0; padding:0; background:var(--bg); color:var(--fg); }\n"
"body {\n"
"  font-family:system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",Helvetica,Arial,sans-serif;\n"
"  font-size:15px;\n"
"  line-height:1.45;\n"
"  min-height:100vh;\n"
"  display:flex;\n"
"  flex-direction:column;\n"
"}\n"
"\n"
"/* --- Header + Tabs --------------------------------------------------- */\n"
"header {\n"
"  padding:12px 16px 8px;\n"
"  border-bottom:1px solid var(--border);\n"
"  background:var(--panel);\n"
"}\n"
"header h1 { margin:0; font-size:1.2em; }\n"
"header .status { font-size:0.85em; color:var(--hint); margin-top:4px; }\n"
"nav.tabs {\n"
"  display:flex;\n"
"  overflow-x:auto;\n"
"  border-bottom:1px solid var(--border);\n"
"  background:var(--panel);\n"
"  -webkit-overflow-scrolling:touch;\n"
"  scrollbar-width:none;\n"
"}\n"
"nav.tabs::-webkit-scrollbar { display:none; }\n"
"nav.tabs button {\n"
"  flex:1;\n"
"  min-width:80px;\n"
"  background:transparent;\n"
"  color:var(--fg);\n"
"  border:0;\n"
"  border-bottom:3px solid transparent;\n"
"  padding:12px 8px;\n"
"  font-size:14px;\n"
"  font-weight:500;\n"
"  cursor:pointer;\n"
"  transition:color 0.15s, border-color 0.15s;\n"
"  white-space:nowrap;\n"
"}\n"
"nav.tabs button:hover { background:var(--muted); }\n"
"nav.tabs button.active {\n"
"  color:var(--brand);\n"
"  border-bottom-color:var(--brand);\n"
"}\n"
"\n"
"/* --- Main content ---------------------------------------------------- */\n"
"main {\n"
"  flex:1;\n"
"  padding:12px 16px 100px;   /* bottom padding fuer sticky footer */\n"
"  width:100%;                /* volle Fensterbreite */\n"
"  margin:0 auto;\n"
"}\n"
".tab { display:none; }\n"
".tab.active { display:block; }\n"
"\n"
"/* Geraete-Reiter: Liste nutzt die volle verfuegbare Hoehe. */\n"
"#tab-geraete.tab.active { display:flex; flex-direction:column; min-height:calc(100vh - 170px); }\n"
"#tab-geraete > fieldset { flex:1; display:flex; flex-direction:column; min-height:0; }\n"
"#tab-geraete .devwrap { flex:1; min-height:0; overflow:auto; }\n"
"\n"
"/* Sticky-Header: Ueberschriften bleiben beim Scrollen sichtbar (Desktop;\n"
"   im responsiven Modus ist die Kopfzeile ohnehin ausgeblendet). */\n"
"table.responsive thead th { position:sticky; top:0; background:var(--muted); z-index:2; }\n"
"\n"
"/* Telegramm: aufklappbare ESP3-Rohframe-Zerlegung. */\n"
"tr.tel-row:hover > td { background:var(--muted); }\n"
"tr.tel-detail > td { background:var(--muted); padding:8px 10px; }\n"
".rawwrap { overflow-x:auto; }\n"
".rawhex { font-family:ui-monospace,monospace; font-size:12px; color:var(--hint); margin-bottom:6px; white-space:nowrap; }\n"
"table.rawtbl { border-collapse:collapse; font-size:12px; }\n"
"table.rawtbl th { position:static; background:var(--bg); border:1px solid var(--border); padding:3px 8px; white-space:nowrap; font-weight:600; }\n"
"table.rawtbl td { border:1px solid var(--border); padding:3px 8px; white-space:nowrap; text-align:center; font-family:ui-monospace,monospace; }\n"
"\n"
"fieldset {\n"
"  border:1px solid var(--border);\n"
"  border-radius:6px;\n"
"  padding:12px;\n"
"  margin:0 0 14px;\n"
"  background:var(--panel);\n"
"}\n"
"legend { padding:0 6px; font-weight:600; font-size:0.95em; }\n"
"\n"
"label {\n"
"  display:block;\n"
"  margin:8px 0 3px;\n"
"  font-size:13px;\n"
"  color:var(--hint);\n"
"}\n"
"label.inline {\n"
"  display:inline-flex;\n"
"  align-items:center;\n"
"  gap:6px;\n"
"  color:var(--fg);\n"
"  font-size:14px;\n"
"  margin:6px 0;\n"
"}\n"
"label.inline input { margin:0; }\n"
"\n"
"input[type=text], input[type=password], input[type=number], select {\n"
"  width:100%;\n"
"  padding:10px 12px;\n"
"  font-size:16px;      /* verhindert iOS-zoom */\n"
"  background:var(--bg);\n"
"  color:var(--fg);\n"
"  border:1px solid var(--border);\n"
"  border-radius:6px;\n"
"  outline:none;\n"
"}\n"
"input:focus, select:focus { border-color:var(--brand); box-shadow:0 0 0 3px var(--accent-focus); }\n"
"\n"
"button {\n"
"  padding:10px 16px;\n"
"  border:0;\n"
"  border-radius:6px;\n"
"  background:var(--brand);\n"
"  color:var(--brand-fg);\n"
"  cursor:pointer;\n"
"  font-size:14px;\n"
"  font-weight:500;\n"
"  min-height:40px;\n"
"  transition:transform 0.05s, background 0.15s;\n"
"}\n"
"button:active { transform:scale(0.97); }\n"
"button.ghost { background:var(--muted); color:var(--fg); }\n"
"button.danger { background:var(--danger); color:#fff; }\n"
"button:disabled { opacity:0.5; cursor:not-allowed; }\n"
"\n"
".row { display:flex; gap:8px; align-items:center; flex-wrap:wrap; }\n"
".progress { display:none; height:10px; margin-top:10px; border-radius:5px;\n"
"            background:var(--border); overflow:hidden; }\n"
".progress > div { height:100%; width:0%; background:var(--brand);\n"
"                  border-radius:5px; transition:width .25s ease; }\n"
".progress.indet > div { width:30% !important; animation:indet 1.2s infinite ease-in-out; }\n"
"@keyframes indet { 0%{margin-left:-30%} 100%{margin-left:100%} }\n"
".row > * { min-width:0; }\n"
".row > input, .row > select { flex:1; }\n"
"\n"
".hint { font-size:0.85em; color:var(--hint); margin-top:4px; }\n"
".mono {\n"
"  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;\n"
"  background:var(--muted);\n"
"  padding:8px 10px;\n"
"  border-radius:4px;\n"
"  word-break:break-all;\n"
"  font-size:13px;\n"
"}\n"
"\n"
"/* --- Password + Secret --- */\n"
".pw-wrap { position:relative; display:block; }\n"
".pw-wrap input { padding-right:48px; }\n"
".pw-eye {\n"
"  position:absolute;\n"
"  right:4px;\n"
"  top:50%;\n"
"  transform:translateY(-50%);\n"
"  background:transparent;\n"
"  color:var(--hint);\n"
"  padding:8px;\n"
"  border:0;\n"
"  cursor:pointer;\n"
"  min-height:32px;\n"
"  min-width:36px;\n"
"  border-radius:4px;\n"
"  line-height:0;\n"
"}\n"
".pw-eye:hover { color:var(--fg); background:var(--muted); }\n"
".pw-eye svg { display:block; }\n"
"\n"
".secret {\n"
"  display:flex;\n"
"  align-items:center;\n"
"  gap:6px;\n"
"  background:var(--muted);\n"
"  padding:6px 8px;\n"
"  border-radius:6px;\n"
"  min-height:38px;\n"
"}\n"
".secret .val {\n"
"  flex:1;\n"
"  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;\n"
"  font-size:13px;\n"
"  word-break:break-all;\n"
"  user-select:all;\n"
"  -webkit-user-select:all;\n"
"}\n"
".secret .pw-eye { position:static; transform:none; }\n"
"\n"
"/* --- Table (Verbindungen) ------------------------------------------- */\n"
"table { width:100%; border-collapse:collapse; font-size:13px; }\n"
"th { text-align:left; font-weight:600; color:var(--hint); border-bottom:1px solid var(--border); padding:8px 6px; font-size:12px; text-transform:uppercase; letter-spacing:0.03em; }\n"
"td { padding:8px 6px; border-bottom:1px solid var(--muted); }\n"
"tr:last-child td { border-bottom:0; }\n"
"\n"
"@media (max-width:520px) {\n"
"  /* Table -> Card layout auf schmalen screens */\n"
"  table.responsive thead { display:none; }\n"
"  table.responsive tr {\n"
"    display:block;\n"
"    padding:8px 0;\n"
"    border-bottom:1px solid var(--border);\n"
"  }\n"
"  table.responsive tr:last-child { border-bottom:0; }\n"
"  table.responsive td {\n"
"    display:flex;\n"
"    justify-content:space-between;\n"
"    align-items:baseline;\n"
"    padding:3px 0;\n"
"    border:0;\n"
"    text-align:right !important;\n"
"  }\n"
"  table.responsive td::before {\n"
"    content:attr(data-label);\n"
"    color:var(--hint);\n"
"    font-size:0.85em;\n"
"    font-weight:500;\n"
"    margin-right:12px;\n"
"    text-transform:uppercase;\n"
"    letter-spacing:0.03em;\n"
"    text-align:left;\n"
"  }\n"
"}\n"
"\n"
"/* --- Konsole -------------------------------------------------------- */\n"
"pre.console {\n"
"  background:#0f0f10;\n"
"  color:#dcdcdc;\n"
"  padding:10px 12px;\n"
"  border-radius:6px;\n"
"  font-size:12px;\n"
"  line-height:1.4;\n"
"  height:60vh;\n"
"  min-height:280px;\n"
"  max-height:520px;\n"
"  overflow:auto;\n"
"  overflow-x:auto;\n"
"  white-space:pre-wrap;\n"
"  word-break:break-all;\n"
"  font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;\n"
"  user-select:text;\n"
"  -webkit-user-select:text;\n"
"  tab-size:2;\n"
"  margin:8px 0 0;\n"
"}\n"
"pre.console:focus {\n"
"  outline:2px solid var(--brand);\n"
"  outline-offset:2px;\n"
"}\n"
"\n"
"/* --- Sticky footer -------------------------------------------------- */\n"
"footer.actions {\n"
"  position:sticky;\n"
"  bottom:0;\n"
"  left:0;\n"
"  right:0;\n"
"  padding:10px 16px calc(10px + env(safe-area-inset-bottom));\n"
"  border-top:1px solid var(--border);\n"
"  background:color-mix(in srgb, var(--panel) 92%, transparent);\n"
"  backdrop-filter:blur(8px);\n"
"  -webkit-backdrop-filter:blur(8px);\n"
"  display:flex;\n"
"  gap:8px;\n"
"  justify-content:center;\n"
"  width:100%;\n"
"  margin:0 auto;\n"
"}\n"
"footer.actions button {\n"
"  flex:1;\n"
"  min-height:44px;\n"
"}\n"
"footer.actions .save { flex:2; }\n"
"\n"
"/* Sehr schmal: Buttons untereinander */\n"
"@media (max-width:380px) {\n"
"  footer.actions { flex-direction:column; }\n"
"  footer.actions button { min-height:40px; }\n"
"}\n"
"\n"
"/* --- Sonstiges ----------------------------------------------------- */\n"
"hr { border:0; border-top:1px solid var(--border); margin:12px 0; }\n"
"code { background:var(--muted); padding:1px 4px; border-radius:3px; font-size:0.9em; }\n"
"a { color:var(--brand); }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"\n"
"<header>\n"
"  <h1>Busware EUL</h1>\n"
"  <div class=\"status\" id=\"status\">lade...</div>\n"
"</header>\n"
"\n"
"<nav class=\"tabs\" id=\"tabs\">\n"
"  <button data-tab=\"status\" class=\"active\">Status</button>\n"
"  <button data-tab=\"allgemein\">Allgemein</button>\n"
"  <button data-tab=\"wifi\">WiFi</button>\n"
"  <button data-tab=\"usb\">USB</button>\n"
"  <button data-tab=\"enocean\">EnOcean</button>\n"
"  <button data-tab=\"geraete\">Geräte</button>\n"
"  <button data-tab=\"api\">API</button>\n"
"  <button data-tab=\"events\">Events</button>\n"
"  <button data-tab=\"konsole\">Konsole</button>\n"
"</nav>\n"
"\n"
"<main>\n"
"\n"
"  <!-- ============================================================ Status -->\n"
"  <section class=\"tab active\" id=\"tab-status\">\n"
"    <fieldset><legend>Gateway</legend>\n"
"      <div id=\"gwstat\" class=\"mono\" style=\"white-space:pre\">lade...</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Aktive Verbindungen</legend>\n"
"      <table class=\"responsive\">\n"
"        <thead>\n"
"          <tr><th>Peer</th><th>Uptime</th><th>RX</th><th>TX</th><th>Frames</th><th>Verworfen</th></tr>\n"
"        </thead>\n"
"        <tbody id=\"cli_body\">\n"
"          <tr><td colspan=\"6\" class=\"hint\">keine aktiven Verbindungen</td></tr>\n"
"        </tbody>\n"
"      </table>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Telegramme</legend>\n"
"      <input type=\"text\" id=\"tel_filter\" placeholder=\"Filter: Absender, Name, RORG, Bedeutung ...\" autocomplete=\"off\" style=\"margin-bottom:8px\">\n"
"      <div style=\"max-height:42vh;overflow:auto\">\n"
"        <table class=\"responsive\">\n"
"          <thead>\n"
"            <tr><th>Zeit</th><th>Ri.</th><th>Typ</th><th>RORG</th><th>Absender</th><th>Daten</th><th>Bedeutung</th><th>dBm</th></tr>\n"
"          </thead>\n"
"          <tbody id=\"tel_body\">\n"
"            <tr><td colspan=\"8\" class=\"hint\">warte auf Telegramme...</td></tr>\n"
"          </tbody>\n"
"        </table>\n"
"      </div>\n"
"      <div class=\"hint\">Dekodierte EnOcean-Funktelegramme (live, neueste oben). <code>&#8595;</code> empfangen vom TCM515 · <code>&#8593;</code> an den TCM515 gesendet. Name hinter dem Absender kommt aus dem Reiter <b>Geräte</b>. Zeile anklicken zeigt den <b>ESP3-Rohframe feldweise</b>.</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>TCM515-Statistik</legend>\n"
"      <div id=\"stats\" class=\"mono\" style=\"white-space:pre\">-</div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- ========================================================= Allgemein -->\n"
"  <section class=\"tab\" id=\"tab-allgemein\">\n"
"    <fieldset><legend>Geraet</legend>\n"
"      <label>Geraetename</label>\n"
"      <input type=\"text\" id=\"dev_name\" maxlength=\"39\" autocomplete=\"off\" placeholder=\"z.B. EnOcean Gateway Flur\">\n"
"      <div class=\"hint\">Anzeigename im Portal-Titel und in Home Assistant.</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Portal-Login</legend>\n"
"      <label>Benutzer</label>\n"
"      <input type=\"text\" id=\"admin_user\" maxlength=\"23\" autocomplete=\"off\" placeholder=\"admin\">\n"
"      <label>Aktuelles Passwort <span class=\"hint\">(nur beim Erst-Setup sichtbar)</span></label>\n"
"      <div id=\"adminp\" class=\"secret\"></div>\n"
"      <label>Neues Passwort <span class=\"hint\">(leer = unveraendert, min. 8 Zeichen)</span></label>\n"
"      <input type=\"password\" id=\"admin_pass_new\" maxlength=\"63\" placeholder=\"unveraendert\" autocomplete=\"off\" data-eye>\n"
"      <div class=\"hint\">Login fuer dieses Portal im Normalbetrieb (STA-Modus).</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Zeit (NTP)</legend>\n"
"      <label>NTP-Server</label>\n"
"      <input type=\"text\" id=\"ntp_server\" maxlength=\"63\" autocomplete=\"off\" placeholder=\"pool.ntp.org\">\n"
"      <label>Zeitzone</label>\n"
"      <select id=\"tz\"></select>\n"
"      <div class=\"hint\">Sommer-/Winterzeit wird gemaess Zone automatisch umgestellt.</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Firmware</legend>\n"
"      <div id=\"fw_info\" class=\"mono\" style=\"white-space:pre\">-</div>\n"
"      <label>Update einspielen (.bin)</label>\n"
"      <div class=\"row\">\n"
"        <input type=\"file\" id=\"ota_file\" accept=\".bin\">\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-ota\">Hochladen &amp; Update</button>\n"
"      </div>\n"
"      <div class=\"progress\" id=\"ota_bar_wrap\"><div id=\"ota_bar\"></div></div>\n"
"      <div id=\"ota_progress\" class=\"hint\">Datei: <code>.pio/build/busware-eul/firmware.bin</code>. Das Geraet startet nach erfolgreichem Update automatisch neu.</div>\n"
"      <hr>\n"
"      <label>OTA-Token <span class=\"hint\">(erlaubt NUR Firmware-Updates, kein Portal-Zugriff)</span></label>\n"
"      <div class=\"row\">\n"
"        <div id=\"ota_token\" class=\"secret\"></div>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-regen-ota\">Neu erzeugen</button>\n"
"      </div>\n"
"      <div class=\"hint\">Damit lassen sich Updates delegieren, ohne das Admin-Passwort weiterzugeben:<br>\n"
"        <code>curl -H \"Authorization: Bearer &lt;token&gt;\" --data-binary @firmware.bin http://&lt;ip&gt;/api/ota</code><br>\n"
"        &bdquo;Neu erzeugen&ldquo; macht den alten Token sofort ungueltig.</div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- ============================================================== WiFi -->\n"
"  <section class=\"tab\" id=\"tab-wifi\">\n"
"    <fieldset><legend>WLAN (Heimnetz)</legend>\n"
"      <label>SSID</label>\n"
"      <div class=\"row\">\n"
"        <select id=\"ssid_sel\"><option value=\"\">-- Netzwerk waehlen --</option></select>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-scan\">Suchen</button>\n"
"      </div>\n"
"      <label>oder SSID manuell</label>\n"
"      <input type=\"text\" id=\"ssid\" maxlength=\"32\" autocomplete=\"off\">\n"
"      <label>Passwort <span class=\"hint\">(Auge-Button zum Anzeigen)</span></label>\n"
"      <input type=\"password\" id=\"pass\" maxlength=\"63\" placeholder=\"(nicht gesetzt)\" autocomplete=\"off\" data-eye>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- =============================================================== USB -->\n"
"  <section class=\"tab\" id=\"tab-usb\">\n"
"    <fieldset><legend>USB-CDC-Bridge</legend>\n"
"      <label class=\"inline\"><input type=\"checkbox\" id=\"usb_en\"> USB als transparente ESP3-Bridge aktivieren</label>\n"
"      <div class=\"hint\">Erlaubt Direkt-Zugriff auf den TCM515 ueber die USB-C-Buchse als virtuellen COM-Port. Aus Sicherheitsgruenden (CRA) standardmaessig aus.</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Hinweis</legend>\n"
"      <div class=\"hint\">\n"
"        USB-Traffic wird nicht in die Web-Konsole gespiegelt. Zur Diagnose am USB-Kanal\n"
"        lokal <code>pio device monitor</code> oder <code>screen /dev/cu.usbmodemXXXX 460800</code> verwenden.\n"
"      </div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- =========================================================== EnOcean -->\n"
"  <section class=\"tab\" id=\"tab-enocean\">\n"
"    <fieldset><legend>TCM515 Base-ID</legend>\n"
"      <label>Base-ID <span class=\"hint\">(Format FF-xx-xx-xx)</span></label>\n"
"      <div class=\"row\">\n"
"        <input type=\"text\" id=\"baseid_in\" maxlength=\"11\" autocomplete=\"off\" placeholder=\"FF-xx-xx-xx\" style=\"font-family:ui-monospace,monospace\">\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-baseid-read\">Lesen</button>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-baseid-write\">Schreiben</button>\n"
"      </div>\n"
"      <div id=\"baseid_info\" class=\"hint\">Base-ID des Funkmoduls. Sie ist der Ausgangspunkt der 128 Sender-IDs, die das Gateway selbst senden kann.</div>\n"
"      <div class=\"hint\">Achtung: Der TCM515 erlaubt herstellerseitig nur rund <b>10 Schreibvorgänge</b>. Gültiger Bereich: <code>FF800000</code>…<code>FFFFFF80</code>.</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>TCP-Bridge (Home Assistant / FHEM / ...)</legend>\n"
"      <label class=\"inline\"><input type=\"checkbox\" id=\"tcp_en\"> TCP-Server aktivieren</label>\n"
"      <label>Port</label>\n"
"      <input type=\"number\" id=\"tcp_port\" value=\"5100\" min=\"1\" max=\"65535\">\n"
"      <label class=\"inline\"><input type=\"checkbox\" id=\"tcp_auth\"> AUTH-Token verlangen <span class=\"hint\">(empfohlen)</span></label>\n"
"      <label>Aktueller Token</label>\n"
"      <div class=\"row\">\n"
"        <div id=\"token\" class=\"secret\"></div>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-regen\">Neu erzeugen</button>\n"
"      </div>\n"
"      <div class=\"hint\">Handshake: Server sendet <code>HELLO EUL v1 AUTH-REQUIRED</code>, Client antwortet mit <code>AUTH &lt;token&gt;</code>.</div>\n"
"      <hr>\n"
"      <button type=\"button\" class=\"ghost\" id=\"btn-preset-ha\">Preset: HA-Eltako Integration</button>\n"
"      <div class=\"hint\">Setzt Port 5100 + Auth aus (MGW-LAN-Konvention der <a href=\"https://github.com/FMDHET/home-assistant-eltako\" target=\"_blank\" rel=\"noopener\">Eltako HA-Integration</a>).</div>\n"
"      <div id=\"ha_yaml_box\" style=\"display:none;margin-top:10px\">\n"
"        <label>HA-Config (nach Speichern &amp; Neustart einsetzbar)</label>\n"
"        <pre id=\"ha_yaml\" class=\"mono\" style=\"white-space:pre;overflow:auto;font-size:12px;padding:10px\"></pre>\n"
"      </div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- =========================================================== Geraete -->\n"
"  <section class=\"tab\" id=\"tab-geraete\">\n"
"    <fieldset><legend>Bekannte Geräte</legend>\n"
"      <div class=\"devwrap\">\n"
"        <table class=\"responsive\">\n"
"          <thead>\n"
"            <tr><th>Absender</th><th>Name</th><th>Eltako Gerät</th><th>EEP-Profil</th></tr>\n"
"          </thead>\n"
"          <tbody id=\"dev_body\">\n"
"            <tr><td colspan=\"4\" class=\"hint\">noch keine Absender gesehen</td></tr>\n"
"          </tbody>\n"
"        </table>\n"
"      </div>\n"
"      <div class=\"hint\">Jeder empfangene Absender wird hier automatisch eingetragen. <b>Name</b> frei vergeben (erscheint im Status hinter dem Absender). <b>Eltako Gerät</b> wählen setzt automatisch das passende <b>EEP-Profil</b>; das EEP wird auch aus A5-Lerntelegrammen gelernt und bestimmt die „Bedeutung“-Dekodierung. Alles nur im Browser gespeichert.</div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- =============================================================== API -->\n"
"  <section class=\"tab\" id=\"tab-api\">\n"
"    <fieldset><legend>REST-API</legend>\n"
"      <label class=\"inline\"><input type=\"checkbox\" id=\"api_en\"> REST-API aktivieren</label>\n"
"      <div class=\"hint\">HTTP-Zugriff auf empfangene Telegramme und zum Senden. Authentifizierung ueber den Geraete-Token, per Header <code>Authorization: Bearer &lt;token&gt;</code> oder Query <code>?token=&lt;token&gt;</code>.</div>\n"
"      <label>Geraete-Token</label>\n"
"      <div class=\"row\">\n"
"        <div id=\"api_token\" class=\"secret\"></div>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-regen2\">Neu erzeugen</button>\n"
"      </div>\n"
"      <div class=\"hint\">Derselbe Token wie fuer die TCP-Bridge (Reiter EnOcean).</div>\n"
"    </fieldset>\n"
"\n"
"    <fieldset><legend>Endpunkte</legend>\n"
"      <pre id=\"api_doc\" class=\"mono\" style=\"white-space:pre-wrap;overflow:auto;font-size:12px;padding:10px\">API deaktiviert oder Adresse unbekannt.</pre>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- ============================================================ Events -->\n"
"  <section class=\"tab\" id=\"tab-events\">\n"
"    <fieldset><legend>Ereignisse</legend>\n"
"      <div style=\"max-height:60vh;overflow:auto\">\n"
"        <table class=\"responsive\">\n"
"          <thead>\n"
"            <tr><th>Zeit</th><th>Level</th><th>Quelle</th><th>Meldung</th></tr>\n"
"          </thead>\n"
"          <tbody id=\"evt_body\">\n"
"            <tr><td colspan=\"4\" class=\"hint\">warte auf Ereignisse...</td></tr>\n"
"          </tbody>\n"
"        </table>\n"
"      </div>\n"
"      <div class=\"hint\">Boot, WLAN (Verbindung/Trennung mit Grund), TCP-Clients, Security, periodischer Netz-Status. Neueste oben.</div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"  <!-- =========================================================== Konsole -->\n"
"  <section class=\"tab\" id=\"tab-konsole\">\n"
"    <fieldset><legend>Live-Datenverkehr</legend>\n"
"      <div class=\"row\" style=\"margin-bottom:6px\">\n"
"        <label class=\"inline\" style=\"flex:1\"><input type=\"checkbox\" id=\"autoscroll\" checked> Auto-Scroll</label>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-copy\">Kopieren</button>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-clear\">Leeren</button>\n"
"        <button type=\"button\" class=\"ghost\" id=\"btn-pause\">Pause</button>\n"
"      </div>\n"
"      <pre id=\"con\" class=\"console\" tabindex=\"0\" aria-label=\"Konsole. Klicken oder fokussieren, dann Strg+A um Inhalt zu markieren.\"></pre>\n"
"      <div class=\"hint\">\n"
"        <code>&lt; TCM</code> = vom Modul empfangen, <code>&gt; ip:port</code> = von diesem Client gesendet.\n"
"        Fokus auf die Konsole (Klick) und <code>Strg+A</code> / <code>Cmd+A</code> markiert nur die Konsole.\n"
"      </div>\n"
"    </fieldset>\n"
"  </section>\n"
"\n"
"</main>\n"
"\n"
"<footer class=\"actions\">\n"
"  <button type=\"button\" class=\"save\" id=\"btn-save\">Speichern</button>\n"
"  <button type=\"button\" class=\"ghost\" id=\"btn-reboot\">Neustart</button>\n"
"  <button type=\"button\" class=\"danger\" id=\"btn-factory\">Werkseinstellungen</button>\n"
"</footer>\n"
"\n"
"<script>\"use strict\";(()=>{var A={\"A5-02-01\":{cls:\"4BS\",lin:[{hi:[255,-40],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich -40\\xB0C bis 0\\xB0C\"},\"A5-02-02\":{cls:\"4BS\",lin:[{hi:[255,-30],k:\"Temperatur\",lo:[0,10],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich -30\\xB0C bis +10\\xB0C\"},\"A5-02-03\":{cls:\"4BS\",lin:[{hi:[255,-20],k:\"Temperatur\",lo:[0,20],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich -20\\xB0C bis +20\\xB0C\"},\"A5-02-04\":{cls:\"4BS\",lin:[{hi:[255,-10],k:\"Temperatur\",lo:[0,30],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich -10\\xB0C bis +30\\xB0C\"},\"A5-02-05\":{cls:\"4BS\",lin:[{hi:[255,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich 0\\xB0C bis +40\\xB0C\"},\"A5-02-06\":{cls:\"4BS\",lin:[{hi:[255,10],k:\"Temperatur\",lo:[0,50],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich +10\\xB0C bis +50\\xB0C\"},\"A5-02-07\":{cls:\"4BS\",lin:[{hi:[255,20],k:\"Temperatur\",lo:[0,60],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich +20\\xB0C bis +60\\xB0C\"},\"A5-02-08\":{cls:\"4BS\",lin:[{hi:[255,30],k:\"Temperatur\",lo:[0,70],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich +30\\xB0C bis +70\\xB0C\"},\"A5-02-09\":{cls:\"4BS\",lin:[{hi:[255,40],k:\"Temperatur\",lo:[0,80],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich +40\\xB0C bis +80\\xB0C\"},\"A5-02-0A\":{cls:\"4BS\",lin:[{hi:[255,50],k:\"Temperatur\",lo:[0,90],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich +50\\xB0C bis +90\\xB0C\"},\"A5-02-0B\":{cls:\"4BS\",lin:[{hi:[255,60],k:\"Temperatur\",lo:[0,100],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich +60\\xB0C bis +100\\xB0C\"},\"A5-02-10\":{cls:\"4BS\",lin:[{hi:[255,-60],k:\"Temperatur\",lo:[0,20],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich -60\\xB0C bis +20\\xB0C\"},\"A5-02-11\":{cls:\"4BS\",lin:[{hi:[255,-50],k:\"Temperatur\",lo:[0,30],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich -50\\xB0C bis +30\\xB0C\"},\"A5-02-12\":{cls:\"4BS\",lin:[{hi:[255,-40],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich -40\\xB0C bis +40\\xB0C\"},\"A5-02-13\":{cls:\"4BS\",lin:[{hi:[255,-30],k:\"Temperatur\",lo:[0,50],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich -30\\xB0C bis +50\\xB0C\"},\"A5-02-14\":{cls:\"4BS\",lin:[{hi:[255,-20],k:\"Temperatur\",lo:[0,60],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich -20\\xB0C bis +60\\xB0C\"},\"A5-02-15\":{cls:\"4BS\",lin:[{hi:[255,-10],k:\"Temperatur\",lo:[0,70],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich -10\\xB0C bis +70\\xB0C\"},\"A5-02-16\":{cls:\"4BS\",lin:[{hi:[255,0],k:\"Temperatur\",lo:[0,80],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich 0\\xB0C bis +80\\xB0C\"},\"A5-02-17\":{cls:\"4BS\",lin:[{hi:[255,10],k:\"Temperatur\",lo:[0,90],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich +10\\xB0C bis +90\\xB0C\"},\"A5-02-18\":{cls:\"4BS\",lin:[{hi:[255,20],k:\"Temperatur\",lo:[0,100],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich +20\\xB0C bis +100\\xB0C\"},\"A5-02-19\":{cls:\"4BS\",lin:[{hi:[255,30],k:\"Temperatur\",lo:[0,110],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich +30\\xB0C bis +110\\xB0C\"},\"A5-02-1A\":{cls:\"4BS\",lin:[{hi:[255,40],k:\"Temperatur\",lo:[0,120],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich +40\\xB0C bis +120\\xB0C\"},\"A5-02-1B\":{cls:\"4BS\",lin:[{hi:[255,50],k:\"Temperatur\",lo:[0,130],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatursensoren, Temperatursensor Bereich +50\\xB0C bis +130\\xB0C\"},\"A5-02-20\":{cls:\"4BS\",t:\"Temperatursensoren, 10 Bit Temperatursensor Bereich -10\\xB0C bis +41.2\\xB0C\"},\"A5-02-30\":{cls:\"4BS\",t:\"Temperatursensoren, 10 Bit Temperatursensor Bereich -40\\xB0C bis +62.3\\xB0C\"},\"A5-04-01\":{cls:\"4BS\",lin:[{hi:[250,100],k:\"Feuchte\",lo:[0,0],sb:8,u:\"%\",w:8},{hi:[250,40],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatur- und Feuchtesensor, Bereich 0\\xB0C bis +40\\xB0C und 0% bis 100%\"},\"A5-04-02\":{cls:\"4BS\",lin:[{hi:[250,100],k:\"Feuchte\",lo:[0,0],sb:8,u:\"%\",w:8},{hi:[250,60],k:\"Temperatur\",lo:[0,-20],sb:16,u:\"\\xB0C\",w:8}],t:\"Temperatur- und Feuchtesensor, Bereich -20\\xB0C bis +60\\xB0C und 0% bis 100%\"},\"A5-04-03\":{cls:\"4BS\",lin:[{hi:[255,100],k:\"Feuchte\",lo:[0,0],sb:0,u:\"%\",w:8}],t:\"Temperatur- und Feuchtesensor, Bereich -20\\xB0C bis +60\\xB0C 10bit-measurement und 0% bis 100%\"},\"A5-05-01\":{cls:\"4BS\",t:\"Barometrischer Sensor, Bereich 500 bis 1150 hPa\"},\"A5-06-01\":{cls:\"4BS\",lin:[{hi:[255,51],k:\"Versorgungsspannung\",lo:[0,0],sb:0,u:\"V\",w:8},{hi:[255,3e4],k:\"Beleuchtungsst\\xE4rke\",lo:[0,300],sb:8,u:\"lx\",w:8},{hi:[255,6e4],k:\"Beleuchtungsst\\xE4rke\",lo:[0,600],sb:16,u:\"lx\",w:8}],t:\"Lichtsensor, Bereich 300lx bis 60.000lx\"},\"A5-06-02\":{cls:\"4BS\",lin:[{hi:[255,5.1],k:\"Versorgungsspannung\",lo:[0,0],sb:0,u:\"V\",w:8},{hi:[255,510],k:\"Beleuchtungsst\\xE4rke 2\",lo:[0,0],sb:8,w:8},{hi:[255,1020],k:\"Beleuchtungsst\\xE4rke 1\",lo:[0,0],sb:16,w:8}],t:\"Lichtsensor, Bereich 0lx bis 1.020lx\"},\"A5-06-03\":{cls:\"4BS\",lin:[{hi:[250,50],k:\"Versorgungsspannung\",lo:[0,0],sb:0,u:\"V\",w:8},{hi:[250,1e3],k:\"Beleuchtungsst\\xE4rke\",lo:[0,0],sb:8,u:\"lx\",w:8}],t:\"Lichtsensor, 10-bit measurement (1-Lux resolution) mit range 0lx bis 1000lx\"},\"A5-06-04\":{cls:\"4BS\",lin:[{hi:[255,60],k:\"Temperatur\",lo:[0,-20],sb:0,u:\"\\xB0C\",w:8},{hi:[65535,65535],k:\"Beleuchtungsst\\xE4rke\",lo:[0,0],sb:8,u:\"lx\",w:16}],t:\"Lichtsensor \\u2013 Fassaden-Helligkeitssensor\"},\"A5-07-01\":{cls:\"4BS\",lin:[{hi:[250,5],k:\"Versorgungsspannung\",lo:[0,0],sb:0,w:8}],t:\"Anwesenheitssensor, Anwesenheit mit Versorgungsspannung monitor\"},\"A5-07-02\":{cls:\"4BS\",lin:[{hi:[250,50],k:\"Versorgungsspannung\",lo:[0,0],sb:0,w:8}],t:\"Anwesenheitssensor, Anwesenheit mit Versorgungsspannung monitor\"},\"A5-08-01\":{cls:\"4BS\",lin:[{hi:[255,51],k:\"Versorgungsspannung\",lo:[0,0],sb:0,u:\"V\",w:8},{hi:[255,510],k:\"Beleuchtungsst\\xE4rke\",lo:[0,0],sb:8,u:\"lx\",w:8},{hi:[255,51],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"Licht, Temperatur und Anwesenheitssensor, Bereich 0lx bis 510lx, 0\\xB0C bis +51\\xB0C und Anwesenheit Button\"},\"A5-08-02\":{cls:\"4BS\",lin:[{hi:[255,51],k:\"Versorgungsspannung\",lo:[0,0],sb:0,u:\"V\",w:8},{hi:[255,1020],k:\"Beleuchtungsst\\xE4rke\",lo:[0,0],sb:8,u:\"lx\",w:8},{hi:[255,51],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"Licht, Temperatur und Anwesenheitssensor, Bereich 0lx bis 1020lx, 0\\xB0C bis +51\\xB0C und Anwesenheit Button\"},\"A5-08-03\":{cls:\"4BS\",lin:[{hi:[255,51],k:\"Versorgungsspannung\",lo:[0,0],sb:0,u:\"V\",w:8},{hi:[255,1530],k:\"Beleuchtungsst\\xE4rke\",lo:[0,0],sb:8,u:\"lx\",w:8},{hi:[255,50],k:\"Temperatur\",lo:[0,-30],sb:16,u:\"\\xB0C\",w:8}],t:\"Licht, Temperatur und Anwesenheitssensor, Bereich 0lx bis 1530lx, -30\\xB0C bis +50\\xB0C und Anwesenheit Button\"},\"A5-09-02\":{cls:\"4BS\",lin:[{hi:[255,51],k:\"Versorgungsspannung\",lo:[0,0],sb:0,u:\"V\",w:8},{hi:[255,1020],k:\"Konzentration\",lo:[0,0],sb:8,u:\"ppm\",w:8},{hi:[255,51],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"Gassensor, CO-Sensor 0 ppm bis 1020 ppm\"},\"A5-09-04\":{cls:\"4BS\",lin:[{hi:[200,100],k:\"Feuchte\",lo:[0,0],sb:0,u:\"%\",w:8},{hi:[255,2550],k:\"Konzentration\",lo:[0,0],sb:8,u:\"ppm\",w:8},{hi:[255,51],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"Gassensor, CO\\u2082-Sensor\"},\"A5-09-05\":{cls:\"4BS\",lin:[{hi:[65535,65535],k:\"VOC\",lo:[0,0],sb:0,w:16}],t:\"Gassensor, VOC Sensor\"},\"A5-09-06\":{cls:\"4BS\",lin:[{hi:[255,1023],k:\"Radon\",lo:[0,0],sb:0,u:\"Bq/m3\",w:8}],t:\"Gassensor, Radon\"},\"A5-09-07\":{cls:\"4BS\",lin:[{hi:[255,511],k:\"Feinstaub PM10\",lo:[0,0],sb:0,u:\"\\xB5g/m3\",w:8}],t:\"Gassensor, Particles\"},\"A5-09-08\":{cls:\"4BS\",lin:[{hi:[255,2e3],k:\"CO\\u2082\",lo:[0,0],sb:16,u:\"ppm\",w:8}],t:\"Gassensor, Pure CO\\u2082-Sensor\"},\"A5-09-09\":{cls:\"4BS\",lin:[{hi:[255,2e3],k:\"CO\\u2082\",lo:[0,0],sb:16,u:\"ppm\",w:8}],t:\"Gassensor, Pure CO\\u2082-Sensor mit Stromausfallerkennung\"},\"A5-09-0A\":{cls:\"4BS\",lin:[{hi:[65535,65535],k:\"Konzentration\",lo:[0,0],sb:0,u:\"ppm\",w:16},{hi:[255,60],k:\"Temperatur\",lo:[0,-20],sb:16,u:\"\\xB0C\",w:8}],t:\"Gassensor, Hydrogen Gassensor\"},\"A5-09-0C\":{cls:\"4BS\",t:\"Gassensor, VOC Sensor\"},\"A5-10-01\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Sollwert\",lo:[0,0],sb:8,w:8},{hi:[255,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatursensor, Sollwert, L\\xFCfterstufe und Anwesenheit Steuerung\"},\"A5-10-02\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Sollwert\",lo:[0,0],sb:8,w:8},{hi:[255,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatursensor, Sollwert, L\\xFCfterstufe und Tag-/Nacht-Steuerung\"},\"A5-10-03\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Sollwert\",lo:[0,0],sb:8,w:8},{hi:[255,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatursensor, Sollwert Steuerung\"},\"A5-10-04\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Sollwert\",lo:[0,0],sb:8,w:8},{hi:[255,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatursensor, Sollwert und L\\xFCfterstufe Steuerung\"},\"A5-10-05\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Sollwert\",lo:[0,0],sb:8,w:8},{hi:[255,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatursensor, Sollwert und Anwesenheit Steuerung\"},\"A5-10-06\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Sollwert\",lo:[0,0],sb:8,w:8},{hi:[255,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatursensor, Sollwert und Tag-/Nacht-Steuerung\"},\"A5-10-07\":{cls:\"4BS\",lin:[{hi:[255,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatursensor, L\\xFCfterstufe Steuerung\"},\"A5-10-08\":{cls:\"4BS\",lin:[{hi:[255,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatursensor, L\\xFCfterstufe und Anwesenheit Steuerung \"},\"A5-10-09\":{cls:\"4BS\",lin:[{hi:[255,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatursensor, L\\xFCfterstufe und Tag-/Nacht-Steuerung\"},\"A5-10-0A\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Sollwert\",lo:[0,0],sb:8,w:8},{hi:[255,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatursensor, Sollwert Adjust und Single Input Contact\"},\"A5-10-0B\":{cls:\"4BS\",t:\"Raumbedienger\\xE4t, Temperatursensor und Single Input Contact\"},\"A5-10-0C\":{cls:\"4BS\",lin:[{hi:[255,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatursensor und Anwesenheit Steuerung\"},\"A5-10-0D\":{cls:\"4BS\",t:\"Raumbedienger\\xE4t, Temperatursensor und Tag-/Nacht-Steuerung\"},\"A5-10-10\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Sollwert\",lo:[0,0],sb:0,w:8},{hi:[250,100],k:\"Feuchte\",lo:[0,0],sb:8,u:\"%\",w:8},{hi:[250,40],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatur- und Feuchtesensor, Sollwert und Anwesenheit Steuerung\"},\"A5-10-11\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Sollwert\",lo:[0,0],sb:0,w:8},{hi:[250,100],k:\"Feuchte\",lo:[0,0],sb:8,u:\"%\",w:8},{hi:[250,40],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatur- und Feuchtesensor, Sollwert und Tag-/Nacht-Steuerung\"},\"A5-10-12\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Sollwert\",lo:[0,0],sb:0,w:8},{hi:[250,100],k:\"Feuchte\",lo:[0,0],sb:8,u:\"%\",w:8},{hi:[250,40],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatur- und Feuchtesensor und Sollwert\"},\"A5-10-13\":{cls:\"4BS\",lin:[{hi:[250,100],k:\"Feuchte\",lo:[0,0],sb:8,u:\"%\",w:8},{hi:[250,40],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatur- und Feuchtesensor, Anwesenheit Steuerung\"},\"A5-10-14\":{cls:\"4BS\",lin:[{hi:[250,100],k:\"Feuchte\",lo:[0,0],sb:8,u:\"%\",w:8},{hi:[250,40],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatur- und Feuchtesensor, Tag-/Nacht-Steuerung\"},\"A5-10-15\":{cls:\"4BS\",t:\"Raumbedienger\\xE4t, 10 Bit Temperatursensor, 6 bit Sollwert Steuerung\"},\"A5-10-16\":{cls:\"4BS\",t:\"Raumbedienger\\xE4t, 10 Bit Temperatursensor, 6 bit Sollwert Steuerung;Anwesenheit Steuerung\"},\"A5-10-17\":{cls:\"4BS\",t:\"Raumbedienger\\xE4t, 10 Bit Temperatursensor, Anwesenheit Steuerung\"},\"A5-10-18\":{cls:\"4BS\",lin:[{hi:[250,1e3],k:\"Beleuchtungsst\\xE4rke\",lo:[0,0],sb:0,u:\"lx\",w:8},{hi:[250,0],k:\"Temperatur-Sollwert\",lo:[0,40],sb:8,w:8},{hi:[250,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Beleuchtungsst\\xE4rke, Temperatur Sollwert, Temperatursensor, L\\xFCfterstufe und Anwesenheit Steuerung\"},\"A5-10-19\":{cls:\"4BS\",lin:[{hi:[250,100],k:\"Feuchte\",lo:[0,0],sb:0,u:\"%\",w:8},{hi:[250,0],k:\"Temperatur-Sollwert\",lo:[0,40],sb:8,w:8},{hi:[250,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Feuchte, Temperatur Sollwert, Temperatursensor, L\\xFCfterstufe und Anwesenheit Steuerung\"},\"A5-10-1A\":{cls:\"4BS\",lin:[{hi:[250,5],k:\"Versorgungsspannung\",lo:[0,0],sb:0,u:\"V\",w:8},{hi:[250,0],k:\"Temperatur-Sollwert\",lo:[0,40],sb:8,w:8},{hi:[250,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Versorgungsspannung monitor, Temperatur Sollwert, Temperatursensor, L\\xFCfterstufe und Anwesenheit Steuerung\"},\"A5-10-1B\":{cls:\"4BS\",lin:[{hi:[250,5],k:\"Versorgungsspannung\",lo:[0,0],sb:0,u:\"V\",w:8},{hi:[250,1e3],k:\"Beleuchtungsst\\xE4rke\",lo:[0,0],sb:8,u:\"lx\",w:8},{hi:[250,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Supply Voltage Monitor, Beleuchtungsst\\xE4rke, Temperatursensor, L\\xFCfterstufe und Anwesenheit Steuerung\"},\"A5-10-1C\":{cls:\"4BS\",lin:[{hi:[250,1e3],k:\"Beleuchtungsst\\xE4rke\",lo:[0,0],sb:0,u:\"lx\",w:8},{hi:[250,1e3],k:\"Beleuchtungs-Sollwert\",lo:[0,0],sb:8,u:\"lx\",w:8},{hi:[250,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Beleuchtungsst\\xE4rke, Beleuchtungsst\\xE4rke Sollwert, Temperatursensor, L\\xFCfterstufe und Anwesenheit Steuerung\"},\"A5-10-1D\":{cls:\"4BS\",lin:[{hi:[250,100],k:\"Feuchte\",lo:[0,0],sb:0,u:\"%\",w:8},{hi:[250,100],k:\"Feuchte-Sollwert\",lo:[0,0],sb:8,u:\"%\",w:8},{hi:[250,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Feuchte, Feuchte Sollwert, Temperatursensor, L\\xFCfterstufe und Anwesenheit Steuerung\"},\"A5-10-1E\":{cls:\"4BS\",t:\"Raumbedienger\\xE4t, Feuchte, Feuchte Sollwert, Temperatursensor, L\\xFCfterstufe und Anwesenheit Steuerung\"},\"A5-10-1F\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Sollwert\",lo:[0,0],sb:8,w:8},{hi:[255,0],k:\"Temperatur\",lo:[0,40],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatursensor, Sollwert, L\\xFCfterstufe, Anwesenheit und Unoccupancy Steuerung\"},\"A5-10-20\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Sollwert\",lo:[0,0],sb:0,w:8},{hi:[250,40],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatur und Sollwert mit Special Heating States\"},\"A5-10-21\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Sollwert\",lo:[0,0],sb:0,w:8},{hi:[250,100],k:\"Feuchte\",lo:[0,0],sb:8,u:\"%\",w:8},{hi:[250,40],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatur, Feuchte und Sollwert mit Special Heating States\"},\"A5-10-22\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Relativer Sollwert\",lo:[0,0],sb:0,w:8},{hi:[250,100],k:\"Feuchte\",lo:[0,0],sb:8,u:\"%\",w:8},{hi:[250,40],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatur, Setpoint, Feuchte und L\\xFCfterstufe\"},\"A5-10-23\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Relativer Sollwert\",lo:[0,0],sb:0,w:8},{hi:[250,100],k:\"Feuchte\",lo:[0,0],sb:8,u:\"%\",w:8},{hi:[250,40],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"Raumbedienger\\xE4t, Temperatur, Setpoint, Feuchte, L\\xFCfterstufe und Anwesenheit\"},\"A5-11-01\":{cls:\"4BS\",lin:[{hi:[255,510],k:\"Beleuchtungsst\\xE4rke\",lo:[0,0],sb:0,u:\"lx\",w:8},{hi:[255,255],k:\"Beleuchtungs-Sollwert\",lo:[0,0],sb:8,w:8},{hi:[255,255],k:\"Dimmwert\",lo:[0,0],sb:16,w:8}],t:\"Controller-Status, Lighting Controller\"},\"A5-11-03\":{cls:\"4BS\",lin:[{hi:[100,100],k:\"Behang-/Rollladenposition\",lo:[0,0],sb:0,w:8}],t:\"Controller-Status, Blind Status\"},\"A5-11-04\":{cls:\"4BS\",t:\"Controller-Status, Extended Lighting Status\"},\"A5-12-00\":{cls:\"4BS\",lin:[{hi:[16777215,16777215],k:\"Z\\xE4hlerstand\",lo:[0,0],sb:0,w:24}],t:\"Automatische Z\\xE4hlererfassung (AMR), Counter\"},\"A5-12-01\":{cls:\"4BS\",lin:[{hi:[16777215,16777215],k:\"Z\\xE4hlerstand\",lo:[0,0],sb:0,w:24}],t:\"Automatische Z\\xE4hlererfassung (AMR), Strom\"},\"A5-12-02\":{cls:\"4BS\",lin:[{hi:[16777215,16777215],k:\"Z\\xE4hlerstand\",lo:[0,0],sb:0,w:24}],t:\"Automatische Z\\xE4hlererfassung (AMR), Gas\"},\"A5-12-03\":{cls:\"4BS\",lin:[{hi:[16777215,16777215],k:\"Z\\xE4hlerstand\",lo:[0,0],sb:0,w:24}],t:\"Automatische Z\\xE4hlererfassung (AMR), Water\"},\"A5-13-01\":{cls:\"4BS\",lin:[{hi:[255,999],k:\"D\\xE4mmerungssensor\",lo:[0,0],sb:0,u:\"lx\",w:8},{hi:[255,80],k:\"Temperatur\",lo:[0,-40],sb:8,u:\"\\xB0C\",w:8},{hi:[255,70],k:\"Windgeschwindigkeit\",lo:[0,0],sb:16,u:\"m/s\",w:8}],t:\"Umweltanwendungen, Sonnenintensit\\xE4t\"},\"A5-13-03\":{cls:\"4BS\",t:\"Umweltanwendungen, Date Exchange\"},\"A5-13-04\":{cls:\"4BS\",t:\"Umweltanwendungen, Time und Day Exchange\"},\"A5-13-05\":{cls:\"4BS\",lin:[{hi:[180,90],k:\"Sonnenh\\xF6he\",lo:[0,-90],sb:0,u:\"\\xB0\",w:8}],t:\"Umweltanwendungen, Direction Exchange\"},\"A5-13-06\":{cls:\"4BS\",t:\"Umweltanwendungen, Geographic Position Exchange\"},\"A5-13-07\":{cls:\"4BS\",lin:[{hi:[255,1999],k:\"Mittlere Windgeschwindigkeit\",lo:[0,1],sb:8,w:8},{hi:[255,1999],k:\"Max. Windgeschwindigkeit\",lo:[0,1],sb:16,w:8}],t:\"Umweltanwendungen, Wind Sensor\"},\"A5-13-10\":{cls:\"4BS\",lin:[{hi:[180,90],k:\"Sonnen-Azimut\",lo:[0,-90],sb:8,u:\"\\xB0\",w:8}],t:\"Umweltanwendungen, Sun position und radiation\"},\"A5-13-11\":{cls:\"4BS\",t:\"Umweltanwendungen, Noise\"},\"A5-14-01\":{cls:\"4BS\",lin:[{hi:[250,50],k:\"Versorgungsspannung\",lo:[0,0],sb:0,u:\"V\",w:8}],t:\"Multifunktionssensor, Single Input Contact (Window/Door), Versorgungsspannung monitor\"},\"A5-14-02\":{cls:\"4BS\",lin:[{hi:[250,50],k:\"Versorgungsspannung\",lo:[0,0],sb:0,u:\"V\",w:8},{hi:[250,1e3],k:\"Beleuchtungsst\\xE4rke\",lo:[0,0],sb:8,u:\"lx\",w:8}],t:\"Multifunktionssensor, Single Input Contact (Window/Door), Versorgungsspannung monitor und Beleuchtungsst\\xE4rke\"},\"A5-14-03\":{cls:\"4BS\",lin:[{hi:[250,50],k:\"Versorgungsspannung\",lo:[0,0],sb:0,u:\"V\",w:8}],t:\"Multifunktionssensor, Single Input Contact (Window/Door), Versorgungsspannung monitor und Vibration\"},\"A5-14-04\":{cls:\"4BS\",lin:[{hi:[250,50],k:\"Versorgungsspannung\",lo:[0,0],sb:0,u:\"V\",w:8},{hi:[250,1e3],k:\"Beleuchtungsst\\xE4rke\",lo:[0,0],sb:8,u:\"lx\",w:8}],t:\"Multifunktionssensor, Single Input Contact (Window/Door), Versorgungsspannung monitor, Vibration und Beleuchtungsst\\xE4rke\"},\"A5-14-05\":{cls:\"4BS\",lin:[{hi:[250,5],k:\"Versorgungsspannung\",lo:[0,0],sb:0,u:\"V\",w:8}],t:\"Multifunktionssensor, Vibration/Tilt, Versorgungsspannung monitor\"},\"A5-14-06\":{cls:\"4BS\",lin:[{hi:[250,50],k:\"Versorgungsspannung\",lo:[0,0],sb:0,u:\"V\",w:8},{hi:[250,1e3],k:\"Beleuchtungsst\\xE4rke\",lo:[0,0],sb:8,u:\"lx\",w:8}],t:\"Multifunktionssensor, Vibration/Tilt, Beleuchtungsst\\xE4rke und Versorgungsspannung monitor\"},\"A5-14-07\":{cls:\"4BS\",t:\"Multifunktionssensor, Dual-door-contact mit States Open/Closed und Locked/Unlocked, Versorgungsspannung monitor\"},\"A5-14-08\":{cls:\"4BS\",t:\"Multifunktionssensor, Dual-door-contact mit States Open/Closed und Locked/Unlocked, Versorgungsspannung monitor und Vibration detection\"},\"A5-14-09\":{cls:\"4BS\",lin:[{hi:[14,11],k:\"Kontakt\",lo:[8,0],sb:24,w:8}],t:\"Multifunktionssensor, Window/Door-Contact mit States Open/Closed/Tilt, Versorgungsspannung monitor\"},\"A5-14-0A\":{cls:\"4BS\",t:\"Multifunktionssensor, Window/Door-Contact mit States Open/Closed/Tilt, Versorgungsspannung monitor\"},\"A5-20-01\":{cls:\"4BS\",lin:[{hi:[100,100],k:\"Istwert\",lo:[0,0],sb:0,w:8},{hi:[255,0],k:\"Temperatur (RCU)\",lo:[0,40],sb:8,w:8},{hi:[255,40],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"HLK-Komponenten, Batteriebetriebener Stellantrieb\"},\"A5-20-02\":{cls:\"4BS\",lin:[{hi:[100,100],k:\"Istwert\",lo:[0,0],sb:0,w:8},{hi:[100,100],k:\"Ventil-Sollwert\",lo:[0,0],sb:0,w:8}],t:\"HLK-Komponenten, Basic Actuator\"},\"A5-20-03\":{cls:\"4BS\",lin:[{hi:[100,100],k:\"Ventil-Iststellung\",lo:[0,0],sb:0,w:8},{hi:[255,0],k:\"Temperatur (RCU)\",lo:[0,40],sb:8,w:8},{hi:[255,40],k:\"Temperatur\",lo:[0,0],sb:16,u:\"\\xB0C\",w:8}],t:\"HLK-Komponenten, Line powered Actuator\"},\"A5-20-04\":{cls:\"4BS\",lin:[{hi:[100,100],k:\"Position\",lo:[0,0],sb:0,w:8},{hi:[100,100],k:\"Ventilposition\",lo:[0,0],sb:0,w:8},{hi:[255,80],k:\"Vorlauftemperatur / Temp.-Sollwert\",lo:[0,20],sb:8,w:8},{hi:[255,30],k:\"Temperatur-Sollwert\",lo:[0,10],sb:8,u:\"\\xB0C\",w:8}],t:\"HLK-Komponenten, Heating Radiator Valve Actuating Drive mit Feed und Room Temperatur Measurement, Local Sollwert Steuerung und Display\"},\"A5-20-06\":{cls:\"4BS\",t:\"HLK-Komponenten,Harvesting-powered actuator mit local temperature offset control \"},\"A5-30-01\":{cls:\"4BS\",t:\"Digitaleingang, Single Input Contact, Battery Monitor\"},\"A5-30-02\":{cls:\"4BS\",t:\"Digitaleingang, Single Input Contact\"},\"A5-30-03\":{cls:\"4BS\",lin:[{hi:[255,0],k:\"Temperatur\",lo:[0,40],sb:8,u:\"\\xB0C\",w:8}],t:\"Digitaleingang, 4 Digital Inputs, Wake und Temperatur\"},\"A5-30-04\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Digitaleingang\",lo:[0,0],sb:16,w:8}],t:\"Digitaleingang, 3 Digital Inputs, 1 Analog Input 8 Bits\"},\"A5-37-01\":{cls:\"4BS\",lin:[{hi:[255,255],k:\"Tempor\\xE4rer Sollwert\",lo:[0,0],sb:0,w:8},{hi:[255,3825],k:\"Timeout\",lo:[1,15],sb:16,u:\"min\",w:8}],t:\"Energiemanagement, Demand Response\"},\"A5-38-08\":{cls:\"4BS\",lin:[{hi:[65535,65535],k:\"Zeit\",lo:[1,1],sb:8,w:16},{hi:[255,100],k:\"Dimmwert\",lo:[0,0],sb:8,w:8},{hi:[255,255],k:\"Rampenzeit\",lo:[0,0],sb:16,w:8},{hi:[255,128],k:\"Sollwert\",lo:[0,-127],sb:16,w:8},{hi:[255,512],k:\"Basis-Sollwert\",lo:[0,0],sb:16,w:8},{hi:[255,100],k:\"Stellgr\\xF6\\xDFe (Override)\",lo:[0,0],sb:16,w:8}],t:\"Zentralkommando, Gateway\"},\"A5-3F-7F\":{cls:\"4BS\",t:\"Universal\"},\"D2-01-00\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-01\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-02\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-03\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-04\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-05\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-06\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-07\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-08\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-09\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-0A\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-0B\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-0C\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-0D\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-0F\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-10\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-11\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-01-12\":{cls:\"VLD\",t:\"Elektronische Schalter und Dimmer mit Energiemessung und lokaler Steuerung\"},\"D2-05-00\":{cls:\"VLD\",t:\"Jalousiesteuerung f\\xFCr Position und Winkel\"},\"D2-05-02\":{cls:\"VLD\",t:\"Jalousiesteuerung f\\xFCr Position und Winkel\"},\"D2-06-01\":{cls:\"VLD\",t:\"Multisensor-Fenstergriff, Alarm, Position Sensor, Vacation Mode, Optional Sensors\"},\"D2-14-40\":{cls:\"VLD\",t:\"Innentemperatur, Feuchte XYZ Acceleration, Beleuchtungsst\\xE4rke Sensor\"},\"D2-14-41\":{cls:\"VLD\",t:\"Innentemperatur, Feuchte XYZ Acceleration, Beleuchtungsst\\xE4rke Sensor, Window Contact\"},\"D2-14-52\":{cls:\"VLD\",t:\"Multifunktionssensoren\"},\"D2-14-54\":{cls:\"VLD\",t:\"Multifunktionssensoren, Leak Detector mit Temperatur und Feuchte Sensing\"},\"D2-15-00\":{cls:\"VLD\",t:\"Personen-Aktivit\\xE4tssensor\"},\"D2-32-00\":{cls:\"VLD\",lin:[{hi:[65520,4095],k:\"Strom\",lo:[0,0],sb:8,w:16}],t:\"AC-Stromzange, 1 channel\"},\"D2-32-01\":{cls:\"VLD\",t:\"AC-Stromzange, 2 channels\"},\"D2-32-02\":{cls:\"VLD\",t:\"AC-Stromzange, 3 channels\"},\"D2-40-00\":{cls:\"VLD\",t:\"LED-Controller-Status, Type 0x00\"},\"D2-40-01\":{cls:\"VLD\",t:\"LED-Controller-Status, Type 0x01\"},\"D2-A0-01\":{cls:\"VLD\",t:\"Standardventil, Valve Steuerung\"},\"D2-B1-00\":{cls:\"VLD\",t:\"Kanalnummer\"},\"D5-00-01\":{cls:\"1BS\",t:\"Kontakte und Schalter, Single Input Contact\"},\"F6-01-01\":{cls:\"RPS\",t:\"Drucktaster\"},\"F6-02-01\":{cls:\"RPS\",t:\"Wippschalter, 2 Wippe, Licht- und Jalousiesteuerung - Applikationsstil 1\"},\"F6-02-02\":{cls:\"RPS\",t:\"Wippschalter, 2 Wippe, Licht- und Jalousiesteuerung - Applikationsstil 10\"},\"F6-02-03\":{cls:\"RPS\",t:\"Wippschalter, 2 Wippe, Licht- und Jalousiesteuerung - Applikationsstil 11\"},\"F6-02-04\":{cls:\"RPS\",t:\"Wippschalter, 2 Wippe, Licht und blind control ERP2\"},\"F6-03-01\":{cls:\"RPS\",t:\"Wippschalter, 4 Wippe, Licht- und Jalousiesteuerung - Applikationsstil 1\"},\"F6-03-02\":{cls:\"RPS\",t:\"Wippschalter, 4 Wippe, Licht- und Jalousiesteuerung - Applikationsstil 2\"},\"F6-04-02\":{cls:\"RPS\",t:\"Positionsschalter, Home und Office Application, Key Card Activated Switch ERP2\"},\"F6-05-00\":{cls:\"RPS\",t:\"Melder \\u2013 Windgeschwindigkeits-Schwellenmelder\"},\"F6-05-01\":{cls:\"RPS\",t:\"Melder, Liquid Leakage Sensor (mechanic harvester)\"},\"F6-05-02\":{cls:\"RPS\",t:\"Melder, Smoke Detector\"},\"F6-10-00\":{cls:\"RPS\",t:\"Mechanischer Griff, Window Handle\"}};var v=[{key:\"DSZ14DRS|A5-12-01\",model:\"DSZ14DRS\",typ:\"Z\\xE4hler Strom\",eep:\"A5-12-01\"},{key:\"DSZ14WDRS|A5-12-01\",model:\"DSZ14WDRS\",typ:\"Z\\xE4hler Strom\",eep:\"A5-12-01\"},{key:\"F1FT65|F6-01-01\",model:\"F1FT65\",typ:\"RPS 1-fach Taster\",eep:\"F6-01-01\"},{key:\"F1T55E|F6-01-01\",model:\"F1T55E\",typ:\"RPS 1-fach Taster\",eep:\"F6-01-01\"},{key:\"F1T65|F6-01-01\",model:\"F1T65\",typ:\"RPS 1-fach Taster\",eep:\"F6-01-01\"},{key:\"F265B|F6-02-01\",model:\"F265B\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F2FT65|F6-02-01\",model:\"F2FT65\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F2FT65B|F6-02-01\",model:\"F2FT65B\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F2FZT65B|F6-02-01\",model:\"F2FZT65B\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F2T55E|F6-02-01\",model:\"F2T55E\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F2T55EB|F6-02-01\",model:\"F2T55EB\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F2T65|F6-02-01\",model:\"F2T65\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F2ZT55E|F6-02-01\",model:\"F2ZT55E\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F2ZT65|F6-02-01\",model:\"F2ZT65\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F3Z14D|A5-12-01\",model:\"F3Z14D\",typ:\"Z\\xE4hler Strom\",eep:\"A5-12-01\"},{key:\"F3Z14D|A5-12-02\",model:\"F3Z14D\",typ:\"Z\\xE4hler Gas\",eep:\"A5-12-02\"},{key:\"F3Z14D|A5-12-03\",model:\"F3Z14D\",typ:\"Z\\xE4hler Wasser\",eep:\"A5-12-03\"},{key:\"F4FT65|F6-02-01\",model:\"F4FT65\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F4FT65B|F6-02-01\",model:\"F4FT65B\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F4PT|F6-02-01\",model:\"F4PT\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F4T55B|F6-02-01\",model:\"F4T55B\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F4T55E|F6-02-01\",model:\"F4T55E\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F4T55EB|F6-02-01\",model:\"F4T55EB\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F4T65|F6-02-01\",model:\"F4T65\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F4T65B|F6-02-01\",model:\"F4T65B\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F4USM61B|A5-07-01\",model:\"F4USM61B\",typ:\"Bewegungsm.\",eep:\"A5-07-01\"},{key:\"F4USM61B|A5-08-01\",model:\"F4USM61B\",typ:\"FBH\",eep:\"A5-08-01\"},{key:\"F4USM61B|A5-38-08\",model:\"F4USM61B\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"F4USM61B|D5-00-01\",model:\"F4USM61B\",typ:\"Fensterkontakt\",eep:\"D5-00-01\"},{key:\"F4USM61B|F6-02-01\",model:\"F4USM61B\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F5PT55|F6-02-01\",model:\"F5PT55\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F6T55B|A5-07-01\",model:\"F6T55B\",typ:\"Bewegungsm.\",eep:\"A5-07-01\"},{key:\"F6T55B|F6-02-01\",model:\"F6T55B\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"F6T65B|A5-07-01\",model:\"F6T65B\",typ:\"Bewegungsm.\",eep:\"A5-07-01\"},{key:\"F6T65B|F6-02-01\",model:\"F6T65B\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FABH130|F6-02-01\",model:\"FABH130\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FABH65S|A5-08-01\",model:\"FABH65S\",typ:\"FBH\",eep:\"A5-08-01\"},{key:\"FAH60|A5-06-01\",model:\"FAH60\",typ:\"FAH60/FIH65S\",eep:\"A5-06-01\"},{key:\"FAH65S|A5-06-01\",model:\"FAH65S\",typ:\"FAH60/FIH65S\",eep:\"A5-06-01\"},{key:\"FASM60|F6-02-01\",model:\"FASM60\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FASWZ-16A|A5-12-01\",model:\"FASWZ-16A\",typ:\"Z\\xE4hler Strom\",eep:\"A5-12-01\"},{key:\"FB55B|A5-07-01\",model:\"FB55B\",typ:\"Bewegungsm.\",eep:\"A5-07-01\"},{key:\"FB55EB|A5-07-01\",model:\"FB55EB\",typ:\"Bewegungsm.\",eep:\"A5-07-01\"},{key:\"FB65B|A5-07-01\",model:\"FB65B\",typ:\"Bewegungsm.\",eep:\"A5-07-01\"},{key:\"FB65EB|A5-07-01\",model:\"FB65EB\",typ:\"Bewegungsm.\",eep:\"A5-07-01\"},{key:\"FBH55ESB|A5-07-01\",model:\"FBH55ESB\",typ:\"Bewegungsm.\",eep:\"A5-07-01\"},{key:\"FBH55ESB|A5-08-01\",model:\"FBH55ESB\",typ:\"FBH\",eep:\"A5-08-01\"},{key:\"FBH55SB|A5-07-01\",model:\"FBH55SB\",typ:\"Bewegungsm.\",eep:\"A5-07-01\"},{key:\"FBH55SB|A5-08-01\",model:\"FBH55SB\",typ:\"FBH\",eep:\"A5-08-01\"},{key:\"FBH65|A5-08-01\",model:\"FBH65\",typ:\"FBH\",eep:\"A5-08-01\"},{key:\"FBH65S|A5-08-01\",model:\"FBH65S\",typ:\"FBH\",eep:\"A5-08-01\"},{key:\"FBH65SB|A5-07-01\",model:\"FBH65SB\",typ:\"Bewegungsm.\",eep:\"A5-07-01\"},{key:\"FBH65SB|A5-08-01\",model:\"FBH65SB\",typ:\"FBH\",eep:\"A5-08-01\"},{key:\"FBH65TF|A5-04-01\",model:\"FBH65TF\",typ:\"Feuchte/Temp.\",eep:\"A5-04-01\"},{key:\"FBH65TF|A5-04-02\",model:\"FBH65TF\",typ:\"Feuchte/Temp.\",eep:\"A5-04-02\"},{key:\"FBH65TF|A5-08-01\",model:\"FBH65TF\",typ:\"FBH\",eep:\"A5-08-01\"},{key:\"FBHF65SB|A5-07-01\",model:\"FBHF65SB\",typ:\"Bewegungsm.\",eep:\"A5-07-01\"},{key:\"FBHF65SB|A5-08-01\",model:\"FBHF65SB\",typ:\"FBH\",eep:\"A5-08-01\"},{key:\"FCO2TF65|A5-09-04\",model:\"FCO2TF65\",typ:\"CO2/Feuchte/Temp\",eep:\"A5-09-04\"},{key:\"FCO2TS|A5-09-04\",model:\"FCO2TS\",typ:\"CO2/Feuchte/Temp\",eep:\"A5-09-04\"},{key:\"FDT55B|A5-38-08\",model:\"FDT55B\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FDT55EB|A5-38-08\",model:\"FDT55EB\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FDT65B|A5-38-08\",model:\"FDT65B\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FDTF65B|A5-38-08\",model:\"FDTF65B\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FET55E|F6-01-01\",model:\"FET55E\",typ:\"RPS 1-fach Taster\",eep:\"F6-01-01\"},{key:\"FF8|F6-02-01\",model:\"FF8\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FFD|A5-38-08\",model:\"FFD\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FFD|F6-02-01\",model:\"FFD\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FFG7B|A5-14-09\",model:\"FFG7B\",typ:\"FFG7B Fenstergriff\",eep:\"A5-14-09\"},{key:\"FFG7B|F6-10-00\",model:\"FFG7B\",typ:\"Fenstergriff\",eep:\"F6-10-00\"},{key:\"FFGB-hg|A5-14-01\",model:\"FFGB-hg\",typ:\"FFGB-hg Fenstersensor\",eep:\"A5-14-01\"},{key:\"FFGB-hg|A5-14-03\",model:\"FFGB-hg\",typ:\"FFGB-hg Fenstersensor\",eep:\"A5-14-03\"},{key:\"FFGB-hg|A5-14-07\",model:\"FFGB-hg\",typ:\"FFGB-hg Fenstersensor\",eep:\"A5-14-07\"},{key:\"FFGB-hg|A5-14-08\",model:\"FFGB-hg\",typ:\"FFGB-hg Fenstersensor\",eep:\"A5-14-08\"},{key:\"FFGB-hg|A5-14-09\",model:\"FFGB-hg\",typ:\"FFG7B Fenstergriff\",eep:\"A5-14-09\"},{key:\"FFGB-hg|A5-14-0A\",model:\"FFGB-hg\",typ:\"FTKB Fenstergriff\",eep:\"A5-14-0A\"},{key:\"FFGB-hg|F6-10-00\",model:\"FFGB-hg\",typ:\"Fenstergriff\",eep:\"F6-10-00\"},{key:\"FFKB|D5-00-01\",model:\"FFKB\",typ:\"Fensterkontakt\",eep:\"D5-00-01\"},{key:\"FFT55B|A5-04-02\",model:\"FFT55B\",typ:\"Feuchte/Temp.\",eep:\"A5-04-02\"},{key:\"FFT55B|A5-04-03\",model:\"FFT55B\",typ:\"Feuchte/Temp.\",eep:\"A5-04-03\"},{key:\"FFT55EB|A5-04-02\",model:\"FFT55EB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-02\"},{key:\"FFT55EB|A5-04-03\",model:\"FFT55EB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-03\"},{key:\"FFT60SB|A5-04-02\",model:\"FFT60SB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-02\"},{key:\"FFT60SB|A5-04-03\",model:\"FFT60SB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-03\"},{key:\"FFT65B|A5-04-02\",model:\"FFT65B\",typ:\"Feuchte/Temp.\",eep:\"A5-04-02\"},{key:\"FFT65B|A5-04-03\",model:\"FFT65B\",typ:\"Feuchte/Temp.\",eep:\"A5-04-03\"},{key:\"FFTE|F6-10-00\",model:\"FFTE\",typ:\"Fenstergriff\",eep:\"F6-10-00\"},{key:\"FFTF65B|A5-04-02\",model:\"FFTF65B\",typ:\"Feuchte/Temp.\",eep:\"A5-04-02\"},{key:\"FFTF65B|A5-04-03\",model:\"FFTF65B\",typ:\"Feuchte/Temp.\",eep:\"A5-04-03\"},{key:\"FHD60SB|A5-06-01\",model:\"FHD60SB\",typ:\"FAH60/FIH65S\",eep:\"A5-06-01\"},{key:\"FHD60SB|A5-38-08\",model:\"FHD60SB\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FHD65SB|A5-06-02\",model:\"FHD65SB\",typ:\"D\\xE4mmerungssch.\",eep:\"A5-06-02\"},{key:\"FHM2|F6-02-01\",model:\"FHM2\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FHMB|A5-30-03\",model:\"FHMB\",typ:\"Wasser/Rauch/Hitze\",eep:\"A5-30-03\"},{key:\"FHS2|F6-02-01\",model:\"FHS2\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FHS4|F6-02-01\",model:\"FHS4\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FIH65B|A5-06-02\",model:\"FIH65B\",typ:\"D\\xE4mmerungssch.\",eep:\"A5-06-02\"},{key:\"FIH65S|A5-06-01\",model:\"FIH65S\",typ:\"FAH60/FIH65S\",eep:\"A5-06-01\"},{key:\"FKD|F6-01-01\",model:\"FKD\",typ:\"RPS 1-fach Taster\",eep:\"F6-01-01\"},{key:\"FKF65|F6-02-01\",model:\"FKF65\",typ:\"Kartenschalter\",eep:\"F6-02-01\"},{key:\"FKS|A5-20-01\",model:\"FKS\",typ:\"Kleinstellantrieb\",eep:\"A5-20-01\"},{key:\"FKS-H|A5-20-04\",model:\"FKS-H\",typ:\"Kleinstellantrieb\",eep:\"A5-20-04\"},{key:\"FKS-SV|A5-20-01\",model:\"FKS-SV\",typ:\"Kleinstellantrieb\",eep:\"A5-20-01\"},{key:\"FLGTF55|A5-04-02\",model:\"FLGTF55\",typ:\"Feuchte/Temp.\",eep:\"A5-04-02\"},{key:\"FLGTF55|A5-09-0C\",model:\"FLGTF55\",typ:\"Luftg\\xFCte\",eep:\"A5-09-0C\"},{key:\"FLGTF55E|A5-04-02\",model:\"FLGTF55E\",typ:\"Feuchte/Temp.\",eep:\"A5-04-02\"},{key:\"FLGTF55E|A5-09-0C\",model:\"FLGTF55E\",typ:\"Luftg\\xFCte\",eep:\"A5-09-0C\"},{key:\"FLGTF65|A5-04-02\",model:\"FLGTF65\",typ:\"Feuchte/Temp.\",eep:\"A5-04-02\"},{key:\"FLGTF65|A5-09-0C\",model:\"FLGTF65\",typ:\"Luftg\\xFCte\",eep:\"A5-09-0C\"},{key:\"FLT58|A5-04-02\",model:\"FLT58\",typ:\"Feuchte/Temp.\",eep:\"A5-04-02\"},{key:\"FLT58|A5-09-05\",model:\"FLT58\",typ:\"VOC\",eep:\"A5-09-05\"},{key:\"FMH1W|F6-01-01\",model:\"FMH1W\",typ:\"RPS 1-fach Taster\",eep:\"F6-01-01\"},{key:\"FMH2S|F6-02-01\",model:\"FMH2S\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FMH4|F6-02-01\",model:\"FMH4\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FMH4S|F6-02-01\",model:\"FMH4S\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FMH8|F6-02-01\",model:\"FMH8\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FMMS44SB|A5-02-05\",model:\"FMMS44SB\",typ:\"Temp.F\\xFChler\",eep:\"A5-02-05\"},{key:\"FMMS44SB|A5-04-01\",model:\"FMMS44SB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-01\"},{key:\"FMMS44SB|A5-04-03\",model:\"FMMS44SB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-03\"},{key:\"FMMS44SB|A5-06-02\",model:\"FMMS44SB\",typ:\"D\\xE4mmerungssch.\",eep:\"A5-06-02\"},{key:\"FMMS44SB|A5-06-03\",model:\"FMMS44SB\",typ:\"D\\xE4mmerungssch.\",eep:\"A5-06-03\"},{key:\"FMMS44SB|A5-14-05\",model:\"FMMS44SB\",typ:\"Fenstersensor\",eep:\"A5-14-05\"},{key:\"FMMS44SB|D2-00-01\",model:\"FMMS44SB\",typ:\"Room Control Panel\",eep:\"D2-00-01\"},{key:\"FMMS44SB|D2-14-40\",model:\"FMMS44SB\",typ:\"Multisensor\",eep:\"D2-14-40\"},{key:\"FMMS44SB|D2-14-41\",model:\"FMMS44SB\",typ:\"Multisensor\",eep:\"D2-14-41\"},{key:\"FMMS44SB|D5-00-01\",model:\"FMMS44SB\",typ:\"Fensterkontakt\",eep:\"D5-00-01\"},{key:\"FMP3|A5-FF-7F\",model:\"FMP3\",typ:\"Direktansteuerung\",eep:\"A5-FF-7F\"},{key:\"FMS55ESB|A5-02-05\",model:\"FMS55ESB\",typ:\"Temp.F\\xFChler\",eep:\"A5-02-05\"},{key:\"FMS55ESB|A5-04-01\",model:\"FMS55ESB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-01\"},{key:\"FMS55ESB|A5-04-03\",model:\"FMS55ESB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-03\"},{key:\"FMS55ESB|A5-06-02\",model:\"FMS55ESB\",typ:\"D\\xE4mmerungssch.\",eep:\"A5-06-02\"},{key:\"FMS55ESB|A5-06-03\",model:\"FMS55ESB\",typ:\"D\\xE4mmerungssch.\",eep:\"A5-06-03\"},{key:\"FMS55ESB|A5-14-05\",model:\"FMS55ESB\",typ:\"Fenstersensor\",eep:\"A5-14-05\"},{key:\"FMS55ESB|D2-14-40\",model:\"FMS55ESB\",typ:\"Multisensor\",eep:\"D2-14-40\"},{key:\"FMS55ESB|D2-14-41\",model:\"FMS55ESB\",typ:\"Multisensor\",eep:\"D2-14-41\"},{key:\"FMS55SB|A5-02-05\",model:\"FMS55SB\",typ:\"Temp.F\\xFChler\",eep:\"A5-02-05\"},{key:\"FMS55SB|A5-04-01\",model:\"FMS55SB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-01\"},{key:\"FMS55SB|A5-04-03\",model:\"FMS55SB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-03\"},{key:\"FMS55SB|A5-06-02\",model:\"FMS55SB\",typ:\"D\\xE4mmerungssch.\",eep:\"A5-06-02\"},{key:\"FMS55SB|A5-06-03\",model:\"FMS55SB\",typ:\"D\\xE4mmerungssch.\",eep:\"A5-06-03\"},{key:\"FMS55SB|A5-14-05\",model:\"FMS55SB\",typ:\"Fenstersensor\",eep:\"A5-14-05\"},{key:\"FMS55SB|D2-14-40\",model:\"FMS55SB\",typ:\"Multisensor\",eep:\"D2-14-40\"},{key:\"FMS55SB|D2-14-41\",model:\"FMS55SB\",typ:\"Multisensor\",eep:\"D2-14-41\"},{key:\"FMS65ESB|A5-02-05\",model:\"FMS65ESB\",typ:\"Temp.F\\xFChler\",eep:\"A5-02-05\"},{key:\"FMS65ESB|A5-04-01\",model:\"FMS65ESB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-01\"},{key:\"FMS65ESB|A5-04-03\",model:\"FMS65ESB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-03\"},{key:\"FMS65ESB|A5-06-02\",model:\"FMS65ESB\",typ:\"D\\xE4mmerungssch.\",eep:\"A5-06-02\"},{key:\"FMS65ESB|A5-06-03\",model:\"FMS65ESB\",typ:\"D\\xE4mmerungssch.\",eep:\"A5-06-03\"},{key:\"FMS65ESB|A5-14-05\",model:\"FMS65ESB\",typ:\"Fenstersensor\",eep:\"A5-14-05\"},{key:\"FMS65ESB|D2-14-40\",model:\"FMS65ESB\",typ:\"Multisensor\",eep:\"D2-14-40\"},{key:\"FMS65ESB|D2-14-41\",model:\"FMS65ESB\",typ:\"Multisensor\",eep:\"D2-14-41\"},{key:\"FNS55B|F6-01-01\",model:\"FNS55B\",typ:\"RPS 1-fach Taster\",eep:\"F6-01-01\"},{key:\"FNS55EB|F6-01-01\",model:\"FNS55EB\",typ:\"RPS 1-fach Taster\",eep:\"F6-01-01\"},{key:\"FNS65EB|F6-01-01\",model:\"FNS65EB\",typ:\"RPS 1-fach Taster\",eep:\"F6-01-01\"},{key:\"FNSN55EB|F6-02-01\",model:\"FNSN55EB\",typ:\"N\\xE4herungssensor (NanoPower)\",eep:\"F6-02-01\"},{key:\"FPE-1|F6-01-01\",model:\"FPE-1\",typ:\"RPS 1-fach Taster\",eep:\"F6-01-01\"},{key:\"FRW|F6-02-01\",model:\"FRW\",typ:\"RPS Rauchmelder\",eep:\"F6-02-01\"},{key:\"FRWB|A5-30-03\",model:\"FRWB\",typ:\"Wasser/Rauch/Hitze\",eep:\"A5-30-03\"},{key:\"FSDG14|A5-12-01\",model:\"FSDG14\",typ:\"Z\\xE4hler Strom\",eep:\"A5-12-01\"},{key:\"FSM14|F6-02-01\",model:\"FSM14\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FSM60B|A5-30-01\",model:\"FSM60B\",typ:\"Wassermelder\",eep:\"A5-30-01\"},{key:\"FSM60B|A5-30-03\",model:\"FSM60B\",typ:\"Wasser/Rauch/Hitze\",eep:\"A5-30-03\"},{key:\"FSM60B|F6-02-01\",model:\"FSM60B\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FSM61|F6-02-01\",model:\"FSM61\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FSMTB|F6-02-01\",model:\"FSMTB\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FSR61VA|A5-12-01\",model:\"FSR61VA\",typ:\"Z\\xE4hler Strom\",eep:\"A5-12-01\"},{key:\"FSTAP|F6-02-01\",model:\"FSTAP\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FSU55D|A5-13-04\",model:\"FSU55D\",typ:\"Zeit + Tag\",eep:\"A5-13-04\"},{key:\"FSU55D|A5-38-08\",model:\"FSU55D\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FSU55D|F6-02-01\",model:\"FSU55D\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FSU55ED|A5-13-04\",model:\"FSU55ED\",typ:\"Zeit + Tag\",eep:\"A5-13-04\"},{key:\"FSU55ED|A5-38-08\",model:\"FSU55ED\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FSU55ED|F6-02-01\",model:\"FSU55ED\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FSU65D|A5-13-04\",model:\"FSU65D\",typ:\"Zeit + Tag\",eep:\"A5-13-04\"},{key:\"FSU65D|A5-38-08\",model:\"FSU65D\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FSU65D|F6-02-01\",model:\"FSU65D\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FSVA-230v|A5-12-01\",model:\"FSVA-230v\",typ:\"Z\\xE4hler Strom\",eep:\"A5-12-01\"},{key:\"FT4F|F6-02-01\",model:\"FT4F\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FT55|F6-02-01\",model:\"FT55\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FTAF55D|A5-10-06\",model:\"FTAF55D\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FTAF55D|F2-02-01\",model:\"FTAF55D\",typ:\"RPS 4-fach Taster\",eep:\"F2-02-01\"},{key:\"FTAF55ED|A5-10-06\",model:\"FTAF55ED\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FTAF65D|A5-10-06\",model:\"FTAF65D\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FTAF65D|A5-10-06#2\",model:\"FTAF65D\",typ:\"Temp.-Regler m. Schalter\",eep:\"A5-10-06\"},{key:\"FTAF65D|F2-02-01\",model:\"FTAF65D\",typ:\"RPS 4-fach Taster\",eep:\"F2-02-01\"},{key:\"FTF65S|A5-02-05\",model:\"FTF65S\",typ:\"Temp.F\\xFChler\",eep:\"A5-02-05\"},{key:\"FTFB|A5-04-02\",model:\"FTFB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-02\"},{key:\"FTFB|A5-04-03\",model:\"FTFB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-03\"},{key:\"FTFSB|A5-04-02\",model:\"FTFSB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-02\"},{key:\"FTFSB|A5-04-03\",model:\"FTFSB\",typ:\"Feuchte/Temp.\",eep:\"A5-04-03\"},{key:\"FTK|D5-00-01\",model:\"FTK\",typ:\"Fensterkontakt\",eep:\"D5-00-01\"},{key:\"FTKB-GR|D5-00-01\",model:\"FTKB-GR\",typ:\"Fensterkontakt\",eep:\"D5-00-01\"},{key:\"FTKB-hg|A5-14-0A\",model:\"FTKB-hg\",typ:\"FTKB Fenstergriff\",eep:\"A5-14-0A\"},{key:\"FTKB-wg|D5-00-01\",model:\"FTKB-wg\",typ:\"Fensterkontakt\",eep:\"D5-00-01\"},{key:\"FTKE|F6-10-00\",model:\"FTKE\",typ:\"Fenstergriff\",eep:\"F6-10-00\"},{key:\"FTR55DSB|A5-10-06\",model:\"FTR55DSB\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FTR55DSB|A5-38-08\",model:\"FTR55DSB\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FTR55HB|A5-10-06\",model:\"FTR55HB\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FTR55HB|A5-38-08\",model:\"FTR55HB\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FTR55SB|A5-10-06\",model:\"FTR55SB\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FTR55SB|A5-38-08\",model:\"FTR55SB\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FTR65DSB|A5-10-06\",model:\"FTR65DSB\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FTR65DSB|A5-38-08\",model:\"FTR65DSB\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FTR65EHB|A5-10-06\",model:\"FTR65EHB\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FTR65EHB|A5-38-08\",model:\"FTR65EHB\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FTR65ESB|A5-10-06\",model:\"FTR65ESB\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FTR65ESB|A5-38-08\",model:\"FTR65ESB\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FTR65HB|A5-10-06\",model:\"FTR65HB\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FTR65HB|A5-38-08\",model:\"FTR65HB\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FTR65HS|A5-10-06\",model:\"FTR65HS\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FTR65HS|A5-10-06#2\",model:\"FTR65HS\",typ:\"Temp.-Regler m. Schalter\",eep:\"A5-10-06\"},{key:\"FTR65SB|A5-10-06\",model:\"FTR65SB\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FTR65SB|A5-38-08\",model:\"FTR65SB\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FTR78S|A5-10-03\",model:\"FTR78S\",typ:\"Temp.-Sensor\",eep:\"A5-10-03\"},{key:\"FTR86B|A5-10-06\",model:\"FTR86B\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FTRF65HB|A5-10-06\",model:\"FTRF65HB\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FTRF65HB|A5-38-08\",model:\"FTRF65HB\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FTRF65SB|A5-10-06\",model:\"FTRF65SB\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FTRF65SB|A5-38-08\",model:\"FTRF65SB\",typ:\"Software/Drehtaster\",eep:\"A5-38-08\"},{key:\"FTS14EM|A5-08-01\",model:\"FTS14EM\",typ:\"FBH\",eep:\"A5-08-01\"},{key:\"FTS14EM|D5-00-01\",model:\"FTS14EM\",typ:\"Fensterkontakt\",eep:\"D5-00-01\"},{key:\"FTS14EM|F6-02-01\",model:\"FTS14EM\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"FTTB|A5-07-01\",model:\"FTTB\",typ:\"Bewegungsm.\",eep:\"A5-07-01\"},{key:\"FUTH55D|A5-10-06\",model:\"FUTH55D\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FUTH55D|A5-10-12\",model:\"FUTH55D\",typ:\"Feuchte/Temp\",eep:\"A5-10-12\"},{key:\"FUTH55ED|A5-10-06\",model:\"FUTH55ED\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FUTH55ED|A5-10-12\",model:\"FUTH55ED\",typ:\"Feuchte/Temp\",eep:\"A5-10-12\"},{key:\"FUTH65D|A5-10-06\",model:\"FUTH65D\",typ:\"Temp.-Regler\",eep:\"A5-10-06\"},{key:\"FUTH65D|A5-10-12\",model:\"FUTH65D\",typ:\"Feuchte/Temp\",eep:\"A5-10-12\"},{key:\"FWS61|A5-13-01\",model:\"FWS61\",typ:\"Wetterdaten\",eep:\"A5-13-01\"},{key:\"FWS61|A5-13-02\",model:\"FWS61\",typ:\"Sonnendaten\",eep:\"A5-13-02\"},{key:\"FWS61|F6-05-01\",model:\"FWS61\",typ:\"FWS61 Drahtbruch\",eep:\"F6-05-01\"},{key:\"FWS81|F6-02-01\",model:\"FWS81\",typ:\"Kartenschalter\",eep:\"F6-02-01\"},{key:\"FWZ12|A5-12-01\",model:\"FWZ12\",typ:\"Z\\xE4hler Strom\",eep:\"A5-12-01\"},{key:\"FWZ14|A5-12-01\",model:\"FWZ14\",typ:\"Z\\xE4hler Strom\",eep:\"A5-12-01\"},{key:\"FZS65|F6-02-01\",model:\"FZS65\",typ:\"RPS Rauchmelder\",eep:\"F6-02-01\"},{key:\"FZT55|F6-02-01\",model:\"FZT55\",typ:\"RPS 4-fach Taster\",eep:\"F6-02-01\"},{key:\"ungekl\\xE4rt|A5-10-03\",model:\"ungekl\\xE4rt\",typ:\"Temp.-Sensor\",eep:\"A5-10-03\"}];var re='<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M1 12s4-8 11-8 11 8 11 8-4 8-11 8S1 12 1 12z\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/></svg>',_='<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M17.94 17.94A10.94 10.94 0 0 1 12 20c-7 0-11-8-11-8a19.4 19.4 0 0 1 5.06-5.94\"/><path d=\"M9.9 4.24A11 11 0 0 1 12 4c7 0 11 8 11 8a19.3 19.3 0 0 1-2.16 3.19\"/><path d=\"M14.12 14.12a3 3 0 1 1-4.24-4.24\"/><line x1=\"1\" y1=\"1\" x2=\"23\" y2=\"23\"/></svg>';function s(e){let t=document.getElementById(e);if(!t)throw new Error(`#${e} not found`);return t}function a(e){s(\"status\").textContent=e}function se(){return window.location.hostname}function H(e){document.querySelectorAll(\"nav.tabs button\").forEach(t=>{t.classList.toggle(\"active\",t.dataset.tab===e)}),document.querySelectorAll(\".tab\").forEach(t=>{t.classList.toggle(\"active\",t.id===`tab-${e}`)}),location.hash!==`#${e}`&&history.replaceState(null,\"\",`#${e}`)}function L(){return document.querySelector(\"nav.tabs button.active\")?.dataset.tab??\"\"}function he(){document.querySelectorAll(\"nav.tabs button\").forEach(t=>{t.addEventListener(\"click\",()=>H(t.dataset.tab))});let e=location.hash.replace(\"#\",\"\");e&&document.getElementById(`tab-${e}`)&&H(e),window.addEventListener(\"hashchange\",()=>{let t=location.hash.replace(\"#\",\"\");t&&document.getElementById(`tab-${t}`)&&H(t)})}function Se(){document.querySelectorAll(\"input[data-eye]\").forEach(e=>{let t=document.createElement(\"div\");t.className=\"pw-wrap\",e.parentNode.insertBefore(t,e),t.appendChild(e);let n=document.createElement(\"button\");n.type=\"button\",n.className=\"pw-eye\",n.setAttribute(\"aria-label\",\"Passwort anzeigen\"),n.innerHTML=_,t.appendChild(n),n.addEventListener(\"click\",()=>{let r=e.type===\"password\";e.type=r?\"text\":\"password\",n.innerHTML=r?re:_,n.setAttribute(\"aria-label\",r?\"Passwort verbergen\":\"Passwort anzeigen\")})})}var b=class{constructor(t){this.host=t;this.value=\"\";this.revealed=!1;this.host.innerHTML='<span class=\"val\"></span><button type=\"button\" class=\"pw-eye\" aria-label=\"anzeigen\"></button>',this.valueEl=this.host.querySelector(\".val\"),this.btn=this.host.querySelector(\".pw-eye\"),this.btn.addEventListener(\"click\",()=>{this.revealed=!this.revealed,this.render()}),this.render()}set(t){this.value=t,this.render()}render(){this.value?this.revealed?this.valueEl.textContent=this.value:this.valueEl.textContent=\"\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\":this.valueEl.textContent=\"\\u2014\",this.btn.innerHTML=this.revealed?re:_,this.btn.setAttribute(\"aria-label\",this.revealed?\"verbergen\":\"anzeigen\")}};async function m(e,t){let n=await fetch(e,t);if(!n.ok)throw new Error(`${n.status}: ${await n.text()}`);return await n.json()}var d={state:()=>m(\"/api/state\"),scan:()=>m(\"/api/scan\"),clients:()=>m(\"/api/clients\"),stats:()=>m(\"/api/stats\"),console:e=>m(`/api/console?since=${e}`),events:e=>m(`/api/events?since=${e}`),save:e=>m(\"/api/config\",{method:\"POST\",headers:{\"content-type\":\"application/json\"},body:JSON.stringify(e)}),regenToken:()=>m(\"/api/regen-token\",{method:\"POST\"}),regenOtaToken:()=>m(\"/api/regen-ota-token\",{method:\"POST\"}),factoryReset:()=>m(\"/api/factory-reset\",{method:\"POST\"}),reboot:()=>m(\"/api/reboot\",{method:\"POST\"}),baseIdRead:()=>m(\"/api/baseid\",{method:\"GET\"}),baseIdWrite:e=>m(\"/api/baseid\",{method:\"POST\",headers:{\"content-type\":\"application/json\"},body:JSON.stringify({base_id:e})})},ge=[[\"Europe/Berlin (Amsterdam, Paris, Rom, Madrid)\",\"CET-1CEST,M3.5.0,M10.5.0/3\"],[\"Europe/London (Dublin, Lissabon)\",\"GMT0BST,M3.5.0/1,M10.5.0\"],[\"Europe/Athen (Helsinki, Bukarest)\",\"EET-2EEST,M3.5.0/3,M10.5.0/4\"],[\"Europe/Moskau\",\"MSK-3\"],[\"UTC\",\"UTC0\"],[\"America/New York\",\"EST5EDT,M3.2.0,M11.1.0\"],[\"America/Chicago\",\"CST6CDT,M3.2.0,M11.1.0\"],[\"America/Denver\",\"MST7MDT,M3.2.0,M11.1.0\"],[\"America/Los Angeles\",\"PST8PDT,M3.2.0,M11.1.0\"],[\"America/Sao Paulo\",\"<-03>3\"],[\"Asia/Dubai\",\"<+04>-4\"],[\"Asia/Kolkata (Indien)\",\"IST-5:30\"],[\"Asia/Shanghai (China)\",\"CST-8\"],[\"Asia/Tokio\",\"JST-9\"],[\"Australia/Sydney\",\"AEST-10AEDT,M10.1.0,M4.1.0/3\"]];function Te(){let e=s(\"tz\");e.innerHTML=\"\";for(let[t,n]of ge){let r=document.createElement(\"option\");r.value=n,r.textContent=t,e.appendChild(r)}}function ye(e){let t=s(\"tz\");if(e&&!Array.from(t.options).some(n=>n.value===e)){let n=document.createElement(\"option\");n.value=e,n.textContent=`Eigene (${e})`,t.appendChild(n)}t.value=e||\"CET-1CEST,M3.5.0,M10.5.0/3\"}function F(e){let t=[\"B\",\"KB\",\"MB\",\"GB\"],n=0;for(;e>=1024&&n<t.length-1;)e/=1024,n++;return`${e.toFixed(n?1:0)} ${t[n]}`}function oe(e){let t=Math.floor(e/1e3);if(t<60)return`${t}s`;let n=Math.floor(t/60);return n<60?`${n}m${t%60}s`:`${Math.floor(n/60)}h${n%60}m`}function u(e){return e.replace(/[&<>\"']/g,t=>{switch(t){case\"&\":return\"&amp;\";case\"<\":return\"&lt;\";case\">\":return\"&gt;\";case'\"':return\"&quot;\";case\"'\":return\"&#39;\";default:return t}})}var G,le,U,K;async function ke(){try{let e=await d.state();s(\"ssid\").value=e.wifi_ssid||\"\",s(\"pass\").value=e.wifi_pass||\"\",s(\"tcp_en\").checked=e.tcp_enabled,s(\"tcp_port\").value=String(e.tcp_port),s(\"tcp_auth\").checked=e.tcp_auth_required,s(\"usb_en\").checked=e.usb_enabled,G.set(e.tcp_token),le.set(e.admin_pass),s(\"api_en\").checked=e.api_enabled,U.set(e.tcp_token),K.set(e.ota_token),s(\"dev_name\").value=e.device_name||\"\",s(\"admin_user\").value=e.admin_user||\"admin\",s(\"ntp_server\").value=e.ntp_server||\"pool.ntp.org\",ye(e.tz),s(\"fw_info\").textContent=`Version  : ${e.fw_version}  (Build ${e.fw_build})\n"
"Git      : ${e.fw_git}\n"
"Datum    : ${e.fw_date}\n"
"Partition: ${e.fw_part}`;let t=document.querySelector(\"header h1\");t&&e.device_name&&(t.textContent=e.device_name),e.device_name&&(document.title=e.device_name),ae(e.tcp_token,e.api_enabled),!e.tcp_auth_required&&e.tcp_enabled&&ie(),a(`Modus: ${e.mode} \\xB7 MAC-Suffix ${e.suffix}`)}catch(e){a(`Fehler: ${e instanceof Error?e.message:String(e)}`)}}async function Z(){a(\"scanne WLAN...\");try{let e=await d.scan(),t=s(\"ssid_sel\");t.innerHTML='<option value=\"\">-- Netzwerk waehlen --</option>',e.forEach(n=>{let r=document.createElement(\"option\");r.value=n.ssid,r.textContent=`${n.ssid} (${n.rssi} dBm${n.auth?\", \"+n.auth:\"\"})`,t.appendChild(r)}),t.onchange=()=>{s(\"ssid\").value=t.value},a(`${e.length} Netze gefunden`)}catch(e){a(`Scan-Fehler: ${e instanceof Error?e.message:String(e)}`)}}async function z(){try{let e=await d.regenToken();G.set(e.token),U.set(e.token),ae(e.token,s(\"api_en\").checked),a(\"neuer Token\")}catch(e){a(`Fehler: ${e instanceof Error?e.message:String(e)}`)}}async function Ae(){try{let e=await d.regenOtaToken();K.set(e.token),a(\"neuer OTA-Token\")}catch(e){a(`Fehler: ${e instanceof Error?e.message:String(e)}`)}}async function Be(){let e=s(\"baseid_info\");e.textContent=\"lese ...\";try{let t=await d.baseIdRead();s(\"baseid_in\").value=t.base_id,e.textContent=t.writes_remaining!==void 0?`Base-ID: ${t.base_id} \\xB7 noch ${t.writes_remaining} Schreibzugriffe`:`Base-ID: ${t.base_id}`,a(\"Base-ID gelesen\")}catch(t){e.textContent=`Fehler: ${t instanceof Error?t.message:String(t)}`}}async function be(){let e=s(\"baseid_in\").value.trim().toUpperCase();if(!/^FF-?[0-9A-F]{2}-?[0-9A-F]{2}-?[0-9A-F]{2}$/.test(e)){a(\"Base-ID-Format: FF-xx-xx-xx (Hex, beginnt mit FF)\");return}if(!confirm(\"Base-ID wirklich schreiben? Der TCM515 erlaubt nur rund 10 Schreibvorg\\xE4nge insgesamt.\"))return;let t=s(\"baseid_info\");t.textContent=\"schreibe ...\";try{let n=await d.baseIdWrite(e);s(\"baseid_in\").value=n.base_id,t.textContent=n.writes_remaining!==void 0?`Neue Base-ID: ${n.base_id} \\xB7 noch ${n.writes_remaining} Schreibzugriffe`:`Neue Base-ID: ${n.base_id}`,a(\"Base-ID geschrieben\")}catch(n){t.textContent=`Fehler: ${n instanceof Error?n.message:String(n)}`}}function fe(){s(\"tcp_en\").checked=!0,s(\"tcp_port\").value=\"5100\",s(\"tcp_auth\").checked=!1,ie(),a(\"HA-Eltako Preset gesetzt \\xB7 nicht vergessen zu speichern\")}function ie(){let e=se(),t=parseInt(s(\"tcp_port\").value,10)||5100,n=`eltako:\n"
"  gateway:\n"
"    - id: 1\n"
"      device_type: eul_lan\n"
"      serial_path: ${e}\n"
"      port: ${t}\n"
"      base_id: FF-AA-00-00     # anpassen: base_id des TCM515\n"
"`;s(\"ha_yaml\").textContent=n,s(\"ha_yaml_box\").style.display=\"block\"}function ae(e,t){let n=se();s(\"api_doc\").textContent=(t?\"\":`# API ist derzeit deaktiviert\n"
"\n"
"`)+`GET  http://${n}/api/telegrams\n"
"     Header: Authorization: Bearer ${e}\n"
"     -> letzte empfangene Telegramme (JSON-Array)\n"
"\n"
"POST http://${n}/api/send\n"
"     Header: Authorization: Bearer ${e}\n"
"     Body:   {\"hex\":\"55....\"}   (kompletter ESP3-Frame)\n"
"\n"
"Beispiel:\n"
"curl -H \"Authorization: Bearer ${e}\" http://${n}/api/telegrams`}async function we(){let e={tcp_enabled:s(\"tcp_en\").checked,tcp_port:parseInt(s(\"tcp_port\").value,10)||5100,tcp_auth_required:s(\"tcp_auth\").checked,usb_enabled:s(\"usb_en\").checked,api_enabled:s(\"api_en\").checked,device_name:s(\"dev_name\").value.trim(),admin_user:s(\"admin_user\").value.trim(),ntp_server:s(\"ntp_server\").value.trim(),tz:s(\"tz\").value},t=s(\"admin_pass_new\").value;if(t){if(t.length<8){a(\"Neues Portal-Passwort braucht min. 8 Zeichen\");return}e.admin_pass=t}let n=s(\"ssid\").value.trim(),r=s(\"pass\").value;if(n&&r)e.wifi_ssid=n,e.wifi_pass=r;else if((n||r)&&!confirm(\"WLAN-Zugang bleibt unveraendert (nur SSID oder Passwort eingetragen). Fortfahren?\"))return;try{await d.save(e),a(\"gespeichert \\u2014 Neustart noetig fuer WLAN/TCP/Name/Zeitzone\")}catch(o){a(`Fehler: ${o instanceof Error?o.message:String(o)}`)}}async function Ee(){if(confirm(\"Geraet jetzt neu starten? Die Verbindung wird kurz getrennt.\"))try{await d.reboot(),a(\"Neustart ausgeloest ...\")}catch(e){a(`Fehler: ${e instanceof Error?e.message:String(e)}`)}}async function De(e){let t=Date.now();for(await new Promise(n=>setTimeout(n,3e3));Date.now()-t<12e4;){let n=Math.round((Date.now()-t)/1e3);e.textContent=`Geraet startet neu ... warte auf Wiederverbindung (${n}s)`;try{let r=new AbortController,o=setTimeout(()=>r.abort(),1500),l=await fetch(\"/api/state\",{signal:r.signal,cache:\"no-store\"});if(clearTimeout(o),l.ok){e.textContent=\"Update abgeschlossen \\u2014 Portal wird neu geladen ...\",setTimeout(()=>location.reload(),800);return}}catch{}await new Promise(r=>setTimeout(r,1500))}e.textContent=\"Geraet meldet sich nicht zurueck \\u2014 Seite bitte manuell neu laden.\"}function Me(){let e=s(\"ota_file\"),t=e.files&&e.files[0];if(!t){a(\"Bitte zuerst eine .bin-Datei waehlen\");return}if(!confirm(`Firmware \"${t.name}\" (${F(t.size)}) einspielen? Das Geraet startet danach neu.`))return;let n=s(\"ota_progress\"),r=s(\"ota_bar_wrap\"),o=s(\"ota_bar\"),l=s(\"btn-ota\");l.disabled=!0,r.style.display=\"block\",r.classList.remove(\"indet\"),o.style.width=\"0%\";let i=new XMLHttpRequest,p=Date.now();i.open(\"POST\",\"/api/ota\"),i.upload.onprogress=c=>{if(!c.lengthComputable)return;let S=c.loaded/c.total*100;o.style.width=`${S.toFixed(1)}%`;let k=(Date.now()-p)/1e3,y=k>.3?c.loaded/k:0,D=y>0?Math.max(1,Math.round((c.total-c.loaded)/y)):0;n.textContent=`Upload ${Math.round(S)} %  \\xB7  ${F(c.loaded)} / ${F(c.total)}`+(y>0?`  \\xB7  ${F(y)}/s  \\xB7  noch ~${D}s`:\"\")},i.upload.onload=()=>{o.style.width=\"100%\",r.classList.add(\"indet\"),n.textContent=\"Upload fertig \\u2014 Geraet prueft und aktiviert das Image ...\"},i.onload=()=>{r.classList.remove(\"indet\"),i.status===200?(o.style.width=\"100%\",a(\"Firmware aktualisiert, Neustart\"),De(n)):(l.disabled=!1,r.style.display=\"none\",n.textContent=`Fehler ${i.status}: ${i.responseText}`,a(\"OTA fehlgeschlagen\"))},i.onerror=()=>{l.disabled=!1,r.classList.remove(\"indet\"),r.style.display=\"none\",n.textContent=\"Upload-Fehler (Verbindung abgebrochen). Nochmal versuchen.\"},n.textContent=\"Upload startet ...\",i.send(t)}async function ve(){if(confirm(\"Wirklich auf Werkseinstellungen zuruecksetzen? Alle Zugangsdaten werden neu erzeugt.\"))try{await d.factoryReset(),a(\"reset \\xB7 neustart\")}catch(e){a(`Fehler: ${e instanceof Error?e.message:String(e)}`)}}async function q(){if(L()===\"status\")try{let e=await d.clients(),t=s(\"cli_body\");if(!e.length){t.innerHTML='<tr><td colspan=\"6\" class=\"hint\">keine aktiven Verbindungen</td></tr>';return}t.innerHTML=e.map(n=>{let r=n.tx_dropped||0,o=r>0?`<b style=\"color:var(--danger)\">${F(r)}</b>`:\"\\u2014\";return`<tr><td data-label=\"Peer\" style=\"font-family:ui-monospace,monospace\">${u(n.peer)}</td><td data-label=\"Uptime\" style=\"text-align:center\">${oe(n.connected_ms)}</td><td data-label=\"RX\" style=\"text-align:right\">${F(n.rx_bytes)}</td><td data-label=\"TX\" style=\"text-align:right\">${F(n.tx_bytes)}</td><td data-label=\"Frames\" style=\"text-align:center\">${n.rx_frames}</td><td data-label=\"Verworfen\" style=\"text-align:right\">${o}</td></tr>`}).join(\"\")}catch{}}function Ce(e){return e?e>=-60?\"sehr gut\":e>=-70?\"gut\":e>=-78?\"schwach\":\"kritisch\":\"n/a\"}async function j(){if(L()===\"status\")try{let e=await d.stats();e.epoch_ms>17e11&&(x=e.epoch_ms-e.uptime_ms);let t=e.epoch_ms>17e11?new Date(e.epoch_ms).toLocaleString(\"de-DE\"):\"nicht synchronisiert\";s(\"gwstat\").textContent=`Uhrzeit (NTP) : ${t}\n"
"IP-Adresse    : ${e.ip||\"\\u2014\"}\n"
"WLAN-Signal   : ${e.rssi?`${e.rssi} dBm (${Ce(e.rssi)})`:\"n/a\"}\n"
"Uptime        : ${oe(e.uptime_ms)}\n"
"Aktive Clients: ${e.clients}\n"
"Freier Heap   : ${F(e.heap_free)}\n"
"Groesster Block: ${F(e.heap_max)}`,s(\"stats\").textContent=`RX vom TCM515 : ${F(e.tcm_rx_bytes)} / ${e.tcm_rx_frames} Frames\n"
"TX an TCM515  : ${F(e.tcm_tx_bytes)} / ${e.tcm_tx_frames} Frames`}catch{}}var Re=60,Le=\"\\u2193\",He=\"\\u2191\",x=null,E={246:\"RPS\",213:\"1BS\",165:\"4BS\",210:\"VLD\",209:\"MSC\",166:\"ADT\",212:\"UTE\"},_e={1:\"Funk (ERP1)\",2:\"Antwort\",3:\"Sub-Tel\",4:\"Event\",5:\"Command\",6:\"Smart-Ack\",7:\"Remote-Man\",9:\"Funk (ERP2)\",10:\"802.15.4\",11:\"Command 2.4\"},ue=\"eul_dev_eep\",ce=\"eul_dev_name\",P=\"eul_dev_model\",h=N(ue),w=N(ce),T=N(P),R=new Map;function N(e){try{let t=localStorage.getItem(e);return t?JSON.parse(t):{}}catch{return{}}}function C(e,t){try{localStorage.setItem(e,JSON.stringify(t))}catch{}}function $(){C(ue,h)}function xe(e,t,n){let r=0;for(let o=0;o<n;o++){let l=t+o,i=l>>3;if(i>=e.length)return null;r=r<<1|e[i]>>7-(l&7)&1}return r>>>0}function Pe(e){return(Math.round(e*100)/100).toString()}function $e(e,t){let n=A[e];if(!n||!n.lin)return\"\";let r=[];for(let o of n.lin){let l=xe(t,o.sb,o.w);if(l===null)continue;let[i,p]=o.lo,[c,S]=o.hi;if(c===i)continue;let k=p+(l-i)*(S-p)/(c-i);r.push(`${o.k} ${Pe(k)}${o.u?\" \"+o.u:\"\"}`)}return r.join(\" \\xB7 \")}var J=[\"Wippe A unten\",\"Wippe A oben\",\"Wippe B unten\",\"Wippe B oben\",\"Taste 5\",\"Taste 6\",\"Taste 7\",\"Taste 8\"];function Ve(e,t){let n=(e&16)!==0;if(!(t&32))return n?\"Taste(n) gedr\\xFCckt\":\"losgelassen\";if(!n&&e===0)return\"losgelassen\";let r=`${J[e>>5&7]} ${n?\"gedr\\xFCckt\":\"losgelassen\"}`;return e&1&&(r+=` + ${J[e>>1&7]}`),r}function Ie(e){return e&1?\"Kontakt geschlossen\":\"Kontakt offen\"}function We(e){if(e.length!==4)return\"\";let t=e[0],n=e[1],r=e[3];return r&8?t===1?r&1?\"Einschalten\":\"Ausschalten\":t===2?`Dimmen auf ${n}%${r&1?\"\":\" (aus)\"}`:\"\":\"Lerntelegramm\"}function X(e){return e.toString(16).padStart(2,\"0\").toUpperCase()}function Ge(e){if(e.length!==4)return null;let t=e[0],n=e[1],r=e[3];if(r&8||!(r&128))return null;let o=t>>2,l=(t&3)<<5|n>>3;return`A5-${X(o)}-${X(l)}`}function Ue(e,t,n,r){if(e===165){let l=Ge(t);if(l){h[r]!==l&&(h[r]=l,$());let i=A[l]?.t;return`Lerntelegramm ${l}${i?\": \"+i:\"\"}`}}let o=h[r];if(o){let l=$e(o,t);if(l)return l}return e===246?Ve(t[0]??0,n):e===213?Ie(t[0]??0):e===165?We(t):\"\"}function Ke(e){if(x===null)return(e/1e3).toFixed(3);let t=new Date(x+e),n=r=>String(r).padStart(2,\"0\");return`${n(t.getHours())}:${n(t.getMinutes())}:${n(t.getSeconds())}.${String(t.getMilliseconds()).padStart(3,\"0\")}`}function V(e){return e.map(t=>t.toString(16).padStart(2,\"0\")).join(\" \")}function Ne(e){return e.map(t=>t.toString(16).padStart(2,\"0\").toUpperCase()).join(\"-\")}function Oe(e){let t=e.indexOf(\" : \");if(t<0)return null;let n=[];for(let r of e.slice(t+3).trim().split(/\\s+/))if(/^[0-9a-fA-F]{2}$/.test(r))n.push(parseInt(r,16));else break;return n.length?n:null}function Ze(e,t,n){if(n.length<7||n[0]!==85)return null;let r=n[1]<<8|n[2],o=n[3],l=n[4],i=n.slice(6,6+r),p=n.slice(6+r,6+r+o);if(i.length<r)return null;let c=_e[l]||`0x${l.toString(16).padStart(2,\"0\")}`;if(l!==1)return{ms:e,dir:t,typ:c,rorg:\"\\u2014\",sender:\"\\u2014\",data:V(i),text:\"\",dbm:null,rep:0,raw:n};if(r<6)return null;let S=i[0],k=i.slice(r-5,r-1),y=i[r-1],D=i.slice(1,r-5),me=o>=6&&p.length>=6?-p[5]:null,de=y&15,O=`0x${S.toString(16).padStart(2,\"0\")}`,Fe=E[S]?`${E[S]} (${O})`:O,M=Ne(k);return R.has(M)||R.set(M,S),{ms:e,dir:t,typ:c,rorg:Fe,sender:M,data:V(D),text:Ue(S,D,y,M),dbm:me,rep:de,raw:n}}function g(e,t){return t>=0&&t<e.length?e[t].toString(16).padStart(2,\"0\"):\"??\"}function B(e,t,n){return e.slice(t,n).map(r=>r.toString(16).padStart(2,\"0\")).join(\" \")||\"\\u2014\"}function ze(e){let t=[];if(e.length<6||e[0]!==85)return t;let n=e[1]<<8|e[2],r=e[3],o=e[4];t.push({name:\"Sync\",hex:g(e,0)}),t.push({name:\"Data Length\",hex:B(e,1,3)}),t.push({name:\"Opt. Length\",hex:g(e,3)}),t.push({name:\"Packet Type\",hex:g(e,4)}),t.push({name:\"CRC8H\",hex:g(e,5)});let l=6,i=6+n;if(o===1&&n>=6){t.push({name:\"RORG\",hex:g(e,l)}),t.push({name:\"Data\",hex:B(e,l+1,i-5)}),t.push({name:\"Sender-ID\",hex:B(e,i-5,i-1)}),t.push({name:\"Status\",hex:g(e,i-1)});let c=i;r>=1&&t.push({name:\"SubTelNum\",hex:g(e,c)}),r>=5&&t.push({name:\"Destination\",hex:B(e,c+1,c+5)}),r>=6&&t.push({name:\"dBm\",hex:g(e,c+5)}),r>=7&&t.push({name:\"Security\",hex:g(e,c+6)})}else t.push({name:\"Data\",hex:B(e,l,i)}),r>0&&t.push({name:\"Optional\",hex:B(e,i,i+r)});let p=6+n+r;return t.push({name:\"CRC8D\",hex:g(e,p)}),t}function qe(e){let t=e.dbm===null?\"\":String(e.dbm),n=w[e.sender],r=`<span style=\"font-family:ui-monospace,monospace\">${u(e.sender)}</span>`+(n?` <b>${u(n)}</b>`:\"\"),o=e.rep>0?` <span title=\"\\xFCber ${e.rep} Repeater wiederholt\" style=\"color:#c47f00\">\\u{1F501}${e.rep}</span>`:\"\",l=`${e.sender} ${n||\"\"} ${e.rorg} ${e.typ} ${e.text}`.toLowerCase(),i=e.rep>0?\"background:rgba(196,127,0,0.10);\":\"\";return`<tr class=\"tel-row\" data-frame=\"${V(e.raw)}\" data-search=\"${u(l)}\" title=\"Klicken: ESP3-Rohframe feldweise zerlegt\" style=\"cursor:pointer;${i}\"><td data-label=\"Zeit\" style=\"font-family:ui-monospace,monospace\">${Ke(e.ms)}</td><td data-label=\"Ri.\" style=\"text-align:center;white-space:nowrap\">${e.dir}${o}</td><td data-label=\"Typ\">${u(e.typ)}</td><td data-label=\"RORG\">${u(e.rorg)}</td><td data-label=\"Absender\">${r}</td><td data-label=\"Daten\" style=\"font-family:ui-monospace,monospace\">${u(e.data)}</td><td data-label=\"Bedeutung\">${u(e.text)}</td><td data-label=\"dBm\" style=\"text-align:right\">${t}</td></tr>`}function je(e){let t=[];for(let o of e){let l=o.line.startsWith(\"<\")?Le:o.line.startsWith(\">\")?He:\"\";if(!l)continue;let i=Oe(o.line);if(!i)continue;let p=Ze(o.ms,l,i);p&&t.push(qe(p))}if(!t.length)return;let n=s(\"tel_body\");n.querySelector(\".hint\")&&(n.innerHTML=\"\"),n.insertAdjacentHTML(\"afterbegin\",t.reverse().join(\"\"));let r=n.querySelectorAll(\"tr.tel-row\");for(;r.length>Re;){let o=r[r.length-1],l=o.nextElementSibling;l&&l.classList.contains(\"tel-detail\")&&l.remove(),o.remove(),r=n.querySelectorAll(\"tr.tel-row\")}pe()}var Y=8,I=\"\";function Je(e){let t=e.trim().split(/\\s+/).filter(Boolean).map(i=>parseInt(i,16)),n=ze(t),r=document.createElement(\"tr\");if(r.className=\"tel-detail\",!n.length)return r.innerHTML=`<td colspan=\"${Y}\" class=\"hint\">Rohframe nicht verf\\xFCgbar</td>`,r;let o=n.map(i=>`<th>${u(i.name)}</th>`).join(\"\"),l=n.map(i=>`<td>${u(i.hex)}</td>`).join(\"\");return r.innerHTML=`<td colspan=\"${Y}\"><div class=\"rawwrap\"><div class=\"rawhex\">${u(e)}</div><table class=\"rawtbl\"><thead><tr>${o}</tr></thead><tbody><tr>${l}</tr></tbody></table></div></td>`,r}function pe(){s(\"tel_body\").querySelectorAll(\"tr.tel-row\").forEach(t=>{let n=!I||(t.getAttribute(\"data-search\")||\"\").includes(I);t.style.display=n?\"\":\"none\";let r=t.nextElementSibling;r&&r.classList.contains(\"tel-detail\")&&(r.style.display=n?\"\":\"none\")})}function Xe(e){let t=E[e];return Object.keys(A).filter(n=>!t||A[n].cls===t).sort()}function Ye(e){return E[parseInt(e.slice(0,2),16)]||\"\"}function Qe(e,t){let n=h[e]||\"\",r=Xe(t),o=['<option value=\"\">\\u2014 unbekannt \\u2014</option>'];n&&!r.includes(n)&&o.push(`<option value=\"${u(n)}\" selected>${u(n)} \\u2014 (kein Profil im Katalog)</option>`);for(let l of r)o.push(`<option value=\"${l}\"${l===n?\" selected\":\"\"}>${u(l+\" \\u2014 \"+A[l].t)}</option>`);return`<select data-sender=\"${u(e)}\" class=\"dev-eep\">${o.join(\"\")}</select>`}function et(e){let t=E[e];return v.filter(n=>!t||Ye(n.eep)===t)}function tt(e,t){let n=T[e]||\"\",r=['<option value=\"\">\\u2014 (nicht zugeordnet) \\u2014</option>'];for(let o of et(t))r.push(`<option value=\"${u(o.key)}\"${o.key===n?\" selected\":\"\"}>${u(o.model+\" \\u2014 \"+o.typ)}</option>`);return`<select data-sender=\"${u(e)}\" class=\"dev-eltako\">${r.join(\"\")}</select>`}function nt(){let e=s(\"dev_body\");if(!(!e||!R.size)){e.querySelector(\".hint\")&&(e.innerHTML=\"\");for(let[t,n]of R){let r=e.querySelector(`tr[data-sender=\"${t}\"]`);if(!r)r=document.createElement(\"tr\"),r.setAttribute(\"data-sender\",t),r.innerHTML=`<td data-label=\"Absender\" style=\"font-family:ui-monospace,monospace\">${u(t)}</td><td data-label=\"Name\"><input type=\"text\" class=\"dev-name\" data-sender=\"${u(t)}\" maxlength=\"31\" autocomplete=\"off\" placeholder=\"z.B. Taster Flur\" value=\"${u(w[t]||\"\")}\"></td><td data-label=\"Eltako Ger\\xE4t\">${tt(t,n)}</td><td data-label=\"EEP-Profil\">${Qe(t,n)}</td>`,e.appendChild(r);else{let o=r.querySelector(\"select.dev-eep\");o&&document.activeElement!==o&&o.value!==(h[t]||\"\")&&(o.value=h[t]||\"\");let l=r.querySelector(\"select.dev-eltako\");l&&document.activeElement!==l&&l.value!==(T[t]||\"\")&&(l.value=T[t]||\"\")}}}}function rt(){let e=s(\"dev_body\");e&&e.addEventListener(\"change\",t=>{let n=t.target;if(!(n instanceof HTMLElement))return;let r=n.getAttribute(\"data-sender\");if(!r)return;let o=n.closest(\"tr\");if(n instanceof HTMLSelectElement&&n.classList.contains(\"dev-eltako\")){let l=v.find(p=>p.key===n.value);l?(T[r]=l.key,h[r]=l.eep):delete T[r],C(P,T),$();let i=o?.querySelector(\"select.dev-eep\");i&&(i.value=h[r]||\"\");return}if(n instanceof HTMLSelectElement&&n.classList.contains(\"dev-eep\")){n.value?h[r]=n.value:delete h[r],$();let l=v.find(i=>i.key===T[r]);if(l&&l.eep!==n.value){delete T[r],C(P,T);let i=o?.querySelector(\"select.dev-eltako\");i&&(i.value=\"\")}return}if(n instanceof HTMLInputElement&&n.classList.contains(\"dev-name\")){let l=n.value.trim();l?w[r]=l:delete w[r],C(ce,w)}})}var Q=0,f=!1;async function ee(){let e=L();if(!(e!==\"status\"&&e!==\"konsole\"&&e!==\"geraete\"))try{let t=await d.console(Q);if(Q=t.last_seq,!t.lines.length||(je(t.lines),nt(),f))return;let n=s(\"con\"),r=t.lines.map(l=>`[${(l.ms/1e3).toFixed(3).padStart(9,\" \")}] ${l.line}`).join(`\n"
"`);n.textContent=n.textContent?n.textContent+`\n"
"`+r:r;let o=n.textContent.split(`\n"
"`);o.length>400&&(n.textContent=o.slice(-400).join(`\n"
"`)),s(\"autoscroll\").checked&&(n.scrollTop=n.scrollHeight)}catch{}}var te=0,st=200,ot=[\"INFO\",\"WARN\",\"FEHLER\"],lt=[\"var(--hint)\",\"#c47f00\",\"var(--danger)\"];function it(e,t){if(t>0){let n=new Date(t),r=o=>String(o).padStart(2,\"0\");return`${r(n.getHours())}:${r(n.getMinutes())}:${r(n.getSeconds())}`}return`${(e/1e3).toFixed(1)}s`}function at(e){let t=e.lvl>=0&&e.lvl<=2?e.lvl:0;return`<tr><td data-label=\"Zeit\" style=\"font-family:ui-monospace,monospace;white-space:nowrap\">${it(e.ms,e.ts)}</td><td data-label=\"Level\" style=\"color:${lt[t]};font-weight:600\">${ot[t]}</td><td data-label=\"Quelle\" style=\"font-family:ui-monospace,monospace\">${u(e.tag)}</td><td data-label=\"Meldung\">${u(e.msg)}</td></tr>`}async function ne(){if(L()===\"events\")try{let e=await d.events(te);if(te=e.last_seq,!e.events.length)return;let t=s(\"evt_body\");for(t.querySelector(\".hint\")&&(t.innerHTML=\"\"),t.insertAdjacentHTML(\"afterbegin\",e.events.map(at).reverse().join(\"\"));t.children.length>st;)t.removeChild(t.lastElementChild)}catch{}}function W(){let e=s(\"con\"),t=document.createRange();t.selectNodeContents(e);let n=window.getSelection();n&&(n.removeAllRanges(),n.addRange(t))}async function ut(){let e=s(\"con\").textContent||\"\";if(!e){a(\"Konsole ist leer\");return}try{await navigator.clipboard.writeText(e),a(`${e.length} Zeichen kopiert`)}catch{W(),a(\"Bitte manuell kopieren (Strg+C / Cmd+C)\")}}function ct(){s(\"con\").textContent=\"\",a(\"Konsole geleert\")}function pt(){f=!f,s(\"btn-pause\").textContent=f?\"Weiter\":\"Pause\",a(f?\"Konsole angehalten\":\"Konsole laeuft\")}function mt(){s(\"con\").addEventListener(\"keydown\",t=>{(t.ctrlKey||t.metaKey)&&t.key.toLowerCase()===\"a\"&&(t.preventDefault(),W())}),document.addEventListener(\"keydown\",t=>{if(!(t.ctrlKey||t.metaKey)||t.key.toLowerCase()!==\"a\"||!document.getElementById(\"tab-konsole\")?.classList.contains(\"active\"))return;let r=document.activeElement;r&&(r.tagName===\"INPUT\"||r.tagName===\"TEXTAREA\"||r.tagName===\"SELECT\")||(t.preventDefault(),W())})}function dt(){he(),Se(),G=new b(s(\"token\")),le=new b(s(\"adminp\")),U=new b(s(\"api_token\")),K=new b(s(\"ota_token\")),s(\"btn-scan\").addEventListener(\"click\",Z),s(\"btn-regen\").addEventListener(\"click\",z),s(\"btn-regen2\").addEventListener(\"click\",z),s(\"btn-regen-ota\").addEventListener(\"click\",Ae),s(\"btn-save\").addEventListener(\"click\",we),s(\"btn-reboot\").addEventListener(\"click\",Ee),s(\"btn-ota\").addEventListener(\"click\",Me),s(\"btn-factory\").addEventListener(\"click\",ve),s(\"btn-clear\").addEventListener(\"click\",ct),s(\"btn-pause\").addEventListener(\"click\",pt),s(\"btn-copy\").addEventListener(\"click\",ut),s(\"btn-preset-ha\").addEventListener(\"click\",fe),s(\"btn-baseid-read\").addEventListener(\"click\",Be),s(\"btn-baseid-write\").addEventListener(\"click\",be),rt();let e=s(\"tel_filter\");e.addEventListener(\"input\",()=>{I=e.value.trim().toLowerCase(),pe()}),s(\"tel_body\").addEventListener(\"click\",t=>{let n=t.target.closest(\"tr.tel-row\");if(!n)return;let r=n.nextElementSibling;if(r&&r.classList.contains(\"tel-detail\")){r.remove();return}let o=n.getAttribute(\"data-frame\");o&&n.after(Je(o))}),mt(),Te(),ke(),Z(),setInterval(q,3e3),setInterval(j,3e3),setInterval(ee,1e3),setInterval(ne,2e3),q(),j(),ee(),ne()}dt();})();\n"
"</script>\n"
"</body>\n"
"</html>\n"
"\n"
;
