// AUTO-GENERATED von scripts/gen_eo_man_data.py - NICHT von Hand editieren.
//
// Quellen (Upstream, MIT):
//   grimmpp/enocean-device-manager : eo_man/data/data_helper.py (EEP_MAPPING),
//                                    eo_man/data/const.py (GatewayDeviceType)
//   grimmpp/eltako14bus            : eltakobus/device.py (KeyFunction)
//
// Neu erzeugen: python scripts/gen_eo_man_data.py

/** Ein Eintrag des EO-Man-Geraetekatalogs (dort: EEP_MAPPING). */
export interface CatalogEntry {
    /** Hardware-Typ, z.B. "FSR14_4x". Nicht eindeutig: ein Typ kann mehrere EEPs haben. */
    hw: string;
    brand?: string;
    /** EEP des Geraets (was es sendet bzw. worauf es hoert). */
    eep?: string;
    /** Home-Assistant-Plattform, z.B. "light". */
    platform?: string;
    /** EEP, mit dem HA den Aktor ansteuert (nur bei Aktoren). */
    senderEep?: string;
    desc?: string;
    /** Anzahl Kanaele/Adressen des Geraets. */
    channels?: number;
    /** Gesetzt, wenn der Eintrag ein Gateway ist - Wert = HA device_type. */
    gateway?: string;
    meterTariffs?: string;
    /** PCT14-Funktionsgruppe, in die der HA-Sender eingetragen werden muss. */
    pct14Fg?: number;
    /** PCT14-Tastenfunktion fuer den HA-Sender. */
    pct14Kf?: number;
}


export const DEVICE_CATALOG: CatalogEntry[] = [
    {"hw": "BusObject", "brand": "unknown", "eep": "unknown", "platform": "unknown", "desc": "unknown bus device"},
    {"hw": "FAM14", "brand": "Eltako", "desc": "Bus Gateway", "gateway": "fam14"},
    {"hw": "FGW14_USB", "brand": "Eltako", "desc": "Bus Gateway", "gateway": "fgw14usb"},
    {"hw": "FTD14", "brand": "Eltako", "desc": "Bus Gateway", "gateway": "ftd14"},
    {"hw": "FGW14", "brand": "Eltako", "desc": "Bus Gateway"},
    {"hw": "FAM-USB", "brand": "Eltako", "desc": "USB Gateway", "gateway": "fam-usb"},
    {"hw": "USB300", "brand": "unknown", "desc": "USB Gateway", "gateway": "enocean-usb300"},
    {"hw": "MGW (LAN)", "brand": "PioTek", "desc": "USB Gateway", "gateway": "lan"},
    {"hw": "MGW (USB)", "brand": "PioTek", "desc": "USB Gateway", "gateway": "esp3-gateway"},
    {"hw": "FTS14EM", "brand": "Eltako", "eep": "F6-02-01", "platform": "binary_sensor", "desc": "Wired Rocker switch", "channels": 1},
    {"hw": "FTS14EM", "brand": "Eltako", "eep": "F6-02-02", "platform": "binary_sensor", "desc": "Wired Rocker switch", "channels": 1},
    {"hw": "FTS14EM", "brand": "Eltako", "eep": "F6-10-00", "platform": "binary_sensor", "desc": "Window handle", "channels": 1},
    {"hw": "FTS14EM", "brand": "Eltako", "eep": "D5-00-01", "platform": "binary_sensor", "desc": "Contact sensor", "channels": 1},
    {"hw": "FTS14EM", "brand": "Eltako", "eep": "A5-08-01", "platform": "binary_sensor", "desc": "Occupancy sensor", "channels": 1},
    {"hw": "FT55", "brand": "Eltako", "eep": "F6-02-01", "platform": "binary_sensor", "desc": "Wireless 4-way pushbutton", "channels": 1},
    {"hw": "F4T55E", "brand": "Eltako", "eep": "F6-02-01", "platform": "binary_sensor", "desc": "Wireless 4-way pushbutton in E-Design55", "channels": 1},
    {"hw": "FFTE", "brand": "Eltako", "eep": "F6-10-00", "platform": "binary_sensor", "desc": "window and door contacts", "channels": 1},
    {"hw": "FTKE", "brand": "Eltako", "eep": "F6-10-00", "platform": "binary_sensor", "desc": "window and door contacts", "channels": 1},
    {"hw": "FTK", "brand": "Eltako", "eep": "F6-10-00", "platform": "binary_sensor", "desc": "window and door contacts", "channels": 1},
    {"hw": "FSDG14", "brand": "Eltako", "eep": "A5-12-01", "platform": "sensor", "desc": "Electricity Meter", "channels": 1},
    {"hw": "F3Z14D", "brand": "Eltako", "eep": "A5-12-01", "platform": "sensor", "desc": "Electricity Meter", "channels": 3},
    {"hw": "FSVA-230V-10A-Power-Meter", "brand": "Eltako", "eep": "A5-12-01", "platform": "sensor", "desc": "Power Meter", "channels": 1, "meterTariffs": "[]"},
    {"hw": "F3Z14D", "brand": "Eltako", "eep": "A5-12-02", "platform": "sensor", "desc": "Gas Meter", "channels": 3},
    {"hw": "F3Z14D", "brand": "Eltako", "eep": "A5-12-03", "platform": "sensor", "desc": "Water Meter", "channels": 3},
    {"hw": "FWZ14_65A", "brand": "Eltako", "eep": "A5-12-01", "platform": "sensor", "desc": "Electricity Meter", "channels": 1, "meterTariffs": "[]"},
    {"hw": "FWG14MS", "brand": "Eltako", "eep": "A5-13-01", "platform": "sensor", "desc": "Weather Station Gateway", "channels": 1},
    {"hw": "MS", "brand": "Eltako", "eep": "A5-13-01", "platform": "sensor", "desc": "Weather Station", "channels": 1},
    {"hw": "WMS", "brand": "Eltako", "eep": "A5-13-01", "platform": "sensor", "desc": "Weather Station", "channels": 1},
    {"hw": "FWS61", "brand": "Eltako", "eep": "A5-13-01", "platform": "sensor", "desc": "Weather Station", "channels": 1},
    {"hw": "FLGTF", "brand": "Eltako", "eep": "A5-04-02", "platform": "sensor", "desc": "Temperature and Humidity Sensor", "channels": 1},
    {"hw": "FLT58", "brand": "Eltako", "eep": "A5-04-02", "platform": "sensor", "desc": "Temperature and Humidity Sensor", "channels": 1},
    {"hw": "FFT60", "brand": "Eltako", "eep": "A5-04-02", "platform": "sensor", "desc": "Temperature and Humidity Sensor", "channels": 1},
    {"hw": "FTFSB", "brand": "Eltako", "eep": "A5-04-02", "platform": "sensor", "desc": "Temperature and Humidity Sensor", "channels": 1},
    {"hw": "FHD60SB", "brand": "Eltako", "eep": "A5-06-01", "platform": "sensor", "desc": "Light - Twilight and daylight Sensor", "channels": 1},
    {"hw": "FABH65S", "brand": "Eltako", "eep": "A5-08-01", "platform": "sensor", "desc": "Light-, Temperature-, Occupancy Sensor", "channels": 1},
    {"hw": "FBH65", "brand": "Eltako", "eep": "A5-08-01", "platform": "sensor", "desc": "Light-, Temperature-, Occupancy Sensor", "channels": 1},
    {"hw": "FBH65S", "brand": "Eltako", "eep": "A5-08-01", "platform": "sensor", "desc": "Light-, Temperature-, Occupancy Sensor", "channels": 1},
    {"hw": "FBH65TF", "brand": "Eltako", "eep": "A5-08-01", "platform": "sensor", "desc": "Light-, Temperature-, Occupancy Sensor", "channels": 1},
    {"hw": "FLGTF", "brand": "Eltako", "eep": "A5-09-0C", "platform": "sensor", "desc": "Air Quality, Temperature and Humidity Sensor", "channels": 1},
    {"hw": "FUTH", "brand": "Eltako", "eep": "A5-10-06", "platform": "sensor", "desc": "Temperature Sensor and Controller", "channels": 1},
    {"hw": "FUTH-feature", "brand": "Eltako", "eep": "A5-10-12", "platform": "sensor", "desc": "Temperature Sensor and Controller and Humidity Sensor", "channels": 1},
    {"hw": "FUD14", "brand": "Eltako", "eep": "A5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Light dimmer", "channels": 1, "pct14Fg": 3, "pct14Kf": 32},
    {"hw": "FUD14_800W", "brand": "Eltako", "eep": "A5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Light dimmer", "channels": 1, "pct14Fg": 3, "pct14Kf": 32},
    {"hw": "FDG14", "brand": "Eltako", "eep": "A5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Dali Gateway", "channels": 16, "pct14Fg": 1, "pct14Kf": 32},
    {"hw": "FD2G14", "brand": "Eltako", "eep": "A5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Dali Gateway", "channels": 16, "pct14Fg": 1, "pct14Kf": 32},
    {"hw": "FMZ14", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "F6-02-01", "desc": "Relay", "channels": 1, "pct14Fg": 1, "pct14Kf": 1},
    {"hw": "FSR14", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 1, "pct14Fg": 2, "pct14Kf": 51},
    {"hw": "FSR14_1x", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 1, "pct14Fg": 2, "pct14Kf": 51},
    {"hw": "FSR14_2x", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 2, "pct14Fg": 2, "pct14Kf": 51},
    {"hw": "FSR14_4x", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 4, "pct14Fg": 2, "pct14Kf": 51},
    {"hw": "FSR14M_2x", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 2, "pct14Fg": 2, "pct14Kf": 51},
    {"hw": "FSR14M_2x-feature", "brand": "Eltako", "eep": "A5-12-01", "platform": "sensor", "desc": "Electricity Meter", "channels": 2, "meterTariffs": "[]"},
    {"hw": "F4SR14_LED", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 4, "pct14Fg": 2, "pct14Kf": 51},
    {"hw": "FSB14", "brand": "Eltako", "eep": "G5-3F-7F", "platform": "cover", "senderEep": "H5-3F-7F", "desc": "Cover", "channels": 2, "pct14Fg": 2, "pct14Kf": 31},
    {"hw": "FHK14", "brand": "Eltako", "eep": "A5-10-06", "platform": "climate", "senderEep": "A5-10-06", "desc": "Heating/Cooling", "channels": 2, "pct14Fg": 3, "pct14Kf": 65},
    {"hw": "F4HK14", "brand": "Eltako", "eep": "A5-10-06", "platform": "climate", "senderEep": "A5-10-06", "desc": "Heating/Cooling", "channels": 4, "pct14Fg": 3, "pct14Kf": 65},
    {"hw": "FAE14SSR", "brand": "Eltako", "eep": "A5-10-06", "platform": "climate", "senderEep": "A5-10-06", "desc": "Heating/Cooling", "channels": 2, "pct14Fg": 3, "pct14Kf": 65},
    {"hw": "FMZ61", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "F6-02-01", "desc": "Relay", "channels": 1},
    {"hw": "FSR61-230V", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 1},
    {"hw": "FSR61NP-230V", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 1},
    {"hw": "FSR61/8-24V UC", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 1},
    {"hw": "FSR61-230V", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 1},
    {"hw": "FSR61G-230V", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 1},
    {"hw": "FSR61LN-230V", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 2},
    {"hw": "FLC61NP-230V", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 1},
    {"hw": "FR62-230V", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 1},
    {"hw": "FR62NP-230V", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 1},
    {"hw": "FL62-230V", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 1},
    {"hw": "FL62NP-230V", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 1},
    {"hw": "FSSA-230V", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Socket Switch Actuator", "channels": 1},
    {"hw": "FSVA-230V-10A", "brand": "Eltako", "eep": "M5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Socket Switch Actuator", "channels": 1},
    {"hw": "FUD61NP-230V", "brand": "Eltako", "eep": "A5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Light dimmer", "channels": 1},
    {"hw": "FUD61NPN-230V", "brand": "Eltako", "eep": "A5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Light dimmer", "channels": 1},
    {"hw": "FD62NP-230V", "brand": "Eltako", "eep": "A5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 1},
    {"hw": "FD62NPN-230V", "brand": "Eltako", "eep": "A5-38-08", "platform": "light", "senderEep": "A5-38-08", "desc": "Relay", "channels": 1},
    {"hw": "FSB61-230V", "brand": "Eltako", "eep": "G5-3F-7F", "platform": "cover", "senderEep": "H5-3F-7F", "desc": "Cover", "channels": 1},
    {"hw": "FSB61NP-230V", "brand": "Eltako", "eep": "G5-3F-7F", "platform": "cover", "senderEep": "H5-3F-7F", "desc": "Cover", "channels": 1},
    {"hw": "FJ62/12-36V DC", "brand": "Eltako", "eep": "G5-3F-7F", "platform": "cover", "senderEep": "H5-3F-7F", "desc": "Cover", "channels": 1},
    {"hw": "FJ62NP-230V", "brand": "Eltako", "eep": "G5-3F-7F", "platform": "cover", "senderEep": "H5-3F-7F", "desc": "Cover", "channels": 1},
    {"hw": "FSUD-230V", "brand": "Eltako", "eep": "G5-3F-7F", "platform": "cover", "senderEep": "H5-3F-7F", "desc": "Cover", "channels": 1},
];

/** PCT14-Tastenfunktionen: [Name, Nummer]. */
export const KEY_FUNCTIONS: ReadonlyArray<readonly [string, number]> = [
    ["NO_FUNCTION", 0],
    ["UNIVERSAL_PUSH_BUTTON", 1],
    ["DIRECTION_PUSH_BUTTON_TOP_ON", 2],
    ["DIRECTION_PUSH_BUTTON_BOTTOM_ON", 3],
    ["CENTRAL_OFF", 4],
    ["CENTRAL_ON", 5],
    ["SCENE_PUSHBUTTON", 6],
    ["SEQUENTIAL_SCENE_PUSH_BUTTON", 7],
    ["LIGHT_ALARM", 8],
    ["DIMMING_VALUE_IN_PERCENTAGE", 10],
    ["STAIRCASE_PUSH_BUTTON", 11],
    ["CENTRAL_UP_DOWN", 12],
    ["CENTRAL_UP_DOWN_WITH_DYNAMIC_PRIORITY", 14],
    ["WINDOW_CONTACT", 16],
    ["NO_WINDOW_CONTACT", 17],
    ["NC_WINDOW_CONTACT", 18],
    ["CENTRAL_UP_DOWN_WITH_STATIC_PRIORITY", 19],
    ["CENTRAL_OFF_WITH_STATIC_PRIORITY", 21],
    ["CENTRAL_ON_WITH_STATIC_PRIORITY", 22],
    ["UNIVERSAL_PUSH_BUTTON_ES", 23],
    ["UNIVERSAL_PUSH_BUTTON_ER", 24],
    ["WINDOW_HANDLE_FTKE", 25],
    ["NO_WINDOW_HANDLE", 26],
    ["NC_WINDOW_HANDLE", 27],
    ["FOUR_FOLD_TEST_PUSH_BUTTON", 29],
    ["FOUR_FOLD_PUSH_BUTTON", 30],
    ["OPERATIONS_COMMAND_WITH_TIME_VALUE_TRASMISSION_FROM_CONTROLLER", 31],
    ["DIMMING_VALUE_FROM_CONTROLLER", 32],
    ["FBH_WITH_BRIGHTNESS_EVALUATION", 33],
    ["FBH_WITHOUT_BRIGHTNESS_EVALUATION", 34],
    ["MOTION_DETECTOR_ACCORDING_TO_EEP_A5_07_01", 35],
    ["FAH60_WITH_DAYLIGHT_EVALUATION", 36],
    ["FAH60_TWILIGHT_PSUH_BUTTON", 37],
    ["FAH60_TWILIGHT_DIMMER", 38],
    ["FAH60_FOR_CONTROL_OF_ROLLER_SHUTTER", 39],
    ["FWG14MS_WEATHER_STATION", 42],
    ["FIH65B_FOR_CONSTANT_LIGHT_CONTROL", 44],
    ["TARGET_BRIGHTNESS_MEMORY_BUTTON", 47],
    ["WATER_SENSOR_ACCORDING_TO_EEP_A5_30_30", 48],
    ["WATER_SENSOR_RPS_TELEGRAM", 49],
    ["SMOKE_DETECTOR", 50],
    ["SWITCHING_STATE_FROM_CONTROLLER", 51],
    ["ACTIVATION_SNOOZE_FUNCTION", 53],
    ["FBH_WITH_BRIGHTNESS_EVALUATION_ONLY_AT_SWITCH_ON_FOR_WARM_LIGHT", 54],
    ["LINKED_ACTUATOR_FEDDBACK", 60],
    ["TEMPERATURE_CONTROLLER_WITH_SETPOINT", 61],
    ["TEMPERATURE_CONTROLLER_WITHOUT_SLIDE_SWITCH", 62],
    ["TEMPERATURE_CONTROLLER_WITH_SLIDE_SWITCH_SUN_MOON", 63],
    ["TEMPERATURE_CONTROLLER_ACCORDING_EEP_A5_10_06_FTR55D", 64],
    ["TEMPERATURE_CONTROLLER_SETPOINT", 65],
    ["TEMPERATURE_CONTROLLER_ACCORDING_EEP_A5_02_05", 66],
    ["HUMIDITY_TEMPERATURE_SENSOR_ACCORDING_TO_EEP_A5_04_02", 67],
    ["TEMPERATURE_SENSOR_ACCORDING_TO_EEP_A5_10_02", 68],
    ["HUMIDITY_TEMPERATURE_SENSOR_FUTH_ACCORDING_TO_EEP_A5_10_12", 69],
    ["TEMPERATURE_SENSOR_ACCORDING_TO_EEP_A5_10_03", 70],
    ["TEMPERATURE_SENSOR_ACCORDING_TO_EEP_A5_10_03_LIMITED_TEMP_RANGE", 71],
    ["CENTRAL_ON_WITH_LATCHING_OF_PRIORITY", 77],
    ["CENTRAL_OFF_WITH_LATCHING_OF_PRIORITY", 78],
    ["DIRECTION_PUSH_BUTTON_FOR_LOCKING_TURNAROUND_AUTOMATIC", 80],
    ["CENTRAL_UP", 82],
    ["CENTRAL_DOWN", 83],
    ["CENTRAL_STOP", 84],
    ["DIRECTION_PUSH_BUTTON_FOR_LOCKING_SHADING_SCENE_1", 98],
    ["DIRECTION_PUSH_BUTTON_FOR_LOCKING_SHADING_SCENE_2", 99],
    ["DIRECTION_PUSH_BUTTON_FOR_LOCKING_SHADING_SCENE_3", 100],
    ["DIRECTION_PUSH_BUTTON_FOR_LOCKING_SHADING_SCENE_4", 101],
    ["DIRECTION_PUSH_BUTTON_FOR_LOCKING", 102],
    ["FAH60_WITH_DAYLIGHT_EVALUATION_SWITCH_OFF_ONLY", 103],
    ["FAH60_WITH_DAYLIGHT_EVALUATION_SWITCH_ON_ONLY", 104],
    ["SCENE_PUSH_BUTTON", 105],
    ["TIME", 110],
    ["WINDOW_HANDLE_ACCORDING_TO_EEP_A5_14_09", 120],
    ["WINDOW_HANDLE_ACCORDING_TO_EEP_A5_14_0A", 121],
    ["RESOLVE_PRIORITY", 123],
    ["WINDOW_HANDLE_ACCORDING_TO_EEP_A5_14_09_AS_NCC", 124],
    ["WINDOW_HANDLE_ACCORDING_TO_EEP_A5_14_09_AS_NOC", 125],
    ["WINDOW_HANDLE_ACCORDING_TO_EEP_A5_14_0A_AS_NCC", 126],
    ["WINDOW_HANDLE_ACCORDING_TO_EEP_A5_14_0A_AS_NOC", 127],
    ["DRIVING_COMMAND_WITH_RUN_TIME_AND_REVERSE_TIME", 128],
    ["HEAT_PUMP", 137],
    ["HUMIDITY_TEMPERATURE_SENSOR_ACCORDING_TO_EEP_A5_04_03", 139],
    ["HUMIDITY_TEMPERATURE_SENSOR_FUTH_TEMP_SETPOINT_ACCORDING_TO_EEP_A5_10_12_BUTH", 149],
    ["VIBRATION_SENSOR_ACCORDING_TO_EEP_A5_14_05", 156],
    ["BRIGHTNESS_SENSOR_ACCORDING_TO_EEP_A5_06_02_TWILIGHT_SWITCH", 157],
    ["BRIGHTNESS_SENSOR_ACCORDING_TO_EEP_A5_06_03_TWILIGHT_SWITCH", 158],
    ["CENTRAL_OFF_WITH_IMMEDIATE_PRIORITY", 159],
    ["CENTRAL_ON_WITH_IMMEDIATE_PRIORITY", 160],
    ["VIBRATION_SENSOR_ACCORDING_TO_EEP_A5_14_05_WITH_DELAY", 161],
    ["WINDOW_SENSOR_ACCORDING_TO_EEP_A5_14_01", 162],
    ["WINDOW_SENSOR_ACCORDING_TO_EEP_A5_14_03", 163],
];
